#ifndef _DEFS_TBL
#define _DEFS_TBL 1
extern const uint32_t __MDM5ZTNkMzJ9=0x03;
extern "C" uint32_t  __stdcall __MDM5ZTNkMzJ9_g(){return __MDM5ZTNkMzJ9;};
extern const uint32_t __OWUzZDMyN2Qc=0x9E;
extern "C" uint32_t  __stdcall __OWUzZDMyN2Qc_g(){return __OWUzZDMyN2Qc;};
extern const uint32_t __M2QzMjdkMWO_=0x3D;
extern "C" uint32_t  __stdcall __M2QzMjdkMWO__g(){return __M2QzMjdkMWO_;};
extern const uint32_t __MzI3ZDFjYmY6=0x32;
extern "C" uint32_t  __stdcall __MzI3ZDFjYmY6_g(){return __MzI3ZDFjYmY6;};
extern const uint32_t __N2QxY2JmM2Hq=0x7D;
extern "C" uint32_t  __stdcall __N2QxY2JmM2Hq_g(){return __N2QxY2JmM2Hq;};
extern const uint32_t __MWNiZjNhZWEA=0x1C;
extern "C" uint32_t  __stdcall __MWNiZjNhZWEA_g(){return __MWNiZjNhZWEA;};
extern const uint32_t __YmYzYWVhMDBh=0xBF;
extern "C" uint32_t  __stdcall __YmYzYWVhMDBh_g(){return __YmYzYWVhMDBh;};
extern const uint32_t __M2FlYTAwNjFD=0x3A;
extern "C" uint32_t  __stdcall __M2FlYTAwNjFD_g(){return __M2FlYTAwNjFD;};
extern const uint32_t __ZWEwMDYxNDNY=0xEA;
extern "C" uint32_t  __stdcall __ZWEwMDYxNDNY_g(){return __ZWEwMDYxNDNY;};
extern const uint32_t __MDA2MTQzNTin=0x00;
extern "C" uint32_t  __stdcall __MDA2MTQzNTin_g(){return __MDA2MTQzNTin;};
extern const uint32_t __NjE0MzU4YTdR=0x61;
extern "C" uint32_t  __stdcall __NjE0MzU4YTdR_g(){return __NjE0MzU4YTdR;};
extern const uint32_t __NDM1OGE3NTHf=0x43;
extern "C" uint32_t  __stdcall __NDM1OGE3NTHf_g(){return __NDM1OGE3NTHf;};
extern const uint32_t __NThhNzUxZGZ0=0x58;
extern "C" uint32_t  __stdcall __NThhNzUxZGZ0_g(){return __NThhNzUxZGZ0;};
extern const uint32_t __YTc1MWRmNzTb=0xA7;
extern "C" uint32_t  __stdcall __YTc1MWRmNzTb_g(){return __YTc1MWRmNzTb;};
extern const uint32_t __NTFkZjc0ZGKI=0x51;
extern "C" uint32_t  __stdcall __NTFkZjc0ZGKI_g(){return __NTFkZjc0ZGKI;};
extern const uint32_t __ZGY3NGRiODgn=0xDF;
extern "C" uint32_t  __stdcall __ZGY3NGRiODgn_g(){return __ZGY3NGRiODgn;};
extern const uint32_t __NzRkYjg4Mjfs=0x74;
extern "C" uint32_t  __stdcall __NzRkYjg4Mjfs_g(){return __NzRkYjg4Mjfs;};
extern const uint32_t __ZGI4ODI3ZWP1=0xDB;
extern "C" uint32_t  __stdcall __ZGI4ODI3ZWP1_g(){return __ZGI4ODI3ZWP1;};
extern const uint32_t __ODgyN2VjZjXR=0x88;
extern "C" uint32_t  __stdcall __ODgyN2VjZjXR_g(){return __ODgyN2VjZjXR;};
extern const uint32_t __MjdlY2Y1ZDGj=0x27;
extern "C" uint32_t  __stdcall __MjdlY2Y1ZDGj_g(){return __MjdlY2Y1ZDGj;};
extern const uint32_t __ZWNmNWQxYTPi=0xEC;
extern "C" uint32_t  __stdcall __ZWNmNWQxYTPi_g(){return __ZWNmNWQxYTPi;};
extern const uint32_t __ZjVkMWEzZTIJ=0xF5;
extern "C" uint32_t  __stdcall __ZjVkMWEzZTIJ_g(){return __ZjVkMWEzZTIJ;};
extern const uint32_t __ZDFhM2UyMDke=0xD1;
extern "C" uint32_t  __stdcall __ZDFhM2UyMDke_g(){return __ZDFhM2UyMDke;};
extern const uint32_t __YTNlMjA5MWXG=0xA3;
extern "C" uint32_t  __stdcall __YTNlMjA5MWXG_g(){return __YTNlMjA5MWXG;};
extern const uint32_t __ZTIwOTFlYzY4=0xE2;
extern "C" uint32_t  __stdcall __ZTIwOTFlYzY4_g(){return __ZTIwOTFlYzY4;};
extern const uint32_t __MDkxZWM2Mzhu=0x09;
extern "C" uint32_t  __stdcall __MDkxZWM2Mzhu_g(){return __MDkxZWM2Mzhu;};
extern const uint32_t __MWVjNjM4NmVw=0x1E;
extern "C" uint32_t  __stdcall __MWVjNjM4NmVw_g(){return __MWVjNjM4NmVw;};
extern const uint32_t __YzYzODZlNzBP=0xC6;
extern "C" uint32_t  __stdcall __YzYzODZlNzBP_g(){return __YzYzODZlNzBP;};
extern const uint32_t __Mzg2ZTcwNGbP=0x38;
extern "C" uint32_t  __stdcall __Mzg2ZTcwNGbP_g(){return __Mzg2ZTcwNGbP;};
extern const uint32_t __NmU3MDRmY2YF=0x6E;
extern "C" uint32_t  __stdcall __NmU3MDRmY2YF_g(){return __NmU3MDRmY2YF;};
extern const uint32_t __NzA0ZmNmMDWC=0x70;
extern "C" uint32_t  __stdcall __NzA0ZmNmMDWC_g(){return __NzA0ZmNmMDWC;};
extern const uint32_t __NGZjZjA1ODLy=0x4F;
extern "C" uint32_t  __stdcall __NGZjZjA1ODLy_g(){return __NGZjZjA1ODLy;};
extern const uint32_t __Y2YwNTgyZjLn=0xCF;
extern "C" uint32_t  __stdcall __Y2YwNTgyZjLn_g(){return __Y2YwNTgyZjLn;};
extern const uint32_t __MDU4MmYyZTdS=0x05;
extern "C" uint32_t  __stdcall __MDU4MmYyZTdS_g(){return __MDU4MmYyZTdS;};
extern const uint32_t __ODJmMmU3NTLQ=0x82;
extern "C" uint32_t  __stdcall __ODJmMmU3NTLQ_g(){return __ODJmMmU3NTLQ;};
extern const uint32_t __ZjJlNzUyZDBn=0xF2;
extern "C" uint32_t  __stdcall __ZjJlNzUyZDBn_g(){return __ZjJlNzUyZDBn;};
extern const uint32_t __ZTc1MmQwNjf_=0xE7;
extern "C" uint32_t  __stdcall __ZTc1MmQwNjf__g(){return __ZTc1MmQwNjf_;};
extern const uint32_t __NTJkMDY3ZmaP=0x52;
extern "C" uint32_t  __stdcall __NTJkMDY3ZmaP_g(){return __NTJkMDY3ZmaP;};
extern const uint32_t __ZDA2N2ZmOGYh=0xD0;
extern "C" uint32_t  __stdcall __ZDA2N2ZmOGYh_g(){return __ZDA2N2ZmOGYh;};
extern const uint32_t __NjdmZjhmMjEd=0x67;
extern "C" uint32_t  __stdcall __NjdmZjhmMjEd_g(){return __NjdmZjhmMjEd;};
extern const uint32_t __ZmY4ZjIxMWRy=0xFF;
extern "C" uint32_t  __stdcall __ZmY4ZjIxMWRy_g(){return __ZmY4ZjIxMWRy;};
extern const uint32_t __OGYyMTFkNzLw=0x8F;
extern "C" uint32_t  __stdcall __OGYyMTFkNzLw_g(){return __OGYyMTFkNzLw;};
extern const uint32_t __MjExZDcyZjAm=0x21;
extern "C" uint32_t  __stdcall __MjExZDcyZjAm_g(){return __MjExZDcyZjAm;};
extern const uint32_t __MWQ3MmYwMjaM=0x1D;
extern "C" uint32_t  __stdcall __MWQ3MmYwMjaM_g(){return __MWQ3MmYwMjaM;};
extern const uint32_t __NzJmMDI2OGMO=0x72;
extern "C" uint32_t  __stdcall __NzJmMDI2OGMO_g(){return __NzJmMDI2OGMO;};
extern const uint32_t __ZjAyNjhjMGX_=0xF0;
extern "C" uint32_t  __stdcall __ZjAyNjhjMGX__g(){return __ZjAyNjhjMGX_;};
extern const uint32_t __MjY4YzBlZmXl=0x26;
extern "C" uint32_t  __stdcall __MjY4YzBlZmXl_g(){return __MjY4YzBlZmXl;};
extern const uint32_t __OGMwZWZlZTWt=0x8C;
extern "C" uint32_t  __stdcall __OGMwZWZlZTWt_g(){return __OGMwZWZlZTWt;};
extern const uint32_t __MGVmZWU1YWSg=0x0E;
extern "C" uint32_t  __stdcall __MGVmZWU1YWSg_g(){return __MGVmZWU1YWSg;};
extern const uint32_t __ZmVlNWFkYTD7=0xFE;
extern "C" uint32_t  __stdcall __ZmVlNWFkYTD7_g(){return __ZmVlNWFkYTD7;};
extern const uint32_t __ZTVhZGEwZmKL=0xE5;
extern "C" uint32_t  __stdcall __ZTVhZGEwZmKL_g(){return __ZTVhZGEwZmKL;};
extern const uint32_t __YWRhMGZiOGIo=0xAD;
extern "C" uint32_t  __stdcall __YWRhMGZiOGIo_g(){return __YWRhMGZiOGIo;};
extern const uint32_t __YTBmYjhiMjjW=0xA0;
extern "C" uint32_t  __stdcall __YTBmYjhiMjjW_g(){return __YTBmYjhiMjjW;};
extern const uint32_t __ZmI4YjI4ZDbx=0xFB;
extern "C" uint32_t  __stdcall __ZmI4YjI4ZDbx_g(){return __ZmI4YjI4ZDbx;};
extern const uint32_t __OGIyOGQ2ZjE_=0x8B;
extern "C" uint32_t  __stdcall __OGIyOGQ2ZjE__g(){return __OGIyOGQ2ZjE_;};
extern const uint32_t __MjhkNmYxM2Us=0x28;
extern "C" uint32_t  __stdcall __MjhkNmYxM2Us_g(){return __MjhkNmYxM2Us;};
extern const uint32_t __ZDZmMTNlMmOm=0xD6;
extern "C" uint32_t  __stdcall __ZDZmMTNlMmOm_g(){return __ZDZmMTNlMmOm;};
extern const uint32_t __ZjEzZTJjYTai=0xF1;
extern "C" uint32_t  __stdcall __ZjEzZTJjYTai_g(){return __ZjEzZTJjYTai;};
extern const uint32_t __M2UyY2E2YTKp=0x3E;
extern "C" uint32_t  __stdcall __M2UyY2E2YTKp_g(){return __M2UyY2E2YTKp;};
extern const uint32_t __MmNhNmEyYTmy=0x2C;
extern "C" uint32_t  __stdcall __MmNhNmEyYTmy_g(){return __MmNhNmEyYTmy;};
extern const uint32_t __YTZhMmE5YjKc=0xA6;
extern "C" uint32_t  __stdcall __YTZhMmE5YjKc_g(){return __YTZhMmE5YjKc;};
extern const uint32_t __YTJhOWIyOWO6=0xA2;
extern "C" uint32_t  __stdcall __YTJhOWIyOWO6_g(){return __YTJhOWIyOWO6;};
extern const uint32_t __YTliMjljYmHC=0xA9;
extern "C" uint32_t  __stdcall __YTliMjljYmHC_g(){return __YTliMjljYmHC;};
extern const uint32_t __YjI5Y2JhYzLH=0xB2;
extern "C" uint32_t  __stdcall __YjI5Y2JhYzLH_g(){return __YjI5Y2JhYzLH;};
extern const uint32_t __OWNiYWMyYzcH=0x9C;
extern "C" uint32_t  __stdcall __OWNiYWMyYzcH_g(){return __OWNiYWMyYzcH;};
extern const uint32_t __YmFjMmM3MDf5=0xBA;
extern "C" uint32_t  __stdcall __YmFjMmM3MDf5_g(){return __YmFjMmM3MDf5;};
extern const uint32_t __YzJjNzA3Zjlz=0xC2;
extern "C" uint32_t  __stdcall __YzJjNzA3Zjlz_g(){return __YzJjNzA3Zjlz;};
extern const uint32_t __YzcwN2Y5NzNA=0xC7;
extern "C" uint32_t  __stdcall __YzcwN2Y5NzNA_g(){return __YzcwN2Y5NzNA;};
extern const uint32_t __MDdmOTczNDA5=0x07;
extern "C" uint32_t  __stdcall __MDdmOTczNDA5_g(){return __MDdmOTczNDA5;};
extern const uint32_t __Zjk3MzQwMzka=0xF9;
extern "C" uint32_t  __stdcall __Zjk3MzQwMzka_g(){return __Zjk3MzQwMzka;};
extern const uint32_t __NzM0MDM5MWE7=0x73;
extern "C" uint32_t  __stdcall __NzM0MDM5MWE7_g(){return __NzM0MDM5MWE7;};
extern const uint32_t __NDAzOTFhM2JZ=0x40;
extern "C" uint32_t  __stdcall __NDAzOTFhM2JZ_g(){return __NDAzOTFhM2JZ;};
extern const uint32_t __MzkxYTNiNTkE=0x39;
extern "C" uint32_t  __stdcall __MzkxYTNiNTkE_g(){return __MzkxYTNiNTkE;};
extern const uint32_t __MWEzYjU5MDSk=0x1A;
extern "C" uint32_t  __stdcall __MWEzYjU5MDSk_g(){return __MWEzYjU5MDSk;};
extern const uint32_t __M2I1OTA0YTS_=0x3B;
extern "C" uint32_t  __stdcall __M2I1OTA0YTS__g(){return __M2I1OTA0YTS_;};
extern const uint32_t __NTkwNGE0YmXN=0x59;
extern "C" uint32_t  __stdcall __NTkwNGE0YmXN_g(){return __NTkwNGE0YmXN;};
extern const uint32_t __MDRhNGJlY2QG=0x04;
extern "C" uint32_t  __stdcall __MDRhNGJlY2QG_g(){return __MDRhNGJlY2QG;};
extern const uint32_t __YTRiZWNkMDbB=0xA4;
extern "C" uint32_t  __stdcall __YTRiZWNkMDbB_g(){return __YTRiZWNkMDbB;};
extern const uint32_t __YmVjZDA2YzHd=0xBE;
extern "C" uint32_t  __stdcall __YmVjZDA2YzHd_g(){return __YmVjZDA2YzHd;};
extern const uint32_t __Y2QwNmMxZGQr=0xCD;
extern "C" uint32_t  __stdcall __Y2QwNmMxZGQr_g(){return __Y2QwNmMxZGQr;};
extern const uint32_t __MDZjMWRkMmK7=0x06;
extern "C" uint32_t  __stdcall __MDZjMWRkMmK7_g(){return __MDZjMWRkMmK7;};
extern const uint32_t __YzFkZDJiYmK3=0xC1;
extern "C" uint32_t  __stdcall __YzFkZDJiYmK3_g(){return __YzFkZDJiYmK3;};
extern const uint32_t __ZGQyYmJiYjdj=0xDD;
extern "C" uint32_t  __stdcall __ZGQyYmJiYjdj_g(){return __ZGQyYmJiYjdj;};
extern const uint32_t __MmJiYmI3NjN3=0x2B;
extern "C" uint32_t  __stdcall __MmJiYmI3NjN3_g(){return __MmJiYmI3NjN3;};
extern const uint32_t __YmJiNzYzNzdH=0xBB;
extern "C" uint32_t  __stdcall __YmJiNzYzNzdH_g(){return __YmJiNzYzNzdH;};
extern const uint32_t __Yjc2Mzc3NDe2=0xB7;
extern "C" uint32_t  __stdcall __Yjc2Mzc3NDe2_g(){return __Yjc2Mzc3NDe2;};
extern const uint32_t __NjM3NzQ3Yjba=0x63;
extern "C" uint32_t  __stdcall __NjM3NzQ3Yjba_g(){return __NjM3NzQ3Yjba;};
extern const uint32_t __Nzc0N2I2ZGFk=0x77;
extern "C" uint32_t  __stdcall __Nzc0N2I2ZGFk_g(){return __Nzc0N2I2ZGFk;};
extern const uint32_t __NDdiNmRhNjTp=0x47;
extern "C" uint32_t  __stdcall __NDdiNmRhNjTp_g(){return __NDdiNmRhNjTp;};
extern const uint32_t __YjZkYTY0ZTmd=0xB6;
extern "C" uint32_t  __stdcall __YjZkYTY0ZTmd_g(){return __YjZkYTY0ZTmd;};
extern const uint32_t __ZGE2NGU5OWRt=0xDA;
extern "C" uint32_t  __stdcall __ZGE2NGU5OWRt_g(){return __ZGE2NGU5OWRt;};
extern const uint32_t __NjRlOTlkNmQL=0x64;
extern "C" uint32_t  __stdcall __NjRlOTlkNmQL_g(){return __NjRlOTlkNmQL;};
extern const uint32_t __ZTk5ZDZkMGIS=0xE9;
extern "C" uint32_t  __stdcall __ZTk5ZDZkMGIS_g(){return __ZTk5ZDZkMGIS;};
extern const uint32_t __OWQ2ZDBiMTIu=0x9D;
extern "C" uint32_t  __stdcall __OWQ2ZDBiMTIu_g(){return __OWQ2ZDBiMTIu;};
extern const uint32_t __NmQwYjEyMmXX=0x6D;
extern "C" uint32_t  __stdcall __NmQwYjEyMmXX_g(){return __NmQwYjEyMmXX;};
extern const uint32_t __MGIxMjJlZDeE=0x0B;
extern "C" uint32_t  __stdcall __MGIxMjJlZDeE_g(){return __MGIxMjJlZDeE;};
extern const uint32_t __MTIyZWQ3ODSv=0x12;
extern "C" uint32_t  __stdcall __MTIyZWQ3ODSv_g(){return __MTIyZWQ3ODSv;};
extern const uint32_t __MmVkNzg0YWbI=0x2E;
extern "C" uint32_t  __stdcall __MmVkNzg0YWbI_g(){return __MmVkNzg0YWbI;};
extern const uint32_t __ZDc4NGFmYziK=0xD7;
extern "C" uint32_t  __stdcall __ZDc4NGFmYziK_g(){return __ZDc4NGFmYziK;};
extern const uint32_t __ODRhZmM4OGF7=0x84;
extern "C" uint32_t  __stdcall __ODRhZmM4OGF7_g(){return __ODRhZmM4OGF7;};
extern const uint32_t __YWZjODhhN2KG=0xAF;
extern "C" uint32_t  __stdcall __YWZjODhhN2KG_g(){return __YWZjODhhN2KG;};
extern const uint32_t __Yzg4YTdiODZJ=0xC8;
extern "C" uint32_t  __stdcall __Yzg4YTdiODZJ_g(){return __Yzg4YTdiODZJ;};
extern const uint32_t __OGE3Yjg2NDnY=0x8A;
extern "C" uint32_t  __stdcall __OGE3Yjg2NDnY_g(){return __OGE3Yjg2NDnY;};
extern const uint32_t __N2I4NjQ5ZDhx=0x7B;
extern "C" uint32_t  __stdcall __N2I4NjQ5ZDhx_g(){return __N2I4NjQ5ZDhx;};
extern const uint32_t __ODY0OWQ4NzFc=0x86;
extern "C" uint32_t  __stdcall __ODY0OWQ4NzFc_g(){return __ODY0OWQ4NzFc;};
extern const uint32_t __NDlkODcxNWPh=0x49;
extern "C" uint32_t  __stdcall __NDlkODcxNWPh_g(){return __NDlkODcxNWPh;};
extern const uint32_t __ZDg3MTVjZTFI=0xD8;
extern "C" uint32_t  __stdcall __ZDg3MTVjZTFI_g(){return __ZDg3MTVjZTFI;};
extern const uint32_t __NzE1Y2UxNDjk=0x71;
extern "C" uint32_t  __stdcall __NzE1Y2UxNDjk_g(){return __NzE1Y2UxNDjk;};
extern const uint32_t __NWNlMTQ4ZTRs=0x5C;
extern "C" uint32_t  __stdcall __NWNlMTQ4ZTRs_g(){return __NWNlMTQ4ZTRs;};
extern const uint32_t __ZTE0OGU0NmO9=0xE1;
extern "C" uint32_t  __stdcall __ZTE0OGU0NmO9_g(){return __ZTE0OGU0NmO9;};
extern const uint32_t __NDhlNDZjYmQb=0x48;
extern "C" uint32_t  __stdcall __NDhlNDZjYmQb_g(){return __NDhlNDZjYmQb;};
extern const uint32_t __ZTQ2Y2JkMWIt=0xE4;
extern "C" uint32_t  __stdcall __ZTQ2Y2JkMWIt_g(){return __ZTQ2Y2JkMWIt;};
extern const uint32_t __NmNiZDFiMmTK=0x6C;
extern "C" uint32_t  __stdcall __NmNiZDFiMmTK_g(){return __NmNiZDFiMmTK;};
extern const uint32_t __YmQxYjJkY2Gr=0xBD;
extern "C" uint32_t  __stdcall __YmQxYjJkY2Gr_g(){return __YmQxYjJkY2Gr;};
extern const uint32_t __MWIyZGNhYWLe=0x1B;
extern "C" uint32_t  __stdcall __MWIyZGNhYWLe_g(){return __MWIyZGNhYWLe;};
extern const uint32_t __MmRjYWFiZGVK=0x2D;
extern "C" uint32_t  __stdcall __MmRjYWFiZGVK_g(){return __MmRjYWFiZGVK;};
extern const uint32_t __Y2FhYmRlNGHc=0xCA;
extern "C" uint32_t  __stdcall __Y2FhYmRlNGHc_g(){return __Y2FhYmRlNGHc;};
extern const uint32_t __YWJkZTRhZGP0=0xAB;
extern "C" uint32_t  __stdcall __YWJkZTRhZGP0_g(){return __YWJkZTRhZGP0;};
extern const uint32_t __ZGU0YWRjZjRC=0xDE;
extern "C" uint32_t  __stdcall __ZGU0YWRjZjRC_g(){return __ZGU0YWRjZjRC;};
extern const uint32_t __NGFkY2Y0NDK0=0x4A;
extern "C" uint32_t  __stdcall __NGFkY2Y0NDK0_g(){return __NGFkY2Y0NDK0;};
extern const uint32_t __ZGNmNDQyYjSZ=0xDC;
extern "C" uint32_t  __stdcall __ZGNmNDQyYjSZ_g(){return __ZGNmNDQyYjSZ;};
extern const uint32_t __ZjQ0MmI0OTmx=0xF4;
extern "C" uint32_t  __stdcall __ZjQ0MmI0OTmx_g(){return __ZjQ0MmI0OTmx;};
extern const uint32_t __NDJiNDk5YjGB=0x42;
extern "C" uint32_t  __stdcall __NDJiNDk5YjGB_g(){return __NDJiNDk5YjGB;};
extern const uint32_t __YjQ5OWIxODFv=0xB4;
extern "C" uint32_t  __stdcall __YjQ5OWIxODFv_g(){return __YjQ5OWIxODFv;};
extern const uint32_t __OTliMTgxNmZN=0x99;
extern "C" uint32_t  __stdcall __OTliMTgxNmZN_g(){return __OTliMTgxNmZN;};
extern const uint32_t __YjE4MTZmNGTE=0xB1;
extern "C" uint32_t  __stdcall __YjE4MTZmNGTE_g(){return __YjE4MTZmNGTE;};
extern const uint32_t __ODE2ZjRkYzQj=0x81;
extern "C" uint32_t  __stdcall __ODE2ZjRkYzQj_g(){return __ODE2ZjRkYzQj;};
extern const uint32_t __NmY0ZGM0MjNF=0x6F;
extern "C" uint32_t  __stdcall __NmY0ZGM0MjNF_g(){return __NmY0ZGM0MjNF;};
extern const uint32_t __NGRjNDIzNDWO=0x4D;
extern "C" uint32_t  __stdcall __NGRjNDIzNDWO_g(){return __NGRjNDIzNDWO;};
extern const uint32_t __YzQyMzQ1OGV_=0xC4;
extern "C" uint32_t  __stdcall __YzQyMzQ1OGV__g(){return __YzQyMzQ1OGV_;};
extern const uint32_t __MjM0NThlN2YX=0x23;
extern "C" uint32_t  __stdcall __MjM0NThlN2YX_g(){return __MjM0NThlN2YX;};
extern const uint32_t __NDU4ZTdmMTcQ=0x45;
extern "C" uint32_t  __stdcall __NDU4ZTdmMTcQ_g(){return __NDU4ZTdmMTcQ;};
extern const uint32_t __OGU3ZjE3MTAk=0x8E;
extern "C" uint32_t  __stdcall __OGU3ZjE3MTAk_g(){return __OGU3ZjE3MTAk;};
extern const uint32_t __N2YxNzEwMjRm=0x7F;
extern "C" uint32_t  __stdcall __N2YxNzEwMjRm_g(){return __N2YxNzEwMjRm;};
extern const uint32_t __MTcxMDI0Nja4=0x17;
extern "C" uint32_t  __stdcall __MTcxMDI0Nja4_g(){return __MTcxMDI0Nja4;};
extern const uint32_t __MTAyNDY2Yjju=0x10;
extern "C" uint32_t  __stdcall __MTAyNDY2Yjju_g(){return __MTAyNDY2Yjju;};
extern const uint32_t __MjQ2NmI4ZWXD=0x24;
extern "C" uint32_t  __stdcall __MjQ2NmI4ZWXD_g(){return __MjQ2NmI4ZWXD;};
extern const uint32_t __NjZiOGVlYzP6=0x66;
extern "C" uint32_t  __stdcall __NjZiOGVlYzP6_g(){return __NjZiOGVlYzP6;};
extern const uint32_t __YjhlZWMzZmHv=0xB8;
extern "C" uint32_t  __stdcall __YjhlZWMzZmHv_g(){return __YjhlZWMzZmHv;};
extern const uint32_t __ZWVjM2ZhZWb2=0xEE;
extern "C" uint32_t  __stdcall __ZWVjM2ZhZWb2_g(){return __ZWVjM2ZhZWb2;};
extern const uint32_t __YzNmYWVmZjYz=0xC3;
extern "C" uint32_t  __stdcall __YzNmYWVmZjYz_g(){return __YzNmYWVmZjYz;};
extern const uint32_t __ZmFlZmY2MzMx=0xFA;
extern "C" uint32_t  __stdcall __ZmFlZmY2MzMx_g(){return __ZmFlZmY2MzMx;};
extern const uint32_t __ZWZmNjMzMzHF=0xEF;
extern "C" uint32_t  __stdcall __ZWZmNjMzMzHF_g(){return __ZWZmNjMzMzHF;};
extern const uint32_t __ZjYzMzMxYzWW=0xF6;
extern "C" uint32_t  __stdcall __ZjYzMzMxYzWW_g(){return __ZjYzMzMxYzWW;};
extern const uint32_t __MzMzMWM1OTZb=0x33;
extern "C" uint32_t  __stdcall __MzMzMWM1OTZb_g(){return __MzMzMWM1OTZb;};
extern const uint32_t __MzFjNTk2NWI_=0x31;
extern "C" uint32_t  __stdcall __MzFjNTk2NWI__g(){return __MzFjNTk2NWI_;};
extern const uint32_t __YzU5NjViM2aQ=0xC5;
extern "C" uint32_t  __stdcall __YzU5NjViM2aQ_g(){return __YzU5NjViM2aQ;};
extern const uint32_t __OTY1YjNmOTBr=0x96;
extern "C" uint32_t  __stdcall __OTY1YjNmOTBr_g(){return __OTY1YjNmOTBr;};
extern const uint32_t __NWIzZjkwNmJd=0x5B;
extern "C" uint32_t  __stdcall __NWIzZjkwNmJd_g(){return __NWIzZjkwNmJd;};
extern const uint32_t __M2Y5MDZiNWT9=0x3F;
extern "C" uint32_t  __stdcall __M2Y5MDZiNWT9_g(){return __M2Y5MDZiNWT9;};
extern const uint32_t __OTA2YjVkZmQg=0x90;
extern "C" uint32_t  __stdcall __OTA2YjVkZmQg_g(){return __OTA2YjVkZmQg;};
extern const uint32_t __NmI1ZGZkMjAT=0x6B;
extern "C" uint32_t  __stdcall __NmI1ZGZkMjAT_g(){return __NmI1ZGZkMjAT;};
extern const uint32_t __NWRmZDIwMTOU=0x5D;
extern "C" uint32_t  __stdcall __NWRmZDIwMTOU_g(){return __NWRmZDIwMTOU;};
extern const uint32_t __ZmQyMDEzOTSX=0xFD;
extern "C" uint32_t  __stdcall __ZmQyMDEzOTSX_g(){return __ZmQyMDEzOTSX;};
extern const uint32_t __MjAxMzk0OTeF=0x20;
extern "C" uint32_t  __stdcall __MjAxMzk0OTeF_g(){return __MjAxMzk0OTeF;};
extern const uint32_t __MTM5NDk3ODWN=0x13;
extern "C" uint32_t  __stdcall __MTM5NDk3ODWN_g(){return __MTM5NDk3ODWN;};
extern const uint32_t __OTQ5Nzg1OGQZ=0x94;
extern "C" uint32_t  __stdcall __OTQ5Nzg1OGQZ_g(){return __OTQ5Nzg1OGQZ;};
extern const uint32_t __OTc4NThkMTkM=0x97;
extern "C" uint32_t  __stdcall __OTc4NThkMTkM_g(){return __OTc4NThkMTkM;};
extern const uint32_t __ODU4ZDE5MGOS=0x85;
extern "C" uint32_t  __stdcall __ODU4ZDE5MGOS_g(){return __ODU4ZDE5MGOS;};
extern const uint32_t __OGQxOTBjOTIC=0x8D;
extern "C" uint32_t  __stdcall __OGQxOTBjOTIC_g(){return __OGQxOTBjOTIC;};
extern const uint32_t __MTkwYzkyMDJ4=0x19;
extern "C" uint32_t  __stdcall __MTkwYzkyMDJ4_g(){return __MTkwYzkyMDJ4;};
extern const uint32_t __MGM5MjAyNzjJ=0x0C;
extern "C" uint32_t  __stdcall __MGM5MjAyNzjJ_g(){return __MGM5MjAyNzjJ;};
extern const uint32_t __OTIwMjc4Yzki=0x92;
extern "C" uint32_t  __stdcall __OTIwMjc4Yzki_g(){return __OTIwMjc4Yzki;};
extern const uint32_t __MDI3OGM5MjK1=0x02;
extern "C" uint32_t  __stdcall __MDI3OGM5MjK1_g(){return __MDI3OGM5MjK1;};
extern const uint32_t __NzhjOTIyYjWJ=0x78;
extern "C" uint32_t  __stdcall __NzhjOTIyYjWJ_g(){return __NzhjOTIyYjWJ;};
extern const uint32_t __YzkyMmI1ODlf=0xC9;
extern "C" uint32_t  __stdcall __YzkyMmI1ODlf_g(){return __YzkyMmI1ODlf;};
extern const uint32_t __MjJiNTg5NWZX=0x22;
extern "C" uint32_t  __stdcall __MjJiNTg5NWZX_g(){return __MjJiNTg5NWZX;};
extern const uint32_t __YjU4OTVmNTda=0xB5;
extern "C" uint32_t  __stdcall __YjU4OTVmNTda_g(){return __YjU4OTVmNTda;};
extern const uint32_t __ODk1ZjU3NWGR=0x89;
extern "C" uint32_t  __stdcall __ODk1ZjU3NWGR_g(){return __ODk1ZjU3NWGR;};
extern const uint32_t __NWY1NzVhOTEP=0x5F;
extern "C" uint32_t  __stdcall __NWY1NzVhOTEP_g(){return __NWY1NzVhOTEP;};
extern const uint32_t __NTc1YTkxMGbT=0x57;
extern "C" uint32_t  __stdcall __NTc1YTkxMGbT_g(){return __NTc1YTkxMGbT;};
extern const uint32_t __NWE5MTBmZDPO=0x5A;
extern "C" uint32_t  __stdcall __NWE5MTBmZDPO_g(){return __NWE5MTBmZDPO;};
extern const uint32_t __OTEwZmQzY2U3=0x91;
extern "C" uint32_t  __stdcall __OTEwZmQzY2U3_g(){return __OTEwZmQzY2U3;};
extern const uint32_t __MGZkM2NlMzd5=0x0F;
extern "C" uint32_t  __stdcall __MGZkM2NlMzd5_g(){return __MGZkM2NlMzd5;};
extern const uint32_t __ZDNjZTM3Nzm8=0xD3;
extern "C" uint32_t  __stdcall __ZDNjZTM3Nzm8_g(){return __ZDNjZTM3Nzm8;};
extern const uint32_t __Y2UzNzc5YmOu=0xCE;
extern "C" uint32_t  __stdcall __Y2UzNzc5YmOu_g(){return __Y2UzNzc5YmOu;};
extern const uint32_t __Mzc3OWJjYWXL=0x37;
extern "C" uint32_t  __stdcall __Mzc3OWJjYWXL_g(){return __Mzc3OWJjYWXL;};
extern const uint32_t __NzliY2FlY2JT=0x79;
extern "C" uint32_t  __stdcall __NzliY2FlY2JT_g(){return __NzliY2FlY2JT;};
extern const uint32_t __YmNhZWNiNTMv=0xBC;
extern "C" uint32_t  __stdcall __YmNhZWNiNTMv_g(){return __YmNhZWNiNTMv;};
extern const uint32_t __YWVjYjUzMmZp=0xAE;
extern "C" uint32_t  __stdcall __YWVjYjUzMmZp_g(){return __YWVjYjUzMmZp;};
extern const uint32_t __Y2I1MzJmNjk8=0xCB;
extern "C" uint32_t  __stdcall __Y2I1MzJmNjk8_g(){return __Y2I1MzJmNjk8;};
extern const uint32_t __NTMyZjY5M2MV=0x53;
extern "C" uint32_t  __stdcall __NTMyZjY5M2MV_g(){return __NTMyZjY5M2MV;};
extern const uint32_t __MmY2OTNjMTVM=0x2F;
extern "C" uint32_t  __stdcall __MmY2OTNjMTVM_g(){return __MmY2OTNjMTVM;};
extern const uint32_t __NjkzYzE1NGMf=0x69;
extern "C" uint32_t  __stdcall __NjkzYzE1NGMf_g(){return __NjkzYzE1NGMf;};
extern const uint32_t __M2MxNTRjMWZB=0x3C;
extern "C" uint32_t  __stdcall __M2MxNTRjMWZB_g(){return __M2MxNTRjMWZB;};
extern const uint32_t __MTU0YzFmNDGz=0x15;
extern "C" uint32_t  __stdcall __MTU0YzFmNDGz_g(){return __MTU0YzFmNDGz;};
extern const uint32_t __NGMxZjQxYjMN=0x4C;
extern "C" uint32_t  __stdcall __NGMxZjQxYjMN_g(){return __NGMxZjQxYjMN;};
extern const uint32_t __MWY0MWIzMGT8=0x1F;
extern "C" uint32_t  __stdcall __MWY0MWIzMGT8_g(){return __MWY0MWIzMGT8;};
extern const uint32_t __NDFiMzBkZmPr=0x41;
extern "C" uint32_t  __stdcall __NDFiMzBkZmPr_g(){return __NDFiMzBkZmPr;};
extern const uint32_t __YjMwZGZjZWLS=0xB3;
extern "C" uint32_t  __stdcall __YjMwZGZjZWLS_g(){return __YjMwZGZjZWLS;};
extern const uint32_t __MGRmY2ViZDKf=0x0D;
extern "C" uint32_t  __stdcall __MGRmY2ViZDKf_g(){return __MGRmY2ViZDKf;};
extern const uint32_t __ZmNlYmQyOWYK=0xFC;
extern "C" uint32_t  __stdcall __ZmNlYmQyOWYK_g(){return __ZmNlYmQyOWYK;};
extern const uint32_t __ZWJkMjlmMGF1=0xEB;
extern "C" uint32_t  __stdcall __ZWJkMjlmMGF1_g(){return __ZWJkMjlmMGF1;};
extern const uint32_t __ZDI5ZjBhNzWT=0xD2;
extern "C" uint32_t  __stdcall __ZDI5ZjBhNzWT_g(){return __ZDI5ZjBhNzWT;};
extern const uint32_t __OWYwYTc1OTNi=0x9F;
extern "C" uint32_t  __stdcall __OWYwYTc1OTNi_g(){return __OWYwYTc1OTNi;};
extern const uint32_t __MGE3NTkzNjJ_=0x0A;
extern "C" uint32_t  __stdcall __MGE3NTkzNjJ__g(){return __MGE3NTkzNjJ_;};
extern const uint32_t __NzU5MzYyN2Ws=0x75;
extern "C" uint32_t  __stdcall __NzU5MzYyN2Ws_g(){return __NzU5MzYyN2Ws;};
extern const uint32_t __OTM2MjdlYWNq=0x93;
extern "C" uint32_t  __stdcall __OTM2MjdlYWNq_g(){return __OTM2MjdlYWNq;};
extern const uint32_t __NjI3ZWFjNmGa=0x62;
extern "C" uint32_t  __stdcall __NjI3ZWFjNmGa_g(){return __NjI3ZWFjNmGa;};
extern const uint32_t __N2VhYzZhOWHM=0x7E;
extern "C" uint32_t  __stdcall __N2VhYzZhOWHM_g(){return __N2VhYzZhOWHM;};
extern const uint32_t __YWM2YTlhY2PU=0xAC;
extern "C" uint32_t  __stdcall __YWM2YTlhY2PU_g(){return __YWM2YTlhY2PU;};
extern const uint32_t __NmE5YWNjZDSq=0x6A;
extern "C" uint32_t  __stdcall __NmE5YWNjZDSq_g(){return __NmE5YWNjZDSq;};
extern const uint32_t __OWFjY2Q0YWG5=0x9A;
extern "C" uint32_t  __stdcall __OWFjY2Q0YWG5_g(){return __OWFjY2Q0YWG5;};
extern const uint32_t __Y2NkNGFhYjl2=0xCC;
extern "C" uint32_t  __stdcall __Y2NkNGFhYjl2_g(){return __Y2NkNGFhYjl2;};
extern const uint32_t __ZDRhYWI5Nzaw=0xD4;
extern "C" uint32_t  __stdcall __ZDRhYWI5Nzaw_g(){return __ZDRhYWI5Nzaw;};
extern const uint32_t __YWFiOTc2YjA1=0xAA;
extern "C" uint32_t  __stdcall __YWFiOTc2YjA1_g(){return __YWFiOTc2YjA1;};
extern const uint32_t __Yjk3NmIwMzVL=0xB9;
extern "C" uint32_t  __stdcall __Yjk3NmIwMzVL_g(){return __Yjk3NmIwMzVL;};
extern const uint32_t __NzZiMDM1NGJW=0x76;
extern "C" uint32_t  __stdcall __NzZiMDM1NGJW_g(){return __NzZiMDM1NGJW;};
extern const uint32_t __YjAzNTRiNTab=0xB0;
extern "C" uint32_t  __stdcall __YjAzNTRiNTab_g(){return __YjAzNTRiNTab;};
extern const uint32_t __MzU0YjU2OWJ6=0x35;
extern "C" uint32_t  __stdcall __MzU0YjU2OWJ6_g(){return __MzU0YjU2OWJ6;};
extern const uint32_t __NGI1NjliN2Ho=0x4B;
extern "C" uint32_t  __stdcall __NGI1NjliN2Ho_g(){return __NGI1NjliN2Ho;};
extern const uint32_t __NTY5YjdhZTiH=0x56;
extern "C" uint32_t  __stdcall __NTY5YjdhZTiH_g(){return __NTY5YjdhZTiH;};
extern const uint32_t __OWI3YWU4ODdg=0x9B;
extern "C" uint32_t  __stdcall __OWI3YWU4ODdg_g(){return __OWI3YWU4ODdg;};
extern const uint32_t __N2FlODg3NjAY=0x7A;
extern "C" uint32_t  __stdcall __N2FlODg3NjAY_g(){return __N2FlODg3NjAY;};
extern const uint32_t __ZTg4NzYwMTiV=0xE8;
extern "C" uint32_t  __stdcall __ZTg4NzYwMTiV_g(){return __ZTg4NzYwMTiV;};
extern const uint32_t __ODc2MDE4OTVO=0x87;
extern "C" uint32_t  __stdcall __ODc2MDE4OTVO_g(){return __ODc2MDE4OTVO;};
extern const uint32_t __NjAxODk1NGXA=0x60;
extern "C" uint32_t  __stdcall __NjAxODk1NGXA_g(){return __NjAxODk1NGXA;};
extern const uint32_t __MTg5NTRlYzD4=0x18;
extern "C" uint32_t  __stdcall __MTg5NTRlYzD4_g(){return __MTg5NTRlYzD4;};
extern const uint32_t __OTU0ZWMwZjgp=0x95;
extern "C" uint32_t  __stdcall __OTU0ZWMwZjgp_g(){return __OTU0ZWMwZjgp;};
extern const uint32_t __NGVjMGY4Mjk0=0x4E;
extern "C" uint32_t  __stdcall __NGVjMGY4Mjk0_g(){return __NGVjMGY4Mjk0;};
extern const uint32_t __YzBmODI5MzQl=0xC0;
extern "C" uint32_t  __stdcall __YzBmODI5MzQl_g(){return __YzBmODI5MzQl;};
extern const uint32_t __ZjgyOTM0MjUB=0xF8;
extern "C" uint32_t  __stdcall __ZjgyOTM0MjUB_g(){return __ZjgyOTM0MjUB;};
extern const uint32_t __MjkzNDI1MDGh=0x29;
extern "C" uint32_t  __stdcall __MjkzNDI1MDGh_g(){return __MjkzNDI1MDGh;};
extern const uint32_t __MzQyNTAxYTHV=0x34;
extern "C" uint32_t  __stdcall __MzQyNTAxYTHV_g(){return __MzQyNTAxYTHV;};
extern const uint32_t __MjUwMWExZDXZ=0x25;
extern "C" uint32_t  __stdcall __MjUwMWExZDXZ_g(){return __MjUwMWExZDXZ;};
extern const uint32_t __MDFhMWQ1ZDmo=0x01;
extern "C" uint32_t  __stdcall __MDFhMWQ1ZDmo_g(){return __MDFhMWQ1ZDmo;};
extern const uint32_t __YTFkNWQ5YThG=0xA1;
extern "C" uint32_t  __stdcall __YTFkNWQ5YThG_g(){return __YTFkNWQ5YThG;};
extern const uint32_t __ZDVkOWE4NDZQ=0xD5;
extern "C" uint32_t  __stdcall __ZDVkOWE4NDZQ_g(){return __ZDVkOWE4NDZQ;};
extern const uint32_t __ZDlhODQ2NTAI=0xD9;
extern "C" uint32_t  __stdcall __ZDlhODQ2NTAI_g(){return __ZDlhODQ2NTAI;};
extern const uint32_t __YTg0NjUwMDh8=0xA8;
extern "C" uint32_t  __stdcall __YTg0NjUwMDh8_g(){return __YTg0NjUwMDh8;};
extern const uint32_t __NDY1MDA4N2NE=0x46;
extern "C" uint32_t  __stdcall __NDY1MDA4N2NE_g(){return __NDY1MDA4N2NE;};
extern const uint32_t __NTAwODdjNDQ2=0x50;
extern "C" uint32_t  __stdcall __NTAwODdjNDQ2_g(){return __NTAwODdjNDQ2;};
extern const uint32_t __MDg3YzQ0MzZV=0x08;
extern "C" uint32_t  __stdcall __MDg3YzQ0MzZV_g(){return __MDg3YzQ0MzZV;};
extern const uint32_t __N2M0NDM2NTUq=0x7C;
extern "C" uint32_t  __stdcall __N2M0NDM2NTUq_g(){return __N2M0NDM2NTUq;};
extern const uint32_t __NDQzNjU1MmH3=0x44;
extern "C" uint32_t  __stdcall __NDQzNjU1MmH3_g(){return __NDQzNjU1MmH3;};
extern const uint32_t __MzY1NTJhZjcW=0x36;
extern "C" uint32_t  __stdcall __MzY1NTJhZjcW_g(){return __MzY1NTJhZjcW;};
extern const uint32_t __NTUyYWY3MTal=0x55;
extern "C" uint32_t  __stdcall __NTUyYWY3MTal_g(){return __NTUyYWY3MTal;};
extern const uint32_t __MmFmNzE2YTXg=0x2A;
extern "C" uint32_t  __stdcall __MmFmNzE2YTXg_g(){return __MmFmNzE2YTXg;};
extern const uint32_t __ZjcxNmE1ZTCA=0xF7;
extern "C" uint32_t  __stdcall __ZjcxNmE1ZTCA_g(){return __ZjcxNmE1ZTCA;};
extern const uint32_t __MTZhNWUwODDj=0x16;
extern "C" uint32_t  __stdcall __MTZhNWUwODDj_g(){return __MTZhNWUwODDj;};
extern const uint32_t __YTVlMDgwZTPt=0xA5;
extern "C" uint32_t  __stdcall __YTVlMDgwZTPt_g(){return __YTVlMDgwZTPt;};
extern const uint32_t __ZTA4MGUzZWSY=0xE0;
extern "C" uint32_t  __stdcall __ZTA4MGUzZWSY_g(){return __ZTA4MGUzZWSY;};
extern const uint32_t __ODBlM2VkOTjm=0x80;
extern "C" uint32_t  __stdcall __ODBlM2VkOTjm_g(){return __ODBlM2VkOTjm;};
extern const uint32_t __ZTNlZDk4ZTaD=0xE3;
extern "C" uint32_t  __stdcall __ZTNlZDk4ZTaD_g(){return __ZTNlZDk4ZTaD;};
extern const uint32_t __ZWQ5OGU2ODNU=0xED;
extern "C" uint32_t  __stdcall __ZWQ5OGU2ODNU_g(){return __ZWQ5OGU2ODNU;};
extern const uint32_t __OThlNjgzNTRe=0x98;
extern "C" uint32_t  __stdcall __OThlNjgzNTRe_g(){return __OThlNjgzNTRe;};
extern const uint32_t __ZTY4MzU0NWVl=0xE6;
extern "C" uint32_t  __stdcall __ZTY4MzU0NWVl_g(){return __ZTY4MzU0NWVl;};
extern const uint32_t __ODM1NDVlNjUU=0x83;
extern "C" uint32_t  __stdcall __ODM1NDVlNjUU_g(){return __ODM1NDVlNjUU;};
extern const uint32_t __NTQ1ZTY1MTTz=0x54;
extern "C" uint32_t  __stdcall __NTQ1ZTY1MTTz_g(){return __NTQ1ZTY1MTTz;};
extern const uint32_t __NWU2NTE0ZjNo=0x5E;
extern "C" uint32_t  __stdcall __NWU2NTE0ZjNo_g(){return __NWU2NTE0ZjNo;};
extern const uint32_t __NjUxNGYzNjgw=0x65;
extern "C" uint32_t  __stdcall __NjUxNGYzNjgw_g(){return __NjUxNGYzNjgw;};
extern const uint32_t __MTRmMzY4MzAR=0x14;
extern "C" uint32_t  __stdcall __MTRmMzY4MzAR_g(){return __MTRmMzY4MzAR;};
extern const uint32_t __ZjM2ODMwMTED=0xF3;
extern "C" uint32_t  __stdcall __ZjM2ODMwMTED_g(){return __ZjM2ODMwMTED;};
extern const uint32_t __NjgzMDExMDOe=0x68;
extern "C" uint32_t  __stdcall __NjgzMDExMDOe_g(){return __NjgzMDExMDOe;};
extern const uint32_t __MzAxMTAzOWU9=0x30;
extern "C" uint32_t  __stdcall __MzAxMTAzOWU9_g(){return __MzAxMTAzOWU9;};
extern const uint32_t __MTEwMzllM2Qy=0x11;
extern "C" uint32_t  __stdcall __MTEwMzllM2Qy_g(){return __MTEwMzllM2Qy;};
#endif
