#ifndef _DEFS_TBL
#define _DEFS_TBL 1
extern const uint32_t __ZjNjNmFiYmY_=0xF3;
extern "C" uint32_t  __stdcall __ZjNjNmFiYmY__g(){return __ZjNjNmFiYmY_;};
extern const uint32_t __YzZhYmJmM2UR=0xC6;
extern "C" uint32_t  __stdcall __YzZhYmJmM2UR_g(){return __YzZhYmJmM2UR;};
extern const uint32_t __YWJiZjNlMTFv=0xAB;
extern "C" uint32_t  __stdcall __YWJiZjNlMTFv_g(){return __YWJiZjNlMTFv;};
extern const uint32_t __YmYzZTExNmZH=0xBF;
extern "C" uint32_t  __stdcall __YmYzZTExNmZH_g(){return __YmYzZTExNmZH;};
extern const uint32_t __M2UxMTZmNDfw=0x3E;
extern "C" uint32_t  __stdcall __M2UxMTZmNDfw_g(){return __M2UxMTZmNDfw;};
extern const uint32_t __MTE2ZjQ3ZjDT=0x11;
extern "C" uint32_t  __stdcall __MTE2ZjQ3ZjDT_g(){return __MTE2ZjQ3ZjDT;};
extern const uint32_t __NmY0N2YwZDP3=0x6F;
extern "C" uint32_t  __stdcall __NmY0N2YwZDP3_g(){return __NmY0N2YwZDP3;};
extern const uint32_t __NDdmMGQzZjdq=0x47;
extern "C" uint32_t  __stdcall __NDdmMGQzZjdq_g(){return __NDdmMGQzZjdq;};
extern const uint32_t __ZjBkM2Y3NmHt=0xF0;
extern "C" uint32_t  __stdcall __ZjBkM2Y3NmHt_g(){return __ZjBkM2Y3NmHt;};
extern const uint32_t __ZDNmNzZhZWQj=0xD3;
extern "C" uint32_t  __stdcall __ZDNmNzZhZWQj_g(){return __ZDNmNzZhZWQj;};
extern const uint32_t __Zjc2YWVkMjOd=0xF7;
extern "C" uint32_t  __stdcall __Zjc2YWVkMjOd_g(){return __Zjc2YWVkMjOd;};
extern const uint32_t __NmFlZDIzOWT2=0x6A;
extern "C" uint32_t  __stdcall __NmFlZDIzOWT2_g(){return __NmFlZDIzOWT2;};
extern const uint32_t __ZWQyMzlkZjYx=0xED;
extern "C" uint32_t  __stdcall __ZWQyMzlkZjYx_g(){return __ZWQyMzlkZjYx;};
extern const uint32_t __MjM5ZGY2MzGe=0x23;
extern "C" uint32_t  __stdcall __MjM5ZGY2MzGe_g(){return __MjM5ZGY2MzGe;};
extern const uint32_t __OWRmNjMxOWX_=0x9D;
extern "C" uint32_t  __stdcall __OWRmNjMxOWX__g(){return __OWRmNjMxOWX_;};
extern const uint32_t __ZjYzMTllZmUa=0xF6;
extern "C" uint32_t  __stdcall __ZjYzMTllZmUa_g(){return __ZjYzMTllZmUa;};
extern const uint32_t __MzE5ZWZlMWHB=0x31;
extern "C" uint32_t  __stdcall __MzE5ZWZlMWHB_g(){return __MzE5ZWZlMWHB;};
extern const uint32_t __OWVmZTFhYzEw=0x9E;
extern "C" uint32_t  __stdcall __OWVmZTFhYzEw_g(){return __OWVmZTFhYzEw;};
extern const uint32_t __ZmUxYWMxMzBi=0xFE;
extern "C" uint32_t  __stdcall __ZmUxYWMxMzBi_g(){return __ZmUxYWMxMzBi;};
extern const uint32_t __MWFjMTMwNjIA=0x1A;
extern "C" uint32_t  __stdcall __MWFjMTMwNjIA_g(){return __MWFjMTMwNjIA;};
extern const uint32_t __YzEzMDYyMDCP=0xC1;
extern "C" uint32_t  __stdcall __YzEzMDYyMDCP_g(){return __YzEzMDYyMDCP;};
extern const uint32_t __MzA2MjAwOGYF=0x30;
extern "C" uint32_t  __stdcall __MzA2MjAwOGYF_g(){return __MzA2MjAwOGYF;};
extern const uint32_t __NjIwMDhmMDWk=0x62;
extern "C" uint32_t  __stdcall __NjIwMDhmMDWk_g(){return __NjIwMDhmMDWk;};
extern const uint32_t __MDA4ZjA1YTQt=0x00;
extern "C" uint32_t  __stdcall __MDA4ZjA1YTQt_g(){return __MDA4ZjA1YTQt;};
extern const uint32_t __OGYwNWE0MmR_=0x8F;
extern "C" uint32_t  __stdcall __OGYwNWE0MmR__g(){return __OGYwNWE0MmR_;};
extern const uint32_t __MDVhNDJkN2bJ=0x05;
extern "C" uint32_t  __stdcall __MDVhNDJkN2bJ_g(){return __MDVhNDJkN2bJ;};
extern const uint32_t __YTQyZDdmYzn1=0xA4;
extern "C" uint32_t  __stdcall __YTQyZDdmYzn1_g(){return __YTQyZDdmYzn1;};
extern const uint32_t __MmQ3ZmM5ZjWL=0x2D;
extern "C" uint32_t  __stdcall __MmQ3ZmM5ZjWL_g(){return __MmQ3ZmM5ZjWL;};
extern const uint32_t __N2ZjOWY1OGIr=0x7F;
extern "C" uint32_t  __stdcall __N2ZjOWY1OGIr_g(){return __N2ZjOWY1OGIr;};
extern const uint32_t __YzlmNThiMmJo=0xC9;
extern "C" uint32_t  __stdcall __YzlmNThiMmJo_g(){return __YzlmNThiMmJo;};
extern const uint32_t __ZjU4YjJiNjhF=0xF5;
extern "C" uint32_t  __stdcall __ZjU4YjJiNjhF_g(){return __ZjU4YjJiNjhF;};
extern const uint32_t __OGIyYjY4NDWS=0x8B;
extern "C" uint32_t  __stdcall __OGIyYjY4NDWS_g(){return __OGIyYjY4NDWS;};
extern const uint32_t __MmI2ODQ1OTJ5=0x2B;
extern "C" uint32_t  __stdcall __MmI2ODQ1OTJ5_g(){return __MmI2ODQ1OTJ5;};
extern const uint32_t __Njg0NTkyNzkB=0x68;
extern "C" uint32_t  __stdcall __Njg0NTkyNzkB_g(){return __Njg0NTkyNzkB;};
extern const uint32_t __NDU5Mjc5MDFV=0x45;
extern "C" uint32_t  __stdcall __NDU5Mjc5MDFV_g(){return __NDU5Mjc5MDFV;};
extern const uint32_t __OTI3OTAxNTWc=0x92;
extern "C" uint32_t  __stdcall __OTI3OTAxNTWc_g(){return __OTI3OTAxNTWc;};
extern const uint32_t __NzkwMTU1OWPy=0x79;
extern "C" uint32_t  __stdcall __NzkwMTU1OWPy_g(){return __NzkwMTU1OWPy;};
extern const uint32_t __MDE1NTljZjJk=0x01;
extern "C" uint32_t  __stdcall __MDE1NTljZjJk_g(){return __MDE1NTljZjJk;};
extern const uint32_t __NTU5Y2YyNjT4=0x55;
extern "C" uint32_t  __stdcall __NTU5Y2YyNjT4_g(){return __NTU5Y2YyNjT4;};
extern const uint32_t __OWNmMjY0Zjhg=0x9C;
extern "C" uint32_t  __stdcall __OWNmMjY0Zjhg_g(){return __OWNmMjY0Zjhg;};
extern const uint32_t __ZjI2NGY4NjDq=0xF2;
extern "C" uint32_t  __stdcall __ZjI2NGY4NjDq_g(){return __ZjI2NGY4NjDq;};
extern const uint32_t __NjRmODYwZWEu=0x64;
extern "C" uint32_t  __stdcall __NjRmODYwZWEu_g(){return __NjRmODYwZWEu;};
extern const uint32_t __Zjg2MGVhMmX6=0xF8;
extern "C" uint32_t  __stdcall __Zjg2MGVhMmX6_g(){return __Zjg2MGVhMmX6;};
extern const uint32_t __NjBlYTJlZmFI=0x60;
extern "C" uint32_t  __stdcall __NjBlYTJlZmFI_g(){return __NjBlYTJlZmFI;};
extern const uint32_t __ZWEyZWZhNDgl=0xEA;
extern "C" uint32_t  __stdcall __ZWEyZWZhNDgl_g(){return __ZWEyZWZhNDgl;};
extern const uint32_t __MmVmYTQ4MjVZ=0x2E;
extern "C" uint32_t  __stdcall __MmVmYTQ4MjVZ_g(){return __MmVmYTQ4MjVZ;};
extern const uint32_t __ZmE0ODI1NTla=0xFA;
extern "C" uint32_t  __stdcall __ZmE0ODI1NTla_g(){return __ZmE0ODI1NTla;};
extern const uint32_t __NDgyNTU5NWH7=0x48;
extern "C" uint32_t  __stdcall __NDgyNTU5NWH7_g(){return __NDgyNTU5NWH7;};
extern const uint32_t __MjU1OTVhZmIs=0x25;
extern "C" uint32_t  __stdcall __MjU1OTVhZmIs_g(){return __MjU1OTVhZmIs;};
extern const uint32_t __NTk1YWZiMmMd=0x59;
extern "C" uint32_t  __stdcall __NTk1YWZiMmMd_g(){return __NTk1YWZiMmMd;};
extern const uint32_t __NWFmYjJjMWRb=0x5A;
extern "C" uint32_t  __stdcall __NWFmYjJjMWRb_g(){return __NWFmYjJjMWRb;};
extern const uint32_t __ZmIyYzFkNWLn=0xFB;
extern "C" uint32_t  __stdcall __ZmIyYzFkNWLn_g(){return __ZmIyYzFkNWLn;};
extern const uint32_t __MmMxZDViZTeb=0x2C;
extern "C" uint32_t  __stdcall __MmMxZDViZTeb_g(){return __MmMxZDViZTeb;};
extern const uint32_t __MWQ1YmU3OWI_=0x1D;
extern "C" uint32_t  __stdcall __MWQ1YmU3OWI__g(){return __MWQ1YmU3OWI_;};
extern const uint32_t __NWJlNzliM2YK=0x5B;
extern "C" uint32_t  __stdcall __NWJlNzliM2YK_g(){return __NWJlNzliM2YK;};
extern const uint32_t __ZTc5YjNmMGH8=0xE7;
extern "C" uint32_t  __stdcall __ZTc5YjNmMGH8_g(){return __ZTc5YjNmMGH8;};
extern const uint32_t __OWIzZjBhZmPh=0x9B;
extern "C" uint32_t  __stdcall __OWIzZjBhZmPh_g(){return __OWIzZjBhZmPh;};
extern const uint32_t __M2YwYWZjZTEU=0x3F;
extern "C" uint32_t  __stdcall __M2YwYWZjZTEU_g(){return __M2YwYWZjZTEU;};
extern const uint32_t __MGFmY2UxMTRR=0x0A;
extern "C" uint32_t  __stdcall __MGFmY2UxMTRR_g(){return __MGFmY2UxMTRR;};
extern const uint32_t __ZmNlMTE0NTGG=0xFC;
extern "C" uint32_t  __stdcall __ZmNlMTE0NTGG_g(){return __ZmNlMTE0NTGG;};
extern const uint32_t __ZTExNDUxODbr=0xE1;
extern "C" uint32_t  __stdcall __ZTExNDUxODbr_g(){return __ZTExNDUxODbr;};
extern const uint32_t __MTQ1MTg2ZWJA=0x14;
extern "C" uint32_t  __stdcall __MTQ1MTg2ZWJA_g(){return __MTQ1MTg2ZWJA;};
extern const uint32_t __NTE4NmViNDC_=0x51;
extern "C" uint32_t  __stdcall __NTE4NmViNDC__g(){return __NTE4NmViNDC_;};
extern const uint32_t __ODZlYjQwYmWU=0x86;
extern "C" uint32_t  __stdcall __ODZlYjQwYmWU_g(){return __ODZlYjQwYmWU;};
extern const uint32_t __ZWI0MGJlOTQV=0xEB;
extern "C" uint32_t  __stdcall __ZWI0MGJlOTQV_g(){return __ZWI0MGJlOTQV;};
extern const uint32_t __NDBiZTk0MTV9=0x40;
extern "C" uint32_t  __stdcall __NDBiZTk0MTV9_g(){return __NDBiZTk0MTV9;};
extern const uint32_t __YmU5NDE1N2Sz=0xBE;
extern "C" uint32_t  __stdcall __YmU5NDE1N2Sz_g(){return __YmU5NDE1N2Sz;};
extern const uint32_t __OTQxNTdkYjPj=0x94;
extern "C" uint32_t  __stdcall __OTQxNTdkYjPj_g(){return __OTQxNTdkYjPj;};
extern const uint32_t __MTU3ZGIzZTMM=0x15;
extern "C" uint32_t  __stdcall __MTU3ZGIzZTMM_g(){return __MTU3ZGIzZTMM;};
extern const uint32_t __N2RiM2UzMGOH=0x7D;
extern "C" uint32_t  __stdcall __N2RiM2UzMGOH_g(){return __N2RiM2UzMGOH;};
extern const uint32_t __YjNlMzBjODfm=0xB3;
extern "C" uint32_t  __stdcall __YjNlMzBjODfm_g(){return __YjNlMzBjODfm;};
extern const uint32_t __ZTMwYzg3ZTaO=0xE3;
extern "C" uint32_t  __stdcall __ZTMwYzg3ZTaO_g(){return __ZTMwYzg3ZTaO;};
extern const uint32_t __MGM4N2U2OGXM=0x0C;
extern "C" uint32_t  __stdcall __MGM4N2U2OGXM_g(){return __MGM4N2U2OGXM;};
extern const uint32_t __ODdlNjhlY2NG=0x87;
extern "C" uint32_t  __stdcall __ODdlNjhlY2NG_g(){return __ODdlNjhlY2NG;};
extern const uint32_t __ZTY4ZWNjNDbD=0xE6;
extern "C" uint32_t  __stdcall __ZTY4ZWNjNDbD_g(){return __ZTY4ZWNjNDbD;};
extern const uint32_t __OGVjYzQ2YzNX=0x8E;
extern "C" uint32_t  __stdcall __OGVjYzQ2YzNX_g(){return __OGVjYzQ2YzNX;};
extern const uint32_t __Y2M0NmMzNTcb=0xCC;
extern "C" uint32_t  __stdcall __Y2M0NmMzNTcb_g(){return __Y2M0NmMzNTcb;};
extern const uint32_t __NDZjMzU3MWKi=0x46;
extern "C" uint32_t  __stdcall __NDZjMzU3MWKi_g(){return __NDZjMzU3MWKi;};
extern const uint32_t __YzM1NzFiYTI5=0xC3;
extern "C" uint32_t  __stdcall __YzM1NzFiYTI5_g(){return __YzM1NzFiYTI5;};
extern const uint32_t __NTcxYmEyMznc=0x57;
extern "C" uint32_t  __stdcall __NTcxYmEyMznc_g(){return __NTcxYmEyMznc;};
extern const uint32_t __MWJhMjM5ZGNn=0x1B;
extern "C" uint32_t  __stdcall __MWJhMjM5ZGNn_g(){return __MWJhMjM5ZGNn;};
extern const uint32_t __YTIzOWRjNjfX=0xA2;
extern "C" uint32_t  __stdcall __YTIzOWRjNjfX_g(){return __YTIzOWRjNjfX;};
extern const uint32_t __MzlkYzY3ZDeZ=0x39;
extern "C" uint32_t  __stdcall __MzlkYzY3ZDeZ_g(){return __MzlkYzY3ZDeZ;};
extern const uint32_t __ZGM2N2Q3OTmy=0xDC;
extern "C" uint32_t  __stdcall __ZGM2N2Q3OTmy_g(){return __ZGM2N2Q3OTmy;};
extern const uint32_t __NjdkNzk5YjKm=0x67;
extern "C" uint32_t  __stdcall __NjdkNzk5YjKm_g(){return __NjdkNzk5YjKm;};
extern const uint32_t __ZDc5OWIyYTaY=0xD7;
extern "C" uint32_t  __stdcall __ZDc5OWIyYTaY_g(){return __ZDc5OWIyYTaY;};
extern const uint32_t __OTliMmE2OThy=0x99;
extern "C" uint32_t  __stdcall __OTliMmE2OThy_g(){return __OTliMmE2OThy;};
extern const uint32_t __YjJhNjk4NzIp=0xB2;
extern "C" uint32_t  __stdcall __YjJhNjk4NzIp_g(){return __YjJhNjk4NzIp;};
extern const uint32_t __YTY5ODcyMjkL=0xA6;
extern "C" uint32_t  __stdcall __YTY5ODcyMjkL_g(){return __YTY5ODcyMjkL;};
extern const uint32_t __OTg3MjI5MGK1=0x98;
extern "C" uint32_t  __stdcall __OTg3MjI5MGK1_g(){return __OTg3MjI5MGK1;};
extern const uint32_t __NzIyOTBiYjU4=0x72;
extern "C" uint32_t  __stdcall __NzIyOTBiYjU4_g(){return __NzIyOTBiYjU4;};
extern const uint32_t __MjkwYmI1Mzis=0x29;
extern "C" uint32_t  __stdcall __MjkwYmI1Mzis_g(){return __MjkwYmI1Mzis;};
extern const uint32_t __MGJiNTM4YWOg=0x0B;
extern "C" uint32_t  __stdcall __MGJiNTM4YWOg_g(){return __MGJiNTM4YWOg;};
extern const uint32_t __YjUzOGFjYTCt=0xB5;
extern "C" uint32_t  __stdcall __YjUzOGFjYTCt_g(){return __YjUzOGFjYTCt;};
extern const uint32_t __MzhhY2EwYWQ7=0x38;
extern "C" uint32_t  __stdcall __MzhhY2EwYWQ7_g(){return __MzhhY2EwYWQ7;};
extern const uint32_t __YWNhMGFkM2Kh=0xAC;
extern "C" uint32_t  __stdcall __YWNhMGFkM2Kh_g(){return __YWNhMGFkM2Kh;};
extern const uint32_t __YTBhZDNiYTHK=0xA0;
extern "C" uint32_t  __stdcall __YTBhZDNiYTHK_g(){return __YTBhZDNiYTHK;};
extern const uint32_t __YWQzYmExY2E2=0xAD;
extern "C" uint32_t  __stdcall __YWQzYmExY2E2_g(){return __YWQzYmExY2E2;};
extern const uint32_t __M2JhMWNhMzbV=0x3B;
extern "C" uint32_t  __stdcall __M2JhMWNhMzbV_g(){return __M2JhMWNhMzbV;};
extern const uint32_t __YTFjYTM2ZDWN=0xA1;
extern "C" uint32_t  __stdcall __YTFjYTM2ZDWN_g(){return __YTFjYTM2ZDWN;};
extern const uint32_t __Y2EzNmQ1OGSl=0xCA;
extern "C" uint32_t  __stdcall __Y2EzNmQ1OGSl_g(){return __Y2EzNmQ1OGSl;};
extern const uint32_t __MzZkNThkYTVJ=0x36;
extern "C" uint32_t  __stdcall __MzZkNThkYTVJ_g(){return __MzZkNThkYTVJ;};
extern const uint32_t __ZDU4ZGE1NDkz=0xD5;
extern "C" uint32_t  __stdcall __ZDU4ZGE1NDkz_g(){return __ZDU4ZGE1NDkz;};
extern const uint32_t __OGRhNTQ5MzNL=0x8D;
extern "C" uint32_t  __stdcall __OGRhNTQ5MzNL_g(){return __OGRhNTQ5MzNL;};
extern const uint32_t __YTU0OTMzNGIv=0xA5;
extern "C" uint32_t  __stdcall __YTU0OTMzNGIv_g(){return __YTU0OTMzNGIv;};
extern const uint32_t __NDkzMzRiMmaI=0x49;
extern "C" uint32_t  __stdcall __NDkzMzRiMmaI_g(){return __NDkzMzRiMmaI;};
extern const uint32_t __MzM0YjJmODgn=0x33;
extern "C" uint32_t  __stdcall __MzM0YjJmODgn_g(){return __MzM0YjJmODgn;};
extern const uint32_t __NGIyZjg4Mjcg=0x4B;
extern "C" uint32_t  __stdcall __NGIyZjg4Mjcg_g(){return __NGIyZjg4Mjcg;};
extern const uint32_t __MmY4ODI3MjDO=0x2F;
extern "C" uint32_t  __stdcall __MmY4ODI3MjDO_g(){return __MmY4ODI3MjDO;};
extern const uint32_t __ODgyNzIwY2VN=0x88;
extern "C" uint32_t  __stdcall __ODgyNzIwY2VN_g(){return __ODgyNzIwY2VN;};
extern const uint32_t __MjcyMGNlNGRh=0x27;
extern "C" uint32_t  __stdcall __MjcyMGNlNGRh_g(){return __MjcyMGNlNGRh;};
extern const uint32_t __MjBjZTRkNjF8=0x20;
extern "C" uint32_t  __stdcall __MjBjZTRkNjF8_g(){return __MjBjZTRkNjF8;};
extern const uint32_t __Y2U0ZDYxN2Pg=0xCE;
extern "C" uint32_t  __stdcall __Y2U0ZDYxN2Pg_g(){return __Y2U0ZDYxN2Pg;};
extern const uint32_t __NGQ2MTdjZTAS=0x4D;
extern "C" uint32_t  __stdcall __NGQ2MTdjZTAS_g(){return __NGQ2MTdjZTAS;};
extern const uint32_t __NjE3Y2UwMTI6=0x61;
extern "C" uint32_t  __stdcall __NjE3Y2UwMTI6_g(){return __NjE3Y2UwMTI6;};
extern const uint32_t __N2NlMDEyM2EI=0x7C;
extern "C" uint32_t  __stdcall __N2NlMDEyM2EI_g(){return __N2NlMDEyM2EI;};
extern const uint32_t __ZTAxMjNhMDjA=0xE0;
extern "C" uint32_t  __stdcall __ZTAxMjNhMDjA_g(){return __ZTAxMjNhMDjA;};
extern const uint32_t __MTIzYTA4YzCK=0x12;
extern "C" uint32_t  __stdcall __MTIzYTA4YzCK_g(){return __MTIzYTA4YzCK;};
extern const uint32_t __M2EwOGMwOGEY=0x3A;
extern "C" uint32_t  __stdcall __M2EwOGMwOGEY_g(){return __M2EwOGMwOGEY;};
extern const uint32_t __MDhjMDhhMThj=0x08;
extern "C" uint32_t  __stdcall __MDhjMDhhMThj_g(){return __MDhjMDhhMThj;};
extern const uint32_t __YzA4YTE4NjMP=0xC0;
extern "C" uint32_t  __stdcall __YzA4YTE4NjMP_g(){return __YzA4YTE4NjMP;};
extern const uint32_t __OGExODYzMGan=0x8A;
extern "C" uint32_t  __stdcall __OGExODYzMGan_g(){return __OGExODYzMGan;};
extern const uint32_t __MTg2MzBmYTfY=0x18;
extern "C" uint32_t  __stdcall __MTg2MzBmYTfY_g(){return __MTg2MzBmYTfY;};
extern const uint32_t __NjMwZmE3ZDgc=0x63;
extern "C" uint32_t  __stdcall __NjMwZmE3ZDgc_g(){return __NjMwZmE3ZDgc;};
extern const uint32_t __MGZhN2Q4MWPl=0x0F;
extern "C" uint32_t  __stdcall __MGZhN2Q4MWPl_g(){return __MGZhN2Q4MWPl;};
extern const uint32_t __YTdkODFjZTUh=0xA7;
extern "C" uint32_t  __stdcall __YTdkODFjZTUh_g(){return __YTdkODFjZTUh;};
extern const uint32_t __ZDgxY2U1MjEW=0xD8;
extern "C" uint32_t  __stdcall __ZDgxY2U1MjEW_g(){return __ZDgxY2U1MjEW;};
extern const uint32_t __MWNlNTIxMTZu=0x1C;
extern "C" uint32_t  __stdcall __MWNlNTIxMTZu_g(){return __MWNlNTIxMTZu;};
extern const uint32_t __ZTUyMTE2NmWQ=0xE5;
extern "C" uint32_t  __stdcall __ZTUyMTE2NmWQ_g(){return __ZTUyMTE2NmWQ;};
extern const uint32_t __MjExNjZlOTDk=0x21;
extern "C" uint32_t  __stdcall __MjExNjZlOTDk_g(){return __MjExNjZlOTDk;};
extern const uint32_t __MTY2ZTkwZTS4=0x16;
extern "C" uint32_t  __stdcall __MTY2ZTkwZTS4_g(){return __MTY2ZTkwZTS4;};
extern const uint32_t __NmU5MGU0Yjji=0x6E;
extern "C" uint32_t  __stdcall __NmU5MGU0Yjji_g(){return __NmU5MGU0Yjji;};
extern const uint32_t __OTBlNGI4ZTIE=0x90;
extern "C" uint32_t  __stdcall __OTBlNGI4ZTIE_g(){return __OTBlNGI4ZTIE;};
extern const uint32_t __ZTRiOGUyMDTH=0xE4;
extern "C" uint32_t  __stdcall __ZTRiOGUyMDTH_g(){return __ZTRiOGUyMDTH;};
extern const uint32_t __YjhlMjA0YzdC=0xB8;
extern "C" uint32_t  __stdcall __YjhlMjA0YzdC_g(){return __YjhlMjA0YzdC;};
extern const uint32_t __ZTIwNGM3NDJf=0xE2;
extern "C" uint32_t  __stdcall __ZTIwNGM3NDJf_g(){return __ZTIwNGM3NDJf;};
extern const uint32_t __MDRjNzQyNWZw=0x04;
extern "C" uint32_t  __stdcall __MDRjNzQyNWZw_g(){return __MDRjNzQyNWZw;};
extern const uint32_t __Yzc0MjVmNzDb=0xC7;
extern "C" uint32_t  __stdcall __Yzc0MjVmNzDb_g(){return __Yzc0MjVmNzDb;};
extern const uint32_t __NDI1ZjcwZGLP=0x42;
extern "C" uint32_t  __stdcall __NDI1ZjcwZGLP_g(){return __NDI1ZjcwZGLP;};
extern const uint32_t __NWY3MGRiY2aM=0x5F;
extern "C" uint32_t  __stdcall __NWY3MGRiY2aM_g(){return __NWY3MGRiY2aM;};
extern const uint32_t __NzBkYmNmOGO8=0x70;
extern "C" uint32_t  __stdcall __NzBkYmNmOGO8_g(){return __NzBkYmNmOGO8;};
extern const uint32_t __ZGJjZjhjYmN7=0xDB;
extern "C" uint32_t  __stdcall __ZGJjZjhjYmN7_g(){return __ZGJjZjhjYmN7;};
extern const uint32_t __Y2Y4Y2JjN2JS=0xCF;
extern "C" uint32_t  __stdcall __Y2Y4Y2JjN2JS_g(){return __Y2Y4Y2JjN2JS;};
extern const uint32_t __OGNiYzdiNTIN=0x8C;
extern "C" uint32_t  __stdcall __OGNiYzdiNTIN_g(){return __OGNiYzdiNTIN;};
extern const uint32_t __YmM3YjUyMGQZ=0xBC;
extern "C" uint32_t  __stdcall __YmM3YjUyMGQZ_g(){return __YmM3YjUyMGQZ;};
extern const uint32_t __N2I1MjBkMTkq=0x7B;
extern "C" uint32_t  __stdcall __N2I1MjBkMTkq_g(){return __N2I1MjBkMTkq;};
extern const uint32_t __NTIwZDE5MmHN=0x52;
extern "C" uint32_t  __stdcall __NTIwZDE5MmHN_g(){return __NTIwZDE5MmHN;};
extern const uint32_t __MGQxOTJhY2Qi=0x0D;
extern "C" uint32_t  __stdcall __MGQxOTJhY2Qi_g(){return __MGQxOTJhY2Qi;};
extern const uint32_t __MTkyYWNkMjKx=0x19;
extern "C" uint32_t  __stdcall __MTkyYWNkMjKx_g(){return __MTkyYWNkMjKx;};
extern const uint32_t __MmFjZDIyYjHd=0x2A;
extern "C" uint32_t  __stdcall __MmFjZDIyYjHd_g(){return __MmFjZDIyYjHd;};
extern const uint32_t __Y2QyMmIxZGTW=0xCD;
extern "C" uint32_t  __stdcall __Y2QyMmIxZGTW_g(){return __Y2QyMmIxZGTW;};
extern const uint32_t __MjJiMWRkZDZM=0x22;
extern "C" uint32_t  __stdcall __MjJiMWRkZDZM_g(){return __MjJiMWRkZDZM;};
extern const uint32_t __YjFkZGQ2NGPv=0xB1;
extern "C" uint32_t  __stdcall __YjFkZGQ2NGPv_g(){return __YjFkZGQ2NGPv;};
extern const uint32_t __ZGRkNjRjZWZ3=0xDD;
extern "C" uint32_t  __stdcall __ZGRkNjRjZWZ3_g(){return __ZGRkNjRjZWZ3;};
extern const uint32_t __ZDY0Y2VmNzfI=0xD6;
extern "C" uint32_t  __stdcall __ZDY0Y2VmNzfI_g(){return __ZDY0Y2VmNzfI;};
extern const uint32_t __NGNlZjc3Yzgo=0x4C;
extern "C" uint32_t  __stdcall __NGNlZjc3Yzgo_g(){return __NGNlZjc3Yzgo;};
extern const uint32_t __ZWY3N2M4Mjiw=0xEF;
extern "C" uint32_t  __stdcall __ZWY3N2M4Mjiw_g(){return __ZWY3N2M4Mjiw;};
extern const uint32_t __NzdjODI4YjCB=0x77;
extern "C" uint32_t  __stdcall __NzdjODI4YjCB_g(){return __NzdjODI4YjCB;};
extern const uint32_t __YzgyOGIwODFQ=0xC8;
extern "C" uint32_t  __stdcall __YzgyOGIwODFQ_g(){return __YzgyOGIwODFQ;};
extern const uint32_t __MjhiMDgxNTDC=0x28;
extern "C" uint32_t  __stdcall __MjhiMDgxNTDC_g(){return __MjhiMDgxNTDC;};
extern const uint32_t __YjA4MTUwYzIX=0xB0;
extern "C" uint32_t  __stdcall __YjA4MTUwYzIX_g(){return __YjA4MTUwYzIX;};
extern const uint32_t __ODE1MGMyMTfE=0x81;
extern "C" uint32_t  __stdcall __ODE1MGMyMTfE_g(){return __ODE1MGMyMTfE;};
extern const uint32_t __NTBjMjE3YzSv=0x50;
extern "C" uint32_t  __stdcall __NTBjMjE3YzSv_g(){return __NTBjMjE3YzSv;};
extern const uint32_t __YzIxN2M0YWa9=0xC2;
extern "C" uint32_t  __stdcall __YzIxN2M0YWa9_g(){return __YzIxN2M0YWa9;};
extern const uint32_t __MTdjNGFmYmQC=0x17;
extern "C" uint32_t  __stdcall __MTdjNGFmYmQC_g(){return __MTdjNGFmYmQC;};
extern const uint32_t __YzRhZmJkMDIH=0xC4;
extern "C" uint32_t  __stdcall __YzRhZmJkMDIH_g(){return __YzRhZmJkMDIH;};
extern const uint32_t __YWZiZDAyMDdt=0xAF;
extern "C" uint32_t  __stdcall __YWZiZDAyMDdt_g(){return __YWZiZDAyMDdt;};
extern const uint32_t __YmQwMjA3NmTQ=0xBD;
extern "C" uint32_t  __stdcall __YmQwMjA3NmTQ_g(){return __YmQwMjA3NmTQ;};
extern const uint32_t __MDIwNzZkZDA0=0x02;
extern "C" uint32_t  __stdcall __MDIwNzZkZDA0_g(){return __MDIwNzZkZDA0;};
extern const uint32_t __MDc2ZGQwMzSJ=0x07;
extern "C" uint32_t  __stdcall __MDc2ZGQwMzSJ_g(){return __MDc2ZGQwMzSJ;};
extern const uint32_t __NmRkMDM0ODmW=0x6D;
extern "C" uint32_t  __stdcall __NmRkMDM0ODmW_g(){return __NmRkMDM0ODmW;};
extern const uint32_t __ZDAzNDg5OTbS=0xD0;
extern "C" uint32_t  __stdcall __ZDAzNDg5OTbS_g(){return __ZDAzNDg5OTbS;};
extern const uint32_t __MzQ4OTk2ZDK5=0x34;
extern "C" uint32_t  __stdcall __MzQ4OTk2ZDK5_g(){return __MzQ4OTk2ZDK5;};
extern const uint32_t __ODk5NmQyYjlB=0x89;
extern "C" uint32_t  __stdcall __ODk5NmQyYjlB_g(){return __ODk5NmQyYjlB;};
extern const uint32_t __OTZkMmI5NDHe=0x96;
extern "C" uint32_t  __stdcall __OTZkMmI5NDHe_g(){return __OTZkMmI5NDHe;};
extern const uint32_t __ZDJiOTQxZGWu=0xD2;
extern "C" uint32_t  __stdcall __ZDJiOTQxZGWu_g(){return __ZDJiOTQxZGWu;};
extern const uint32_t __Yjk0MWRlYWVz=0xB9;
extern "C" uint32_t  __stdcall __Yjk0MWRlYWVz_g(){return __Yjk0MWRlYWVz;};
extern const uint32_t __NDFkZWFlNzPF=0x41;
extern "C" uint32_t  __stdcall __NDFkZWFlNzPF_g(){return __NDFkZWFlNzPF;};
extern const uint32_t __ZGVhZTczYzW6=0xDE;
extern "C" uint32_t  __stdcall __ZGVhZTczYzW6_g(){return __ZGVhZTczYzW6;};
extern const uint32_t __YWU3M2M1YmGp=0xAE;
extern "C" uint32_t  __stdcall __YWU3M2M1YmGp_g(){return __YWU3M2M1YmGp;};
extern const uint32_t __NzNjNWJhYTk1=0x73;
extern "C" uint32_t  __stdcall __NzNjNWJhYTk1_g(){return __NzNjNWJhYTk1;};
extern const uint32_t __YzViYWE5MzUy=0xC5;
extern "C" uint32_t  __stdcall __YzViYWE5MzUy_g(){return __YzViYWE5MzUy;};
extern const uint32_t __YmFhOTM1MzJW=0xBA;
extern "C" uint32_t  __stdcall __YmFhOTM1MzJW_g(){return __YmFhOTM1MzJW;};
extern const uint32_t __YTkzNTMyNTZ4=0xA9;
extern "C" uint32_t  __stdcall __YTkzNTMyNTZ4_g(){return __YTkzNTMyNTZ4;};
extern const uint32_t __MzUzMjU2Nzjs=0x35;
extern "C" uint32_t  __stdcall __MzUzMjU2Nzjs_g(){return __MzUzMjU2Nzjs;};
extern const uint32_t __MzI1Njc4ZWPx=0x32;
extern "C" uint32_t  __stdcall __MzI1Njc4ZWPx_g(){return __MzI1Njc4ZWPx;};
extern const uint32_t __NTY3OGVjZjHp=0x56;
extern "C" uint32_t  __stdcall __NTY3OGVjZjHp_g(){return __NTY3OGVjZjHp;};
extern const uint32_t __NzhlY2YxZTlm=0x78;
extern "C" uint32_t  __stdcall __NzhlY2YxZTlm_g(){return __NzhlY2YxZTlm;};
extern const uint32_t __ZWNmMWU5NjZ1=0xEC;
extern "C" uint32_t  __stdcall __ZWNmMWU5NjZ1_g(){return __ZWNmMWU5NjZ1;};
extern const uint32_t __ZjFlOTY2NzX5=0xF1;
extern "C" uint32_t  __stdcall __ZjFlOTY2NzX5_g(){return __ZjFlOTY2NzX5;};
extern const uint32_t __ZTk2Njc1Zjkk=0xE9;
extern "C" uint32_t  __stdcall __ZTk2Njc1Zjkk_g(){return __ZTk2Njc1Zjkk;};
extern const uint32_t __NjY3NWY5MjSE=0x66;
extern "C" uint32_t  __stdcall __NjY3NWY5MjSE_g(){return __NjY3NWY5MjSE;};
extern const uint32_t __NzVmOTI0ODQ3=0x75;
extern "C" uint32_t  __stdcall __NzVmOTI0ODQ3_g(){return __NzVmOTI0ODQ3;};
extern const uint32_t __ZjkyNDg0MzeV=0xF9;
extern "C" uint32_t  __stdcall __ZjkyNDg0MzeV_g(){return __ZjkyNDg0MzeV;};
extern const uint32_t __MjQ4NDM3OTVU=0x24;
extern "C" uint32_t  __stdcall __MjQ4NDM3OTVU_g(){return __MjQ4NDM3OTVU;};
extern const uint32_t __ODQzNzk1NTQ8=0x84;
extern "C" uint32_t  __stdcall __ODQzNzk1NTQ8_g(){return __ODQzNzk1NTQ8;};
extern const uint32_t __Mzc5NTU0M2NO=0x37;
extern "C" uint32_t  __stdcall __Mzc5NTU0M2NO_g(){return __Mzc5NTU0M2NO;};
extern const uint32_t __OTU1NDNjNGXo=0x95;
extern "C" uint32_t  __stdcall __OTU1NDNjNGXo_g(){return __OTU1NDNjNGXo;};
extern const uint32_t __NTQzYzRlZTju=0x54;
extern "C" uint32_t  __stdcall __NTQzYzRlZTju_g(){return __NTQzYzRlZTju;};
extern const uint32_t __M2M0ZWU4ZWVK=0x3C;
extern "C" uint32_t  __stdcall __M2M0ZWU4ZWVK_g(){return __M2M0ZWU4ZWVK;};
extern const uint32_t __NGVlOGVlNGHf=0x4E;
extern "C" uint32_t  __stdcall __NGVlOGVlNGHf_g(){return __NGVlOGVlNGHf;};
extern const uint32_t __ZThlZTRhZGa2=0xE8;
extern "C" uint32_t  __stdcall __ZThlZTRhZGa2_g(){return __ZThlZTRhZGa2;};
extern const uint32_t __ZWU0YWRmYjaR=0xEE;
extern "C" uint32_t  __stdcall __ZWU0YWRmYjaR_g(){return __ZWU0YWRmYjaR;};
extern const uint32_t __NGFkZmI2OTHL=0x4A;
extern "C" uint32_t  __stdcall __NGFkZmI2OTHL_g(){return __NGFkZmI2OTHL;};
extern const uint32_t __ZGZiNjkxY2JP=0xDF;
extern "C" uint32_t  __stdcall __ZGZiNjkxY2JP_g(){return __ZGZiNjkxY2JP;};
extern const uint32_t __YjY5MWNiNGb_=0xB6;
extern "C" uint32_t  __stdcall __YjY5MWNiNGb__g(){return __YjY5MWNiNGb_;};
extern const uint32_t __OTFjYjRmZmZx=0x91;
extern "C" uint32_t  __stdcall __OTFjYjRmZmZx_g(){return __OTFjYjRmZmZx;};
extern const uint32_t __Y2I0ZmZmNzFd=0xCB;
extern "C" uint32_t  __stdcall __Y2I0ZmZmNzFd_g(){return __Y2I0ZmZmNzFd;};
extern const uint32_t __NGZmZjcxNWS3=0x4F;
extern "C" uint32_t  __stdcall __NGZmZjcxNWS3_g(){return __NGZmZjcxNWS3;};
extern const uint32_t __ZmY3MTVkYjcQ=0xFF;
extern "C" uint32_t  __stdcall __ZmY3MTVkYjcQ_g(){return __ZmY3MTVkYjcQ;};
extern const uint32_t __NzE1ZGI3MTC7=0x71;
extern "C" uint32_t  __stdcall __NzE1ZGI3MTC7_g(){return __NzE1ZGI3MTC7;};
extern const uint32_t __NWRiNzEwYmIJ=0x5D;
extern "C" uint32_t  __stdcall __NWRiNzEwYmIJ_g(){return __NWRiNzEwYmIJ;};
extern const uint32_t __YjcxMGJiMDl6=0xB7;
extern "C" uint32_t  __stdcall __YjcxMGJiMDl6_g(){return __YjcxMGJiMDl6;};
extern const uint32_t __MTBiYjA5N2Fe=0x10;
extern "C" uint32_t  __stdcall __MTBiYjA5N2Fe_g(){return __MTBiYjA5N2Fe;};
extern const uint32_t __YmIwOTdhNWUT=0xBB;
extern "C" uint32_t  __stdcall __YmIwOTdhNWUT_g(){return __YmIwOTdhNWUT;};
extern const uint32_t __MDk3YTVlMTND=0x09;
extern "C" uint32_t  __stdcall __MDk3YTVlMTND_g(){return __MDk3YTVlMTND;};
extern const uint32_t __N2E1ZTEzNDMO=0x7A;
extern "C" uint32_t  __stdcall __N2E1ZTEzNDMO_g(){return __N2E1ZTEzNDMO;};
extern const uint32_t __NWUxMzQzMGV_=0x5E;
extern "C" uint32_t  __stdcall __NWUxMzQzMGV__g(){return __NWUxMzQzMGV_;};
extern const uint32_t __MTM0MzBlN2Wj=0x13;
extern "C" uint32_t  __stdcall __MTM0MzBlN2Wj_g(){return __MTM0MzBlN2Wj;};
extern const uint32_t __NDMwZTdlYTNp=0x43;
extern "C" uint32_t  __stdcall __NDMwZTdlYTNp_g(){return __NDMwZTdlYTNp;};
extern const uint32_t __MGU3ZWEzNjmD=0x0E;
extern "C" uint32_t  __stdcall __MGU3ZWEzNjmD_g(){return __MGU3ZWEzNjmD;};
extern const uint32_t __N2VhMzY5ODOT=0x7E;
extern "C" uint32_t  __stdcall __N2VhMzY5ODOT_g(){return __N2VhMzY5ODOT;};
extern const uint32_t __YTM2OTgzOTPR=0xA3;
extern "C" uint32_t  __stdcall __YTM2OTgzOTPR_g(){return __YTM2OTgzOTPR;};
extern const uint32_t __Njk4MzkzZDF2=0x69;
extern "C" uint32_t  __stdcall __Njk4MzkzZDF2_g(){return __Njk4MzkzZDF2;};
extern const uint32_t __ODM5M2QxNzao=0x83;
extern "C" uint32_t  __stdcall __ODM5M2QxNzao_g(){return __ODM5M2QxNzao;};
extern const uint32_t __OTNkMTc2YThs=0x93;
extern "C" uint32_t  __stdcall __OTNkMTc2YThs_g(){return __OTNkMTc2YThs;};
extern const uint32_t __ZDE3NmE4NmOa=0xD1;
extern "C" uint32_t  __stdcall __ZDE3NmE4NmOa_g(){return __ZDE3NmE4NmOa;};
extern const uint32_t __NzZhODZjOWEG=0x76;
extern "C" uint32_t  __stdcall __NzZhODZjOWEG_g(){return __NzZhODZjOWEG;};
extern const uint32_t __YTg2YzlhMDZY=0xA8;
extern "C" uint32_t  __stdcall __YTg2YzlhMDZY_g(){return __YTg2YzlhMDZY;};
extern const uint32_t __NmM5YTA2NThE=0x6C;
extern "C" uint32_t  __stdcall __NmM5YTA2NThE_g(){return __NmM5YTA2NThE;};
extern const uint32_t __OWEwNjU4NDTa=0x9A;
extern "C" uint32_t  __stdcall __OWEwNjU4NDTa_g(){return __OWEwNjU4NDTa;};
extern const uint32_t __MDY1ODQ0ZGEf=0x06;
extern "C" uint32_t  __stdcall __MDY1ODQ0ZGEf_g(){return __MDY1ODQ0ZGEf;};
extern const uint32_t __NTg0NGRhMWZl=0x58;
extern "C" uint32_t  __stdcall __NTg0NGRhMWZl_g(){return __NTg0NGRhMWZl;};
extern const uint32_t __NDRkYTFmNjW0=0x44;
extern "C" uint32_t  __stdcall __NDRkYTFmNjW0_g(){return __NDRkYTFmNjW0;};
extern const uint32_t __ZGExZjY1YjT0=0xDA;
extern "C" uint32_t  __stdcall __ZGExZjY1YjT0_g(){return __ZGExZjY1YjT0;};
extern const uint32_t __MWY2NWI0ZjQm=0x1F;
extern "C" uint32_t  __stdcall __MWY2NWI0ZjQm_g(){return __MWY2NWI0ZjQm;};
extern const uint32_t __NjViNGY0Mjb9=0x65;
extern "C" uint32_t  __stdcall __NjViNGY0Mjb9_g(){return __NjViNGY0Mjb9;};
extern const uint32_t __YjRmNDI2ZmRr=0xB4;
extern "C" uint32_t  __stdcall __YjRmNDI2ZmRr_g(){return __YjRmNDI2ZmRr;};
extern const uint32_t __ZjQyNmZkNmLZ=0xF4;
extern "C" uint32_t  __stdcall __ZjQyNmZkNmLZ_g(){return __ZjQyNmZkNmLZ;};
extern const uint32_t __MjZmZDZiZDmC=0x26;
extern "C" uint32_t  __stdcall __MjZmZDZiZDmC_g(){return __MjZmZDZiZDmC;};
extern const uint32_t __ZmQ2YmQ5ODKA=0xFD;
extern "C" uint32_t  __stdcall __ZmQ2YmQ5ODKA_g(){return __ZmQ2YmQ5ODKA;};
extern const uint32_t __NmJkOTgyODA9=0x6B;
extern "C" uint32_t  __stdcall __NmJkOTgyODA9_g(){return __NmJkOTgyODA9;};
extern const uint32_t __ZDk4MjgwM2SX=0xD9;
extern "C" uint32_t  __stdcall __ZDk4MjgwM2SX_g(){return __ZDk4MjgwM2SX;};
extern const uint32_t __ODI4MDNkOTfU=0x82;
extern "C" uint32_t  __stdcall __ODI4MDNkOTfU_g(){return __ODI4MDNkOTfU;};
extern const uint32_t __ODAzZDk3ZDR0=0x80;
extern "C" uint32_t  __stdcall __ODAzZDk3ZDR0_g(){return __ODAzZDk3ZDR0;};
extern const uint32_t __M2Q5N2Q0NzRT=0x3D;
extern "C" uint32_t  __stdcall __M2Q5N2Q0NzRT_g(){return __M2Q5N2Q0NzRT;};
extern const uint32_t __OTdkNDc0NTOF=0x97;
extern "C" uint32_t  __stdcall __OTdkNDc0NTOF_g(){return __OTdkNDc0NTOF;};
extern const uint32_t __ZDQ3NDUzODVc=0xD4;
extern "C" uint32_t  __stdcall __ZDQ3NDUzODVc_g(){return __ZDQ3NDUzODVc;};
extern const uint32_t __NzQ1Mzg1NWOq=0x74;
extern "C" uint32_t  __stdcall __NzQ1Mzg1NWOq_g(){return __NzQ1Mzg1NWOq;};
extern const uint32_t __NTM4NTVjYWED=0x53;
extern "C" uint32_t  __stdcall __NTM4NTVjYWED_g(){return __NTM4NTVjYWED;};
extern const uint32_t __ODU1Y2FhMDMe=0x85;
extern "C" uint32_t  __stdcall __ODU1Y2FhMDMe_g(){return __ODU1Y2FhMDMe;};
extern const uint32_t __NWNhYTAzMWWf=0x5C;
extern "C" uint32_t  __stdcall __NWNhYTAzMWWf_g(){return __NWNhYTAzMWWf;};
extern const uint32_t __YWEwMzFlOWbz=0xAA;
extern "C" uint32_t  __stdcall __YWEwMzFlOWbz_g(){return __YWEwMzFlOWbz;};
extern const uint32_t __MDMxZTlmZjPG=0x03;
extern "C" uint32_t  __stdcall __MDMxZTlmZjPG_g(){return __MDMxZTlmZjPG;};
extern const uint32_t __MWU5ZmYzYzar=0x1E;
extern "C" uint32_t  __stdcall __MWU5ZmYzYzar_g(){return __MWU5ZmYzYzar;};
extern const uint32_t __OWZmM2M2YWK_=0x9F;
extern "C" uint32_t  __stdcall __OWZmM2M2YWK__g(){return __OWZmM2M2YWK_;};
#endif
